rmq:
  host: 127.0.0.1
  user: erksystem
  password: mHrLhkGcg3QhvtvFEe71/Y5PYUEj7iy4
  port: 10001
  incoming-queue:
    api: ERK_API_QUEUE
    provision: ERK_PROVISION_QUEUE
  api-queue-name: ERK_TEST

performance:
  rmq-consumer-count: 8

prometheus:
  activate: false
  port: 8080
  metrics_path: /metrics/prometheus