rmq:
  host: 127.0.0.1
  user: erksystem
  password: mHrLhkGcg3QhvtvFEe71/Y5PYUEj7iy4
  incoming-queues:
    - INCOMING_QUEUE_TEST
    - INCOMING_QUEUE_TEST_2

performance:
  rmq-consumer-count: 8

dbms:
  host: 127.0.0.1
  port: 3306
  user: erk
  password: L7ZD94NgdCA/yf+2euiSPQ==
  database: ERK_SYS
  jdbc-params: serverTimezone=UTC&connectTimeout=3000&socketTimeout=2000

prometheus:
  activate: false
  port: 8080
  metrics_path: /metrics/prometheus