rmq:
  host: 127.0.0.1
  user: erksystem
  password: mHrLhkGcg3QhvtvFEe71/Y5PYUEj7iy4
  port: 10001
  incoming-queue:
    api: ERK_API_QUEUE
    subsystem: ERK_SUBSYSTEM_QUEUE
  outgoing-queue:
    api: API_QUEUE
    subsystem: SUBSYSTEM_QUEUE

performance:
  rmq-consumer-count: 8

dbms:
  host: 127.0.0.1
  port: 3306
  user: erk
  password: L7ZD94NgdCA/yf+2euiSPQ==
  database: ERK_SYS
  jdbc-params: serverTimezone=UTC&connectTimeout=3000&socketTimeout=2000

prometheus:
  activate: false
  port: 8080
  metrics_path: /metrics/prometheus