// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkProvMsg.proto

package com.erksystem.protobuf.prov;

public interface DelServiceProviderInfoRQOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DelServiceProviderInfoRQ)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string OrgName = 1;</code>
   * @return The orgName.
   */
  java.lang.String getOrgName();
  /**
   * <code>string OrgName = 1;</code>
   * @return The bytes for orgName.
   */
  com.google.protobuf.ByteString
      getOrgNameBytes();

  /**
   * <code>string OrgPwd = 2;</code>
   * @return The orgPwd.
   */
  java.lang.String getOrgPwd();
  /**
   * <code>string OrgPwd = 2;</code>
   * @return The bytes for orgPwd.
   */
  com.google.protobuf.ByteString
      getOrgPwdBytes();
}
