// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkProvMsg.proto

// Protobuf Java Version: 3.25.0
package com.erksystem.protobuf.prov;

/**
 * Protobuf enum {@code ErkMsgType_e}
 */
public enum ErkMsgType_e
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ErkMsgType_unknown = 0;</code>
   */
  ErkMsgType_unknown(0),
  /**
   * <code>ErkServiceConnRQ = 1;</code>
   */
  ErkServiceConnRQ(1),
  /**
   * <code>ErkServiceConnRP = 2;</code>
   */
  ErkServiceConnRP(2),
  /**
   * <code>ErkServiceDisConnRQ = 3;</code>
   */
  ErkServiceDisConnRQ(3),
  /**
   * <code>ErkServiceDisConnRP = 4;</code>
   */
  ErkServiceDisConnRP(4),
  /**
   * <code>AddServiceProviderInfoRQ = 5;</code>
   */
  AddServiceProviderInfoRQ(5),
  /**
   * <code>AddServiceProviderInfoRP = 6;</code>
   */
  AddServiceProviderInfoRP(6),
  /**
   * <code>DelServiceProviderInfoRQ = 7;</code>
   */
  DelServiceProviderInfoRQ(7),
  /**
   * <code>DelServiceProviderInfoRP = 8;</code>
   */
  DelServiceProviderInfoRP(8),
  /**
   * <code>UpdServiceProviderInfoRQ = 9;</code>
   */
  UpdServiceProviderInfoRQ(9),
  /**
   * <code>UpdServiceProviderInfoRP = 10;</code>
   */
  UpdServiceProviderInfoRP(10),
  /**
   * <code>AddUserInfoRQ = 11;</code>
   */
  AddUserInfoRQ(11),
  /**
   * <code>AddUserInfoRp = 12;</code>
   */
  AddUserInfoRp(12),
  /**
   * <code>DelUserInfoRQ = 13;</code>
   */
  DelUserInfoRQ(13),
  /**
   * <code>DelUserInfoRp = 14;</code>
   */
  DelUserInfoRp(14),
  /**
   * <code>UpdUserInfoRQ = 15;</code>
   */
  UpdUserInfoRQ(15),
  /**
   * <code>UpdUserInfoRP = 16;</code>
   */
  UpdUserInfoRP(16),
  /**
   * <code>EmoRecogCreateRQ = 17;</code>
   */
  EmoRecogCreateRQ(17),
  /**
   * <code>EmoRecogCreateRP = 18;</code>
   */
  EmoRecogCreateRP(18),
  /**
   * <code>EmoRecogDeleteRQ = 19;</code>
   */
  EmoRecogDeleteRQ(19),
  /**
   * <code>EmoRecogDeleteRP = 20;</code>
   */
  EmoRecogDeleteRP(20),
  /**
   * <code>PhysioEmoRecogRQ = 21;</code>
   */
  PhysioEmoRecogRQ(21),
  /**
   * <code>SpeechEmoRecogRQ = 22;</code>
   */
  SpeechEmoRecogRQ(22),
  /**
   * <code>FaceEmoRecogRQ = 23;</code>
   */
  FaceEmoRecogRQ(23),
  /**
   * <code>EmoRecogRQ = 24;</code>
   */
  EmoRecogRQ(24),
  /**
   * <code>EmoRecogRP = 25;</code>
   */
  EmoRecogRP(25),
  /**
   * <code>ErkMsgType_reserved1 = 26;</code>
   */
  ErkMsgType_reserved1(26),
  /**
   * <code>ErkMsgType_reserved2 = 27;</code>
   */
  ErkMsgType_reserved2(27),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ErkMsgType_unknown = 0;</code>
   */
  public static final int ErkMsgType_unknown_VALUE = 0;
  /**
   * <code>ErkServiceConnRQ = 1;</code>
   */
  public static final int ErkServiceConnRQ_VALUE = 1;
  /**
   * <code>ErkServiceConnRP = 2;</code>
   */
  public static final int ErkServiceConnRP_VALUE = 2;
  /**
   * <code>ErkServiceDisConnRQ = 3;</code>
   */
  public static final int ErkServiceDisConnRQ_VALUE = 3;
  /**
   * <code>ErkServiceDisConnRP = 4;</code>
   */
  public static final int ErkServiceDisConnRP_VALUE = 4;
  /**
   * <code>AddServiceProviderInfoRQ = 5;</code>
   */
  public static final int AddServiceProviderInfoRQ_VALUE = 5;
  /**
   * <code>AddServiceProviderInfoRP = 6;</code>
   */
  public static final int AddServiceProviderInfoRP_VALUE = 6;
  /**
   * <code>DelServiceProviderInfoRQ = 7;</code>
   */
  public static final int DelServiceProviderInfoRQ_VALUE = 7;
  /**
   * <code>DelServiceProviderInfoRP = 8;</code>
   */
  public static final int DelServiceProviderInfoRP_VALUE = 8;
  /**
   * <code>UpdServiceProviderInfoRQ = 9;</code>
   */
  public static final int UpdServiceProviderInfoRQ_VALUE = 9;
  /**
   * <code>UpdServiceProviderInfoRP = 10;</code>
   */
  public static final int UpdServiceProviderInfoRP_VALUE = 10;
  /**
   * <code>AddUserInfoRQ = 11;</code>
   */
  public static final int AddUserInfoRQ_VALUE = 11;
  /**
   * <code>AddUserInfoRp = 12;</code>
   */
  public static final int AddUserInfoRp_VALUE = 12;
  /**
   * <code>DelUserInfoRQ = 13;</code>
   */
  public static final int DelUserInfoRQ_VALUE = 13;
  /**
   * <code>DelUserInfoRp = 14;</code>
   */
  public static final int DelUserInfoRp_VALUE = 14;
  /**
   * <code>UpdUserInfoRQ = 15;</code>
   */
  public static final int UpdUserInfoRQ_VALUE = 15;
  /**
   * <code>UpdUserInfoRP = 16;</code>
   */
  public static final int UpdUserInfoRP_VALUE = 16;
  /**
   * <code>EmoRecogCreateRQ = 17;</code>
   */
  public static final int EmoRecogCreateRQ_VALUE = 17;
  /**
   * <code>EmoRecogCreateRP = 18;</code>
   */
  public static final int EmoRecogCreateRP_VALUE = 18;
  /**
   * <code>EmoRecogDeleteRQ = 19;</code>
   */
  public static final int EmoRecogDeleteRQ_VALUE = 19;
  /**
   * <code>EmoRecogDeleteRP = 20;</code>
   */
  public static final int EmoRecogDeleteRP_VALUE = 20;
  /**
   * <code>PhysioEmoRecogRQ = 21;</code>
   */
  public static final int PhysioEmoRecogRQ_VALUE = 21;
  /**
   * <code>SpeechEmoRecogRQ = 22;</code>
   */
  public static final int SpeechEmoRecogRQ_VALUE = 22;
  /**
   * <code>FaceEmoRecogRQ = 23;</code>
   */
  public static final int FaceEmoRecogRQ_VALUE = 23;
  /**
   * <code>EmoRecogRQ = 24;</code>
   */
  public static final int EmoRecogRQ_VALUE = 24;
  /**
   * <code>EmoRecogRP = 25;</code>
   */
  public static final int EmoRecogRP_VALUE = 25;
  /**
   * <code>ErkMsgType_reserved1 = 26;</code>
   */
  public static final int ErkMsgType_reserved1_VALUE = 26;
  /**
   * <code>ErkMsgType_reserved2 = 27;</code>
   */
  public static final int ErkMsgType_reserved2_VALUE = 27;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ErkMsgType_e valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ErkMsgType_e forNumber(int value) {
    switch (value) {
      case 0: return ErkMsgType_unknown;
      case 1: return ErkServiceConnRQ;
      case 2: return ErkServiceConnRP;
      case 3: return ErkServiceDisConnRQ;
      case 4: return ErkServiceDisConnRP;
      case 5: return AddServiceProviderInfoRQ;
      case 6: return AddServiceProviderInfoRP;
      case 7: return DelServiceProviderInfoRQ;
      case 8: return DelServiceProviderInfoRP;
      case 9: return UpdServiceProviderInfoRQ;
      case 10: return UpdServiceProviderInfoRP;
      case 11: return AddUserInfoRQ;
      case 12: return AddUserInfoRp;
      case 13: return DelUserInfoRQ;
      case 14: return DelUserInfoRp;
      case 15: return UpdUserInfoRQ;
      case 16: return UpdUserInfoRP;
      case 17: return EmoRecogCreateRQ;
      case 18: return EmoRecogCreateRP;
      case 19: return EmoRecogDeleteRQ;
      case 20: return EmoRecogDeleteRP;
      case 21: return PhysioEmoRecogRQ;
      case 22: return SpeechEmoRecogRQ;
      case 23: return FaceEmoRecogRQ;
      case 24: return EmoRecogRQ;
      case 25: return EmoRecogRP;
      case 26: return ErkMsgType_reserved1;
      case 27: return ErkMsgType_reserved2;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ErkMsgType_e>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ErkMsgType_e> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ErkMsgType_e>() {
          public ErkMsgType_e findValueByNumber(int number) {
            return ErkMsgType_e.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.erksystem.protobuf.prov.ErkProvMsg.getDescriptor().getEnumTypes().get(0);
  }

  private static final ErkMsgType_e[] VALUES = values();

  public static ErkMsgType_e valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ErkMsgType_e(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ErkMsgType_e)
}

