// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkProvMsg.proto

// Protobuf Java Version: 3.25.0
package com.erksystem.protobuf.prov;

public final class ErkProvMsgOuterClass {
  private ErkProvMsgOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddServiceProviderInfoRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddServiceProviderInfoRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddServiceProviderInfoRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddServiceProviderInfoRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateServiceProviderInfoRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateServiceProviderInfoRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateServiceProviderInfoRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateServiceProviderInfoRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DelServiceProviderInfoRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DelServiceProviderInfoRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DelServiceProviderInfoRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DelServiceProviderInfoRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddUserInfoRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddUserInfoRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddUserInfoRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddUserInfoRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateUserInfoRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateUserInfoRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateUserInfoRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateUserInfoRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DelUserInfoRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DelUserInfoRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DelUserInfoRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DelUserInfoRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkProvMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkProvMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ErkProvMsg.proto\"\217\001\n\032AddServiceProvide" +
      "rInfoRQ_m\022\017\n\007OrgName\030\001 \001(\t\022\016\n\006OrgPwd\030\002 \001" +
      "(\t\022\027\n\017ServiceDuration\030\003 \001(\t\022\022\n\nUserNumbe" +
      "r\030\004 \001(\005\022#\n\013ServiceType\030\005 \001(\0162\016.ServiceTy" +
      "pe_e\"\307\001\n\032AddServiceProviderInfoRP_m\022\017\n\007O" +
      "rgName\030\001 \001(\t\022\'\n\nResultType\030\002 \001(\0162\023.OrgPr" +
      "ofileResult_e\022\r\n\005OrgId\030\003 \001(\005\022\016\n\006OrgPwd\030\004" +
      " \001(\t\022\027\n\017ServiceDuration\030\005 \001(\t\022\022\n\nUserNum" +
      "ber\030\006 \001(\005\022#\n\013ServiceType\030\007 \001(\0162\016.Service" +
      "Type_e\"\224\002\n\035UpdateServiceProviderInfoRQ_m" +
      "\022\017\n\007OrgName\030\001 \001(\t\022\022\n\nOld_OrgPwd\030\002 \001(\t\022\033\n" +
      "\023Old_ServiceDuration\030\003 \001(\t\022\026\n\016Old_UserNu" +
      "mber\030\004 \001(\005\022\'\n\017Old_ServiceType\030\005 \001(\0162\016.Se" +
      "rviceType_e\022\022\n\nNew_OrgPwd\030\006 \001(\t\022\033\n\023New_S" +
      "erviceDuration\030\007 \001(\t\022\026\n\016New_UserNumber\030\010" +
      " \001(\005\022\'\n\017New_ServiceType\030\t \001(\0162\016.ServiceT" +
      "ype_e\"\275\002\n\035UpdateServiceProviderInfoRP_m\022" +
      "\017\n\007OrgName\030\001 \001(\t\022\'\n\nResultType\030\002 \001(\0162\023.O" +
      "rgProfileResult_e\022\022\n\nOld_OrgPwd\030\003 \001(\t\022\033\n" +
      "\023Old_ServiceDuration\030\004 \001(\t\022\026\n\016Old_UserNu" +
      "mber\030\005 \001(\005\022\'\n\017Old_ServiceType\030\006 \001(\0162\016.Se" +
      "rviceType_e\022\022\n\nNew_OrgPwd\030\007 \001(\t\022\033\n\023New_S" +
      "erviceDuration\030\010 \001(\t\022\026\n\016New_UserNumber\030\t" +
      " \001(\005\022\'\n\017New_ServiceType\030\n \001(\0162\016.ServiceT" +
      "ype_e\"=\n\032DelServiceProviderInfoRQ_m\022\017\n\007O" +
      "rgName\030\001 \001(\t\022\016\n\006OrgPwd\030\002 \001(\t\"V\n\032DelServi" +
      "ceProviderInfoRP_m\022\017\n\007OrgName\030\001 \001(\t\022\'\n\nR" +
      "esultType\030\002 \001(\0162\023.OrgProfileResult_e\"\257\001\n" +
      "\017AddUserInfoRQ_m\022\017\n\007OrgName\030\001 \001(\t\022\020\n\010Use" +
      "rName\030\002 \001(\t\022\017\n\007UserPwd\030\003 \001(\t\022\027\n\017ServiceD" +
      "uration\030\004 \001(\t\022\013\n\003Age\030\005 \001(\005\022\013\n\003Sex\030\006 \001(\005\022" +
      "\020\n\010UserType\030\007 \001(\005\022#\n\013ServiceType\030\010 \001(\0162\016" +
      ".ServiceType_e\"\351\001\n\017AddUserInfoRP_m\022\017\n\007Or" +
      "gName\030\001 \001(\t\022\020\n\010UserName\030\002 \001(\t\022(\n\nResultT" +
      "ype\030\003 \001(\0162\024.UserProfileResult_e\022\016\n\006UserI" +
      "d\030\004 \001(\005\022\017\n\007UserPwd\030\005 \001(\t\022\027\n\017ServiceDurat" +
      "ion\030\006 \001(\t\022\013\n\003Age\030\007 \001(\005\022\013\n\003Sex\030\010 \001(\005\022\020\n\010U" +
      "serType\030\t \001(\005\022#\n\013ServiceType\030\n \001(\0162\016.Ser" +
      "viceType_e\"\335\002\n\022UpdateUserInfoRQ_m\022\017\n\007Org" +
      "Name\030\001 \001(\t\022\020\n\010UserName\030\002 \001(\t\022\023\n\013Old_User" +
      "Pwd\030\003 \001(\t\022\033\n\023Old_ServiceDuration\030\004 \001(\t\022\017" +
      "\n\007Old_Age\030\005 \001(\005\022\017\n\007Old_Sex\030\006 \001(\005\022\024\n\014Old_" +
      "UserType\030\007 \001(\005\022\'\n\017Old_ServiceType\030\010 \001(\0162" +
      "\016.ServiceType_e\022\023\n\013New_UserPwd\030\t \001(\t\022\033\n\023" +
      "New_ServiceDuration\030\n \001(\t\022\017\n\007New_Age\030\013 \001" +
      "(\005\022\017\n\007New_Sex\030\014 \001(\005\022\024\n\014New_UserType\030\r \001(" +
      "\005\022\'\n\017New_ServiceType\030\016 \001(\0162\016.ServiceType" +
      "_e\"\207\003\n\022UpdateUserInfoRP_m\022\017\n\007OrgName\030\001 \001" +
      "(\t\022\020\n\010UserName\030\002 \001(\t\022(\n\nResultType\030\003 \001(\016" +
      "2\024.UserProfileResult_e\022\023\n\013Old_UserPwd\030\004 " +
      "\001(\t\022\033\n\023Old_ServiceDuration\030\005 \001(\t\022\017\n\007Old_" +
      "Age\030\006 \001(\005\022\017\n\007Old_Sex\030\007 \001(\005\022\024\n\014Old_UserTy" +
      "pe\030\010 \001(\005\022\'\n\017Old_ServiceType\030\t \001(\0162\016.Serv" +
      "iceType_e\022\023\n\013New_UserPwd\030\n \001(\t\022\033\n\023New_Se" +
      "rviceDuration\030\013 \001(\t\022\017\n\007New_Age\030\014 \001(\005\022\017\n\007" +
      "New_Sex\030\r \001(\005\022\024\n\014New_UserType\030\016 \001(\005\022\'\n\017N" +
      "ew_ServiceType\030\017 \001(\0162\016.ServiceType_e\"E\n\017" +
      "DelUserInfoRQ_m\022\017\n\007OrgName\030\001 \001(\t\022\020\n\010User" +
      "Name\030\002 \001(\t\022\017\n\007UserPwd\030\003 \001(\t\"n\n\017DelUserIn" +
      "foRP_m\022\017\n\007OrgName\030\001 \001(\t\022\020\n\010UserName\030\002 \001(" +
      "\t\022(\n\nResultType\030\003 \001(\0162\024.UserProfileResul" +
      "t_e\022\016\n\006Return\030\004 \001(\t\"\263\005\n\nErkProvMsg\022?\n\030ad" +
      "dServiceProviderInfoRq\030\001 \001(\0132\033.AddServic" +
      "eProviderInfoRQ_mH\000\022?\n\030addServiceProvide" +
      "rInfoRp\030\002 \001(\0132\033.AddServiceProviderInfoRP" +
      "_mH\000\022E\n\033updateServiceProviderInfoRq\030\003 \001(" +
      "\0132\036.UpdateServiceProviderInfoRQ_mH\000\022E\n\033u" +
      "pdateServiceProviderInfoRp\030\004 \001(\0132\036.Updat" +
      "eServiceProviderInfoRP_mH\000\022?\n\030delService" +
      "ProviderInfoRq\030\005 \001(\0132\033.DelServiceProvide" +
      "rInfoRQ_mH\000\022?\n\030delServiceProviderInfoRp\030" +
      "\006 \001(\0132\033.DelServiceProviderInfoRP_mH\000\022)\n\r" +
      "addUserInfoRq\030\007 \001(\0132\020.AddUserInfoRQ_mH\000\022" +
      ")\n\raddUserInfoRp\030\010 \001(\0132\020.AddUserInfoRP_m" +
      "H\000\022/\n\020updateUserInfoRq\030\t \001(\0132\023.UpdateUse" +
      "rInfoRQ_mH\000\022/\n\020updateUserInfoRp\030\n \001(\0132\023." +
      "UpdateUserInfoRP_mH\000\022)\n\rdelUserInfoRq\030\013 " +
      "\001(\0132\020.DelUserInfoRQ_mH\000\022)\n\rdelUserInfoRp" +
      "\030\014 \001(\0132\020.DelUserInfoRP_mH\000B\005\n\003msg*\253\005\n\014Er" +
      "kMsgType_e\022\013\n\007Unknown\020\000\022\026\n\022ErkServiceCon" +
      "nRQ_e\020\001\022\026\n\022ErkServiceConnRP_e\020\002\022\031\n\025ErkSe" +
      "rviceDisConnRQ_e\020\003\022\031\n\025ErkServiceDisConnR" +
      "P_e\020\004\022\036\n\032AddServiceProviderInfoRQ_e\020\005\022\036\n" +
      "\032AddServiceProviderInfoRP_e\020\006\022\036\n\032DelServ" +
      "iceProviderInfoRQ_e\020\007\022\036\n\032DelServiceProvi" +
      "derInfoRP_e\020\010\022\036\n\032UpdServiceProviderInfoR" +
      "Q_e\020\t\022\036\n\032UpdServiceProviderInfoRP_e\020\n\022\023\n" +
      "\017AddUserInfoRQ_e\020\013\022\023\n\017AddUserInfoRP_e\020\014\022" +
      "\023\n\017DelUserInfoRQ_e\020\r\022\023\n\017DelUserInfoRP_e\020" +
      "\016\022\023\n\017UpdUserInfoRQ_e\020\017\022\023\n\017UpdUserInfoRP_" +
      "e\020\020\022\026\n\022EmoRecogCreateRQ_e\020\021\022\026\n\022EmoRecogC" +
      "reateRP_e\020\022\022\026\n\022EmoRecogDeleteRQ_e\020\023\022\026\n\022E" +
      "moRecogDeleteRP_e\020\024\022\026\n\022PhysioEmoRecogRQ_" +
      "e\020\025\022\026\n\022SpeechEmoRecogRQ_e\020\026\022\024\n\020FaceEmoRe" +
      "cogRQ_e\020\027\022\020\n\014EmoRecogRQ_e\020\030\022\020\n\014EmoRecogR" +
      "P_e\020\031\022\017\n\013reserved1_e\020\032\022\017\n\013reserved2_e\020\033*" +
      "\246\002\n\014ReturnCode_e\022\013\n\007unknown\020\000\022\006\n\002ok\020\001\022\013\n" +
      "\007nok_Org\020\002\022\014\n\010nok_User\020\003\022\017\n\013nok_MsgType\020" +
      "\004\022\022\n\016nok_EngineType\020\005\022\027\n\023nok_EngineCondi" +
      "tion\020\006\022\035\n\031nok_PhysioEngineCondition\020\007\022\035\n" +
      "\031nok_SpeechEngineCondition\020\010\022\036\n\032nok_Face" +
      "EmoEngineCondition\020\t\022\023\n\017nok_DevPlatform\020" +
      "\n\022\023\n\017nok_EmotionType\020\013\022\017\n\013nok_reason1\020\014\022" +
      "\017\n\013nok_reason2\020\r*\267\001\n\014EngineType_e\022\022\n\016Eng" +
      "ine_Unknown\020\000\022\025\n\021Engine_Physiology\020\001\022\021\n\r" +
      "Engine_Speech\020\002\022\017\n\013Engine_Face\020\003\022\026\n\022Engi" +
      "ne_EmoRecogAll\020\004\022\024\n\020Engine_Knowledge\020\005\022\024" +
      "\n\020Engine_Reserved1\020\006\022\024\n\020Engine_Reserved2" +
      "\020\007*_\n\021EngineCondition_e\022\033\n\027Engine_Unknow" +
      "nCondition\020\000\022\024\n\020Engine_Available\020\001\022\027\n\023En" +
      "gine_NotAvailable\020\002*\260\002\n\rServiceType_e\022\023\n" +
      "\017Service_Unknown\020\000\022\026\n\022Service_Physiology" +
      "\020\001\022\022\n\016Service_Speech\020\002\022\021\n\rService_Video\020" +
      "\003\022\034\n\030Service_PhysiologySPEECH\020\004\022\033\n\027Servi" +
      "ce_PhysiologyVideo\020\005\022\027\n\023Service_SpeechVi" +
      "deo\020\006\022!\n\035Service_PhysiologySpeechVideo\020\007" +
      "\022\025\n\021Service_Knowledge\020\010\022\017\n\013Service_All\020\t" +
      "\022\025\n\021Service_Reserved1\020\n\022\025\n\021Service_Reser" +
      "ved2\020\013*\357\002\n\rEmotionType_e\022\023\n\017Emotion_Unkn" +
      "own\020\000\022\023\n\017Emotion_Neutral\020\001\022\024\n\020Emotion_Po" +
      "sitive\020\002\022\024\n\020Emotion_Negative\020\003\022\022\n\016Emotio" +
      "n_Stress\020\004\022\017\n\013Emotion_Joy\020\005\022\021\n\rEmotion_H" +
      "appy\020\006\022\023\n\017Emotion_Sadness\020\007\022\021\n\rEmotion_A" +
      "nger\020\010\022\023\n\017Emotion_Arousal\020\t\022\026\n\022Emotion_R" +
      "elaxation\020\n\022\021\n\rEmotion_Peace\020\013\022\023\n\017Emotio" +
      "n_Anxiety\020\014\022\020\n\014Emotion_Fear\020\r\022\023\n\017Emotion" +
      "_Disgust\020\016\022\025\n\021Emotion_Reserved1\020\017\022\025\n\021Emo" +
      "tion_Reserved2\020\020*\262\002\n\022OrgProfileResult_e\022" +
      "\027\n\023Org_Profile_Unknown\020\000\022\022\n\016Org_Profile_" +
      "Ok\020\001\022\033\n\027Org_Profile_Nok_OrgName\020\002\022\032\n\026Org" +
      "_Profile_Nok_OrgPwd\020\003\022#\n\037Org_Profile_Nok" +
      "_ServiceDuration\020\004\022\036\n\032Org_Profile_Nok_Us" +
      "erNumber\020\005\022\037\n\033Org_Profile_Nok_ServiceTyp" +
      "e\020\006\022\026\n\022Org_Profile_Nok_DB\020\007\022\033\n\027Org_Profi" +
      "le_Nok_Reason1\020\010\022\033\n\027Org_Profile_Nok_Reas" +
      "on2\020\t*\233\003\n\023UserProfileResult_e\022$\n User_Pr" +
      "ofileUSER_PROFILE_UNKNOWN\020\000\022\023\n\017User_Prof" +
      "ile_Ok\020\001\022\034\n\030User_Profile_Nok_OrgName\020\002\022\035" +
      "\n\031User_Profile_Nok_UserName\020\003\022\034\n\030User_Pr" +
      "ofile_Nok_UserPwd\020\004\022$\n User_Profile_Nok_" +
      "ServiceDuration\020\005\022\030\n\024User_Profile_Nok_Ag" +
      "e\020\006\022\030\n\024User_Profile_Nok_Sex\020\007\022\035\n\031User_Pr" +
      "ofile_Nok_UserType\020\010\022 \n\034User_Profile_Nok" +
      "_ServiceType\020\t\022\027\n\023User_Profile_Nok_DB\020\n\022" +
      "\034\n\030User_Profile_Nok_Reason1\020\013\022\034\n\030User_Pr" +
      "ofile_Nok_Reason2\020\014B\037\n\033com.erksystem.pro" +
      "tobuf.provP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AddServiceProviderInfoRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddServiceProviderInfoRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddServiceProviderInfoRQ_m_descriptor,
        new java.lang.String[] { "OrgName", "OrgPwd", "ServiceDuration", "UserNumber", "ServiceType", });
    internal_static_AddServiceProviderInfoRP_m_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddServiceProviderInfoRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddServiceProviderInfoRP_m_descriptor,
        new java.lang.String[] { "OrgName", "ResultType", "OrgId", "OrgPwd", "ServiceDuration", "UserNumber", "ServiceType", });
    internal_static_UpdateServiceProviderInfoRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UpdateServiceProviderInfoRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateServiceProviderInfoRQ_m_descriptor,
        new java.lang.String[] { "OrgName", "OldOrgPwd", "OldServiceDuration", "OldUserNumber", "OldServiceType", "NewOrgPwd", "NewServiceDuration", "NewUserNumber", "NewServiceType", });
    internal_static_UpdateServiceProviderInfoRP_m_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UpdateServiceProviderInfoRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateServiceProviderInfoRP_m_descriptor,
        new java.lang.String[] { "OrgName", "ResultType", "OldOrgPwd", "OldServiceDuration", "OldUserNumber", "OldServiceType", "NewOrgPwd", "NewServiceDuration", "NewUserNumber", "NewServiceType", });
    internal_static_DelServiceProviderInfoRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_DelServiceProviderInfoRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DelServiceProviderInfoRQ_m_descriptor,
        new java.lang.String[] { "OrgName", "OrgPwd", });
    internal_static_DelServiceProviderInfoRP_m_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_DelServiceProviderInfoRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DelServiceProviderInfoRP_m_descriptor,
        new java.lang.String[] { "OrgName", "ResultType", });
    internal_static_AddUserInfoRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_AddUserInfoRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddUserInfoRQ_m_descriptor,
        new java.lang.String[] { "OrgName", "UserName", "UserPwd", "ServiceDuration", "Age", "Sex", "UserType", "ServiceType", });
    internal_static_AddUserInfoRP_m_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_AddUserInfoRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddUserInfoRP_m_descriptor,
        new java.lang.String[] { "OrgName", "UserName", "ResultType", "UserId", "UserPwd", "ServiceDuration", "Age", "Sex", "UserType", "ServiceType", });
    internal_static_UpdateUserInfoRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_UpdateUserInfoRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateUserInfoRQ_m_descriptor,
        new java.lang.String[] { "OrgName", "UserName", "OldUserPwd", "OldServiceDuration", "OldAge", "OldSex", "OldUserType", "OldServiceType", "NewUserPwd", "NewServiceDuration", "NewAge", "NewSex", "NewUserType", "NewServiceType", });
    internal_static_UpdateUserInfoRP_m_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_UpdateUserInfoRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateUserInfoRP_m_descriptor,
        new java.lang.String[] { "OrgName", "UserName", "ResultType", "OldUserPwd", "OldServiceDuration", "OldAge", "OldSex", "OldUserType", "OldServiceType", "NewUserPwd", "NewServiceDuration", "NewAge", "NewSex", "NewUserType", "NewServiceType", });
    internal_static_DelUserInfoRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_DelUserInfoRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DelUserInfoRQ_m_descriptor,
        new java.lang.String[] { "OrgName", "UserName", "UserPwd", });
    internal_static_DelUserInfoRP_m_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_DelUserInfoRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DelUserInfoRP_m_descriptor,
        new java.lang.String[] { "OrgName", "UserName", "ResultType", "Return", });
    internal_static_ErkProvMsg_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ErkProvMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkProvMsg_descriptor,
        new java.lang.String[] { "AddServiceProviderInfoRq", "AddServiceProviderInfoRp", "UpdateServiceProviderInfoRq", "UpdateServiceProviderInfoRp", "DelServiceProviderInfoRq", "DelServiceProviderInfoRp", "AddUserInfoRq", "AddUserInfoRp", "UpdateUserInfoRq", "UpdateUserInfoRp", "DelUserInfoRq", "DelUserInfoRp", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
