// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkProvMsg.proto

package com.erksystem.protobuf.prov;

public final class ErkProvMsgOuterClass {
  private ErkProvMsgOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddServiceProviderInfoRQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddServiceProviderInfoRQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddServiceProviderInfoRP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddServiceProviderInfoRP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateServiceProviderInfoRQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateServiceProviderInfoRQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateServiceProviderInfoRP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateServiceProviderInfoRP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DelServiceProviderInfoRQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DelServiceProviderInfoRQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DelServiceProviderInfoRP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DelServiceProviderInfoRP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddUserInfoRQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddUserInfoRQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddUserInfoRP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddUserInfoRP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateUserInfoRQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateUserInfoRQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateUserInfoRP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateUserInfoRP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DelUserInfoRQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DelUserInfoRQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DelUserInfoRP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DelUserInfoRP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkProvMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkProvMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ErkProvMsg.proto\"\215\001\n\030AddServiceProvide" +
      "rInfoRQ\022\017\n\007OrgName\030\001 \001(\t\022\016\n\006OrgPwd\030\002 \001(\t" +
      "\022\027\n\017ServiceDuration\030\003 \001(\t\022\022\n\nUserNumber\030" +
      "\004 \001(\005\022#\n\013ServiceType\030\005 \001(\0162\016.ServiceType" +
      "_e\"\305\001\n\030AddServiceProviderInfoRP\022\017\n\007OrgNa" +
      "me\030\001 \001(\t\022\'\n\nResultType\030\002 \001(\0162\023.OrgProfil" +
      "eResult_e\022\r\n\005OrgId\030\003 \001(\005\022\016\n\006OrgPwd\030\004 \001(\t" +
      "\022\027\n\017ServiceDuration\030\005 \001(\t\022\022\n\nUserNumber\030" +
      "\006 \001(\005\022#\n\013ServiceType\030\007 \001(\0162\016.ServiceType" +
      "_e\"\222\002\n\033UpdateServiceProviderInfoRQ\022\017\n\007Or" +
      "gName\030\001 \001(\t\022\022\n\nOld_OrgPwd\030\002 \001(\t\022\033\n\023Old_S" +
      "erviceDuration\030\003 \001(\t\022\026\n\016Old_UserNumber\030\004" +
      " \001(\005\022\'\n\017Old_ServiceType\030\005 \001(\0162\016.ServiceT" +
      "ype_e\022\022\n\nNew_OrgPwd\030\006 \001(\t\022\033\n\023New_Service" +
      "Duration\030\007 \001(\t\022\026\n\016New_UserNumber\030\010 \001(\005\022\'" +
      "\n\017New_ServiceType\030\t \001(\0162\016.ServiceType_e\"" +
      "\273\002\n\033UpdateServiceProviderInfoRP\022\017\n\007OrgNa" +
      "me\030\001 \001(\t\022\'\n\nResultType\030\002 \001(\0162\023.OrgProfil" +
      "eResult_e\022\022\n\nOld_OrgPwd\030\003 \001(\t\022\033\n\023Old_Ser" +
      "viceDuration\030\004 \001(\t\022\026\n\016Old_UserNumber\030\005 \001" +
      "(\005\022\'\n\017Old_ServiceType\030\006 \001(\0162\016.ServiceTyp" +
      "e_e\022\022\n\nNew_OrgPwd\030\007 \001(\t\022\033\n\023New_ServiceDu" +
      "ration\030\010 \001(\t\022\026\n\016New_UserNumber\030\t \001(\005\022\'\n\017" +
      "New_ServiceType\030\n \001(\0162\016.ServiceType_e\";\n" +
      "\030DelServiceProviderInfoRQ\022\017\n\007OrgName\030\001 \001" +
      "(\t\022\016\n\006OrgPwd\030\002 \001(\t\"T\n\030DelServiceProvider" +
      "InfoRP\022\017\n\007OrgName\030\001 \001(\t\022\'\n\nResultType\030\002 " +
      "\001(\0162\023.OrgProfileResult_e\"\255\001\n\rAddUserInfo" +
      "RQ\022\017\n\007OrgName\030\001 \001(\t\022\020\n\010UserName\030\002 \001(\t\022\017\n" +
      "\007UserPwd\030\003 \001(\t\022\027\n\017ServiceDuration\030\004 \001(\t\022" +
      "\013\n\003Age\030\005 \001(\005\022\013\n\003Sex\030\006 \001(\005\022\020\n\010UserType\030\007 " +
      "\001(\005\022#\n\013ServiceType\030\010 \001(\0162\016.ServiceType_e" +
      "\"\347\001\n\rAddUserInfoRP\022\017\n\007OrgName\030\001 \001(\t\022\020\n\010U" +
      "serName\030\002 \001(\t\022(\n\nResultType\030\003 \001(\0162\024.User" +
      "ProfileResult_e\022\016\n\006UserId\030\004 \001(\005\022\017\n\007UserP" +
      "wd\030\005 \001(\t\022\027\n\017ServiceDuration\030\006 \001(\t\022\013\n\003Age" +
      "\030\007 \001(\005\022\013\n\003Sex\030\010 \001(\005\022\020\n\010UserType\030\t \001(\005\022#\n" +
      "\013ServiceType\030\n \001(\0162\016.ServiceType_e\"\333\002\n\020U" +
      "pdateUserInfoRQ\022\017\n\007OrgName\030\001 \001(\t\022\020\n\010User" +
      "Name\030\002 \001(\t\022\023\n\013Old_UserPwd\030\003 \001(\t\022\033\n\023Old_S" +
      "erviceDuration\030\004 \001(\t\022\017\n\007Old_Age\030\005 \001(\005\022\017\n" +
      "\007Old_Sex\030\006 \001(\005\022\024\n\014Old_UserType\030\007 \001(\005\022\'\n\017" +
      "Old_ServiceType\030\010 \001(\0162\016.ServiceType_e\022\023\n" +
      "\013New_UserPwd\030\t \001(\t\022\033\n\023New_ServiceDuratio" +
      "n\030\n \001(\t\022\017\n\007New_Age\030\013 \001(\005\022\017\n\007New_Sex\030\014 \001(" +
      "\005\022\024\n\014New_UserType\030\r \001(\005\022\'\n\017New_ServiceTy" +
      "pe\030\016 \001(\0162\016.ServiceType_e\"\205\003\n\020UpdateUserI" +
      "nfoRP\022\017\n\007OrgName\030\001 \001(\t\022\020\n\010UserName\030\002 \001(\t" +
      "\022(\n\nResultType\030\003 \001(\0162\024.UserProfileResult" +
      "_e\022\023\n\013Old_UserPwd\030\004 \001(\t\022\033\n\023Old_ServiceDu" +
      "ration\030\005 \001(\t\022\017\n\007Old_Age\030\006 \001(\005\022\017\n\007Old_Sex" +
      "\030\007 \001(\005\022\024\n\014Old_UserType\030\010 \001(\005\022\'\n\017Old_Serv" +
      "iceType\030\t \001(\0162\016.ServiceType_e\022\023\n\013New_Use" +
      "rPwd\030\n \001(\t\022\033\n\023New_ServiceDuration\030\013 \001(\t\022" +
      "\017\n\007New_Age\030\014 \001(\005\022\017\n\007New_Sex\030\r \001(\005\022\024\n\014New" +
      "_UserType\030\016 \001(\005\022\'\n\017New_ServiceType\030\017 \001(\016" +
      "2\016.ServiceType_e\"C\n\rDelUserInfoRQ\022\017\n\007Org" +
      "Name\030\001 \001(\t\022\020\n\010UserName\030\002 \001(\t\022\017\n\007UserPwd\030" +
      "\003 \001(\t\"l\n\rDelUserInfoRP\022\017\n\007OrgName\030\001 \001(\t\022" +
      "\020\n\010UserName\030\002 \001(\t\022(\n\nResultType\030\003 \001(\0162\024." +
      "UserProfileResult_e\022\016\n\006Return\030\004 \001(\t\"\233\005\n\n" +
      "ErkProvMsg\022=\n\030addServiceProviderInfoRq\030\001" +
      " \001(\0132\031.AddServiceProviderInfoRQH\000\022=\n\030add" +
      "ServiceProviderInfoRp\030\002 \001(\0132\031.AddService" +
      "ProviderInfoRPH\000\022C\n\033updateServiceProvide" +
      "rInfoRq\030\003 \001(\0132\034.UpdateServiceProviderInf" +
      "oRQH\000\022C\n\033updateServiceProviderInfoRp\030\004 \001" +
      "(\0132\034.UpdateServiceProviderInfoRPH\000\022=\n\030de" +
      "lServiceProviderInfoRq\030\005 \001(\0132\031.DelServic" +
      "eProviderInfoRQH\000\022=\n\030delServiceProviderI" +
      "nfoRp\030\006 \001(\0132\031.DelServiceProviderInfoRPH\000" +
      "\022\'\n\raddUserInfoRq\030\007 \001(\0132\016.AddUserInfoRQH" +
      "\000\022\'\n\raddUserInfoRp\030\010 \001(\0132\016.AddUserInfoRP" +
      "H\000\022-\n\020updateUserInfoRq\030\t \001(\0132\021.UpdateUse" +
      "rInfoRQH\000\022-\n\020updateUserInfoRp\030\n \001(\0132\021.Up" +
      "dateUserInfoRPH\000\022\'\n\rdelUserInfoRq\030\013 \001(\0132" +
      "\016.DelUserInfoRQH\000\022\'\n\rdelUserInfoRp\030\014 \001(\013" +
      "2\016.DelUserInfoRPH\000B\005\n\003msg*\253\005\n\014ErkMsgType" +
      "_e\022\013\n\007Unknown\020\000\022\026\n\022ErkServiceConnRQ_e\020\001\022" +
      "\026\n\022ErkServiceConnRP_e\020\002\022\031\n\025ErkServiceDis" +
      "ConnRQ_e\020\003\022\031\n\025ErkServiceDisConnRP_e\020\004\022\036\n" +
      "\032AddServiceProviderInfoRQ_e\020\005\022\036\n\032AddServ" +
      "iceProviderInfoRP_e\020\006\022\036\n\032DelServiceProvi" +
      "derInfoRQ_e\020\007\022\036\n\032DelServiceProviderInfoR" +
      "P_e\020\010\022\036\n\032UpdServiceProviderInfoRQ_e\020\t\022\036\n" +
      "\032UpdServiceProviderInfoRP_e\020\n\022\023\n\017AddUser" +
      "InfoRQ_e\020\013\022\023\n\017AddUserInfoRP_e\020\014\022\023\n\017DelUs" +
      "erInfoRQ_e\020\r\022\023\n\017DelUserInfoRP_e\020\016\022\023\n\017Upd" +
      "UserInfoRQ_e\020\017\022\023\n\017UpdUserInfoRP_e\020\020\022\026\n\022E" +
      "moRecogCreateRQ_e\020\021\022\026\n\022EmoRecogCreateRP_" +
      "e\020\022\022\026\n\022EmoRecogDeleteRQ_e\020\023\022\026\n\022EmoRecogD" +
      "eleteRP_e\020\024\022\026\n\022PhysioEmoRecogRQ_e\020\025\022\026\n\022S" +
      "peechEmoRecogRQ_e\020\026\022\024\n\020FaceEmoRecogRQ_e\020" +
      "\027\022\020\n\014EmoRecogRQ_e\020\030\022\020\n\014EmoRecogRP_e\020\031\022\017\n" +
      "\013reserved1_e\020\032\022\017\n\013reserved2_e\020\033*\246\002\n\014Retu" +
      "rnCode_e\022\013\n\007unknown\020\000\022\006\n\002ok\020\001\022\013\n\007nok_Org" +
      "\020\002\022\014\n\010nok_User\020\003\022\017\n\013nok_MsgType\020\004\022\022\n\016nok" +
      "_EngineType\020\005\022\027\n\023nok_EngineCondition\020\006\022\035" +
      "\n\031nok_PhysioEngineCondition\020\007\022\035\n\031nok_Spe" +
      "echEngineCondition\020\010\022\036\n\032nok_FaceEmoEngin" +
      "eCondition\020\t\022\023\n\017nok_DevPlatform\020\n\022\023\n\017nok" +
      "_EmotionType\020\013\022\017\n\013nok_reason1\020\014\022\017\n\013nok_r" +
      "eason2\020\r*\271\001\n\014EngineType_e\022\022\n\016ENGINE_UNKN" +
      "OWN\020\000\022\025\n\021ENGINE_PHYSIOLOGY\020\001\022\021\n\rENGINE_S" +
      "PEECH\020\002\022\017\n\013ENGINE_FACE\020\003\022\030\n\024ENGINE_EMO_R" +
      "ECOG_ALL\020\004\022\024\n\020ENGINE_KNOWLEDGE\020\005\022\024\n\020ENGI" +
      "NE_RESERVED1\020\006\022\024\n\020ENGINE_RESERVED2\020\007*a\n\021" +
      "EngineCondition_e\022\034\n\030ENGINE_UNKNOWN_COND" +
      "ITION\020\000\022\024\n\020ENGINE_AVAILABLE\020\001\022\030\n\024ENGINE_" +
      "NOT_AVAILABLE\020\002*\265\002\n\rServiceType_e\022\023\n\017SER" +
      "VICE_UNKNOWN\020\000\022\026\n\022SERVICE_PHYSIOLOGY\020\001\022\022" +
      "\n\016SERVICE_SPEECH\020\002\022\021\n\rSERVICE_VIDEO\020\003\022\035\n" +
      "\031SERVICE_PHYSIOLOGY_SPEECH\020\004\022\034\n\030SERVICE_" +
      "PHYSIOLOGY_VIDEO\020\005\022\030\n\024SERVICE_SPEECH_VID" +
      "EO\020\006\022#\n\037SERVICE_PHYSIOLOGY_SPEECH_VIDEO\020" +
      "\007\022\025\n\021SERVICE_KNOWLEDGE\020\010\022\017\n\013SERVICE_ALL\020" +
      "\t\022\025\n\021SERVICE_RESERVED1\020\n\022\025\n\021SERVICE_RESE" +
      "RVED2\020\013*\322\002\n\rEmotionType_e\022\023\n\017EMOTION_UNK" +
      "NOWN\020\000\022\023\n\017EMOTION_NEUTRAL\020\001\022\024\n\020EMOTION_P" +
      "OSITIVE\020\002\022\024\n\020EMOTION_NEGATIVE\020\003\022\022\n\016EMOTI" +
      "ON_STRESS\020\004\022\017\n\013EMOTION_JOY\020\005\022\021\n\rEMOTION_" +
      "HAPPY\020\006\022\023\n\017EMOTION_SADNESS\020\007\022\021\n\rEMOTION_" +
      "ANGER\020\010\022\023\n\017EMOTION_AROUSAL\020\t\022\026\n\022EMOTION_" +
      "RELAXATION\020\n\022\021\n\rEMOTION_PEACE\020\013\022\023\n\017EMOTI" +
      "ON_ANXIETY\020\014\022\020\n\014EMOTION_FEAR\020\r\022\023\n\017EMOTIO" +
      "N_DISGUST\020\016\022\017\n\013EMOTION_ETC\020\017*\262\002\n\022OrgProf" +
      "ileResult_e\022\027\n\023ORG_PROFILE_UNKNOWN\020\000\022\022\n\016" +
      "ORG_PROFILE_OK\020\001\022\033\n\027ORG_PROFILE_NOK_OrgN" +
      "ame\020\002\022\032\n\026ORG_PROFILE_NOK_OrgPwd\020\003\022#\n\037ORG" +
      "_PROFILE_NOK_ServiceDuration\020\004\022\036\n\032ORG_PR" +
      "OFILE_NOK_UserNumber\020\005\022\037\n\033ORG_PROFILE_NO" +
      "K_ServiceType\020\006\022\026\n\022ORG_PROFILE_NOK_DB\020\007\022" +
      "\033\n\027ORG_PROFILE_NOK_REASON1\020\010\022\033\n\027ORG_PROF" +
      "ILE_NOK_REASON2\020\t*\217\003\n\023UserProfileResult_" +
      "e\022\030\n\024USER_PROFILE_UNKNOWN\020\000\022\023\n\017USER_PROF" +
      "ILE_OK\020\001\022\034\n\030USER_PROFILE_NOK_ORGNAME\020\002\022\035" +
      "\n\031USER_PROFILE_NOK_USERNAME\020\003\022\034\n\030USER_PR" +
      "OFILE_NOK_USERPWD\020\004\022$\n USER_PROFILE_NOK_" +
      "SERVICEDURATION\020\005\022\030\n\024USER_PROFILE_NOK_AG" +
      "E\020\006\022\030\n\024USER_PROFILE_NOK_SEX\020\007\022\035\n\031USER_PR" +
      "OFILE_NOK_USERTYPE\020\010\022 \n\034USER_PROFILE_NOK" +
      "_SERVICETYPE\020\t\022\027\n\023USER_PROFILE_NOK_DB\020\n\022" +
      "\034\n\030USER_PROFILE_NOK_REASON1\020\013\022\034\n\030USER_PR" +
      "OFILE_NOK_REASON2\020\014B\037\n\033com.erksystem.pro" +
      "tobuf.provP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AddServiceProviderInfoRQ_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddServiceProviderInfoRQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddServiceProviderInfoRQ_descriptor,
        new java.lang.String[] { "OrgName", "OrgPwd", "ServiceDuration", "UserNumber", "ServiceType", });
    internal_static_AddServiceProviderInfoRP_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddServiceProviderInfoRP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddServiceProviderInfoRP_descriptor,
        new java.lang.String[] { "OrgName", "ResultType", "OrgId", "OrgPwd", "ServiceDuration", "UserNumber", "ServiceType", });
    internal_static_UpdateServiceProviderInfoRQ_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UpdateServiceProviderInfoRQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateServiceProviderInfoRQ_descriptor,
        new java.lang.String[] { "OrgName", "OldOrgPwd", "OldServiceDuration", "OldUserNumber", "OldServiceType", "NewOrgPwd", "NewServiceDuration", "NewUserNumber", "NewServiceType", });
    internal_static_UpdateServiceProviderInfoRP_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UpdateServiceProviderInfoRP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateServiceProviderInfoRP_descriptor,
        new java.lang.String[] { "OrgName", "ResultType", "OldOrgPwd", "OldServiceDuration", "OldUserNumber", "OldServiceType", "NewOrgPwd", "NewServiceDuration", "NewUserNumber", "NewServiceType", });
    internal_static_DelServiceProviderInfoRQ_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_DelServiceProviderInfoRQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DelServiceProviderInfoRQ_descriptor,
        new java.lang.String[] { "OrgName", "OrgPwd", });
    internal_static_DelServiceProviderInfoRP_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_DelServiceProviderInfoRP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DelServiceProviderInfoRP_descriptor,
        new java.lang.String[] { "OrgName", "ResultType", });
    internal_static_AddUserInfoRQ_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_AddUserInfoRQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddUserInfoRQ_descriptor,
        new java.lang.String[] { "OrgName", "UserName", "UserPwd", "ServiceDuration", "Age", "Sex", "UserType", "ServiceType", });
    internal_static_AddUserInfoRP_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_AddUserInfoRP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddUserInfoRP_descriptor,
        new java.lang.String[] { "OrgName", "UserName", "ResultType", "UserId", "UserPwd", "ServiceDuration", "Age", "Sex", "UserType", "ServiceType", });
    internal_static_UpdateUserInfoRQ_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_UpdateUserInfoRQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateUserInfoRQ_descriptor,
        new java.lang.String[] { "OrgName", "UserName", "OldUserPwd", "OldServiceDuration", "OldAge", "OldSex", "OldUserType", "OldServiceType", "NewUserPwd", "NewServiceDuration", "NewAge", "NewSex", "NewUserType", "NewServiceType", });
    internal_static_UpdateUserInfoRP_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_UpdateUserInfoRP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateUserInfoRP_descriptor,
        new java.lang.String[] { "OrgName", "UserName", "ResultType", "OldUserPwd", "OldServiceDuration", "OldAge", "OldSex", "OldUserType", "OldServiceType", "NewUserPwd", "NewServiceDuration", "NewAge", "NewSex", "NewUserType", "NewServiceType", });
    internal_static_DelUserInfoRQ_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_DelUserInfoRQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DelUserInfoRQ_descriptor,
        new java.lang.String[] { "OrgName", "UserName", "UserPwd", });
    internal_static_DelUserInfoRP_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_DelUserInfoRP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DelUserInfoRP_descriptor,
        new java.lang.String[] { "OrgName", "UserName", "ResultType", "Return", });
    internal_static_ErkProvMsg_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ErkProvMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkProvMsg_descriptor,
        new java.lang.String[] { "AddServiceProviderInfoRq", "AddServiceProviderInfoRp", "UpdateServiceProviderInfoRq", "UpdateServiceProviderInfoRp", "DelServiceProviderInfoRq", "DelServiceProviderInfoRp", "AddUserInfoRq", "AddUserInfoRp", "UpdateUserInfoRq", "UpdateUserInfoRp", "DelUserInfoRq", "DelUserInfoRp", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
