use ERK_SYSTEM;

-- USER Table 이 PROVIDER Table 을 참조하므로 먼저 삭제
DROP TABLE IF EXISTS SERVICE_USER_TBL;
DROP TABLE IF EXISTS SERVICE_PROVIDER_TBL;

CREATE TABLE SERVICE_PROVIDER_TBL (
    OrgId INT PRIMARY KEY NOT NULL,
    OrgName VARCHAR(50) UNIQUE KEY NOT NULL,
    OrgPwd VARCHAR(40) NOT NULL,
    ProviderType INT NOT NULL,
    ServiceDuration VARCHAR(10) NOT NULL,
    UserNumber INT NOT NULL,
    ServiceType INT NOT NULL
);

CREATE TABLE SERVICE_USER_TBL (
    OrgId INT NOT NULL,
    UserId INT NOT NULL,
    UserName VARCHAR(50) PRIMARY KEY NOT NULL,
    UserPwd VARCHAR(40) DEFAULT NULL,
    ServiceDuration VARCHAR(10) NOT NULL,
    Age INT DEFAULT 0,
    Sex INT DEFAULT 0,
    Mbti INT DEFAULT 0,
    UserType INT DEFAULT 0,
    ServiceType INT NOT NULL DEFAULT 0,
    ServiceStatus INT NOT NULL DEFAULT 0,
    ServiceNumber INT NOT NULL DEFAULT 0,
    UNIQUE KEY SERVICE_USER_TBL.idx_UniqueKey (OrgId, UserId),
    FOREIGN KEY (OrgId) REFERENCES SERVICE_PROVIDER_TBL(OrgId)
);
