// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkApiMsg.proto

// Protobuf Java Version: 3.25.3
package com.erksystem.protobuf.api;

public interface AddUserInfoRQ_mOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddUserInfoRQ_m)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ErkMsgType_e MsgType = 1;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  int getMsgTypeValue();
  /**
   * <code>.ErkMsgType_e MsgType = 1;</code>
   * @return The msgType.
   */
  com.erksystem.protobuf.api.ErkMsgType_e getMsgType();

  /**
   * <code>.QueueInfo_s QueueInfo = 2;</code>
   * @return Whether the queueInfo field is set.
   */
  boolean hasQueueInfo();
  /**
   * <code>.QueueInfo_s QueueInfo = 2;</code>
   * @return The queueInfo.
   */
  com.erksystem.protobuf.api.QueueInfo_s getQueueInfo();
  /**
   * <code>.QueueInfo_s QueueInfo = 2;</code>
   */
  com.erksystem.protobuf.api.QueueInfo_sOrBuilder getQueueInfoOrBuilder();

  /**
   * <code>string OrgName = 3;</code>
   * @return The orgName.
   */
  java.lang.String getOrgName();
  /**
   * <code>string OrgName = 3;</code>
   * @return The bytes for orgName.
   */
  com.google.protobuf.ByteString
      getOrgNameBytes();

  /**
   * <code>string UserName = 4;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string UserName = 4;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string UserPwd = 5;</code>
   * @return The userPwd.
   */
  java.lang.String getUserPwd();
  /**
   * <code>string UserPwd = 5;</code>
   * @return The bytes for userPwd.
   */
  com.google.protobuf.ByteString
      getUserPwdBytes();

  /**
   * <code>string ServiceDuration = 6;</code>
   * @return The serviceDuration.
   */
  java.lang.String getServiceDuration();
  /**
   * <code>string ServiceDuration = 6;</code>
   * @return The bytes for serviceDuration.
   */
  com.google.protobuf.ByteString
      getServiceDurationBytes();

  /**
   * <code>int32 Age = 7;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>.SexType_e Sex = 8;</code>
   * @return The enum numeric value on the wire for sex.
   */
  int getSexValue();
  /**
   * <code>.SexType_e Sex = 8;</code>
   * @return The sex.
   */
  com.erksystem.protobuf.api.SexType_e getSex();

  /**
   * <code>.MbtiType_e MbtiType = 9;</code>
   * @return The enum numeric value on the wire for mbtiType.
   */
  int getMbtiTypeValue();
  /**
   * <code>.MbtiType_e MbtiType = 9;</code>
   * @return The mbtiType.
   */
  com.erksystem.protobuf.api.MbtiType_e getMbtiType();

  /**
   * <code>.UserType_e UserType = 10;</code>
   * @return The enum numeric value on the wire for userType.
   */
  int getUserTypeValue();
  /**
   * <code>.UserType_e UserType = 10;</code>
   * @return The userType.
   */
  com.erksystem.protobuf.api.UserType_e getUserType();

  /**
   * <code>.ServiceType_e ServiceType = 11;</code>
   * @return The enum numeric value on the wire for serviceType.
   */
  int getServiceTypeValue();
  /**
   * <code>.ServiceType_e ServiceType = 11;</code>
   * @return The serviceType.
   */
  com.erksystem.protobuf.api.ServiceType_e getServiceType();
}
