// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkApiMsg.proto

// Protobuf Java Version: 3.25.0
package com.erksystem.protobuf.api;

public interface ErkApiMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ErkApiMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ErkServiceConnRQ_m erkServiceConnRq = 1;</code>
   * @return Whether the erkServiceConnRq field is set.
   */
  boolean hasErkServiceConnRq();
  /**
   * <code>.ErkServiceConnRQ_m erkServiceConnRq = 1;</code>
   * @return The erkServiceConnRq.
   */
  com.erksystem.protobuf.api.ErkServiceConnRQ_m getErkServiceConnRq();
  /**
   * <code>.ErkServiceConnRQ_m erkServiceConnRq = 1;</code>
   */
  com.erksystem.protobuf.api.ErkServiceConnRQ_mOrBuilder getErkServiceConnRqOrBuilder();

  /**
   * <code>.ErkServiceConnRP_m erkServiceConnRp = 2;</code>
   * @return Whether the erkServiceConnRp field is set.
   */
  boolean hasErkServiceConnRp();
  /**
   * <code>.ErkServiceConnRP_m erkServiceConnRp = 2;</code>
   * @return The erkServiceConnRp.
   */
  com.erksystem.protobuf.api.ErkServiceConnRP_m getErkServiceConnRp();
  /**
   * <code>.ErkServiceConnRP_m erkServiceConnRp = 2;</code>
   */
  com.erksystem.protobuf.api.ErkServiceConnRP_mOrBuilder getErkServiceConnRpOrBuilder();

  /**
   * <code>.ErkServiceDisConnRQ_m erkServiceDisConnRq = 3;</code>
   * @return Whether the erkServiceDisConnRq field is set.
   */
  boolean hasErkServiceDisConnRq();
  /**
   * <code>.ErkServiceDisConnRQ_m erkServiceDisConnRq = 3;</code>
   * @return The erkServiceDisConnRq.
   */
  com.erksystem.protobuf.api.ErkServiceDisConnRQ_m getErkServiceDisConnRq();
  /**
   * <code>.ErkServiceDisConnRQ_m erkServiceDisConnRq = 3;</code>
   */
  com.erksystem.protobuf.api.ErkServiceDisConnRQ_mOrBuilder getErkServiceDisConnRqOrBuilder();

  /**
   * <code>.ErkServiceDisConnRP_m erkServiceDisConnRp = 4;</code>
   * @return Whether the erkServiceDisConnRp field is set.
   */
  boolean hasErkServiceDisConnRp();
  /**
   * <code>.ErkServiceDisConnRP_m erkServiceDisConnRp = 4;</code>
   * @return The erkServiceDisConnRp.
   */
  com.erksystem.protobuf.api.ErkServiceDisConnRP_m getErkServiceDisConnRp();
  /**
   * <code>.ErkServiceDisConnRP_m erkServiceDisConnRp = 4;</code>
   */
  com.erksystem.protobuf.api.ErkServiceDisConnRP_mOrBuilder getErkServiceDisConnRpOrBuilder();

  /**
   * <code>.EmoRecogCreateRQ_m emoRecogCreateRq = 5;</code>
   * @return Whether the emoRecogCreateRq field is set.
   */
  boolean hasEmoRecogCreateRq();
  /**
   * <code>.EmoRecogCreateRQ_m emoRecogCreateRq = 5;</code>
   * @return The emoRecogCreateRq.
   */
  com.erksystem.protobuf.api.EmoRecogCreateRQ_m getEmoRecogCreateRq();
  /**
   * <code>.EmoRecogCreateRQ_m emoRecogCreateRq = 5;</code>
   */
  com.erksystem.protobuf.api.EmoRecogCreateRQ_mOrBuilder getEmoRecogCreateRqOrBuilder();

  /**
   * <code>.EmoRecogCreateRP_m emoRecogCreateRp = 6;</code>
   * @return Whether the emoRecogCreateRp field is set.
   */
  boolean hasEmoRecogCreateRp();
  /**
   * <code>.EmoRecogCreateRP_m emoRecogCreateRp = 6;</code>
   * @return The emoRecogCreateRp.
   */
  com.erksystem.protobuf.api.EmoRecogCreateRP_m getEmoRecogCreateRp();
  /**
   * <code>.EmoRecogCreateRP_m emoRecogCreateRp = 6;</code>
   */
  com.erksystem.protobuf.api.EmoRecogCreateRP_mOrBuilder getEmoRecogCreateRpOrBuilder();

  /**
   * <code>.EmoRecogDeleteRQ_m emoRecogDeleteRq = 7;</code>
   * @return Whether the emoRecogDeleteRq field is set.
   */
  boolean hasEmoRecogDeleteRq();
  /**
   * <code>.EmoRecogDeleteRQ_m emoRecogDeleteRq = 7;</code>
   * @return The emoRecogDeleteRq.
   */
  com.erksystem.protobuf.api.EmoRecogDeleteRQ_m getEmoRecogDeleteRq();
  /**
   * <code>.EmoRecogDeleteRQ_m emoRecogDeleteRq = 7;</code>
   */
  com.erksystem.protobuf.api.EmoRecogDeleteRQ_mOrBuilder getEmoRecogDeleteRqOrBuilder();

  /**
   * <code>.EmoRecogDeleteRP_m emoRecogDeleteRp = 8;</code>
   * @return Whether the emoRecogDeleteRp field is set.
   */
  boolean hasEmoRecogDeleteRp();
  /**
   * <code>.EmoRecogDeleteRP_m emoRecogDeleteRp = 8;</code>
   * @return The emoRecogDeleteRp.
   */
  com.erksystem.protobuf.api.EmoRecogDeleteRP_m getEmoRecogDeleteRp();
  /**
   * <code>.EmoRecogDeleteRP_m emoRecogDeleteRp = 8;</code>
   */
  com.erksystem.protobuf.api.EmoRecogDeleteRP_mOrBuilder getEmoRecogDeleteRpOrBuilder();

  /**
   * <code>.HeartBeatRQ_m HeartBeatRQ = 9;</code>
   * @return Whether the heartBeatRQ field is set.
   */
  boolean hasHeartBeatRQ();
  /**
   * <code>.HeartBeatRQ_m HeartBeatRQ = 9;</code>
   * @return The heartBeatRQ.
   */
  com.erksystem.protobuf.api.HeartBeatRQ_m getHeartBeatRQ();
  /**
   * <code>.HeartBeatRQ_m HeartBeatRQ = 9;</code>
   */
  com.erksystem.protobuf.api.HeartBeatRQ_mOrBuilder getHeartBeatRQOrBuilder();

  /**
   * <code>.HeartBeatRP_m HeartBeatRP = 10;</code>
   * @return Whether the heartBeatRP field is set.
   */
  boolean hasHeartBeatRP();
  /**
   * <code>.HeartBeatRP_m HeartBeatRP = 10;</code>
   * @return The heartBeatRP.
   */
  com.erksystem.protobuf.api.HeartBeatRP_m getHeartBeatRP();
  /**
   * <code>.HeartBeatRP_m HeartBeatRP = 10;</code>
   */
  com.erksystem.protobuf.api.HeartBeatRP_mOrBuilder getHeartBeatRPOrBuilder();

  /**
   * <code>.EmoRecogRQ_m emoRecogRq = 11;</code>
   * @return Whether the emoRecogRq field is set.
   */
  boolean hasEmoRecogRq();
  /**
   * <code>.EmoRecogRQ_m emoRecogRq = 11;</code>
   * @return The emoRecogRq.
   */
  com.erksystem.protobuf.api.EmoRecogRQ_m getEmoRecogRq();
  /**
   * <code>.EmoRecogRQ_m emoRecogRq = 11;</code>
   */
  com.erksystem.protobuf.api.EmoRecogRQ_mOrBuilder getEmoRecogRqOrBuilder();

  /**
   * <code>.EmoRecogRP_m emoRecogRp = 12;</code>
   * @return Whether the emoRecogRp field is set.
   */
  boolean hasEmoRecogRp();
  /**
   * <code>.EmoRecogRP_m emoRecogRp = 12;</code>
   * @return The emoRecogRp.
   */
  com.erksystem.protobuf.api.EmoRecogRP_m getEmoRecogRp();
  /**
   * <code>.EmoRecogRP_m emoRecogRp = 12;</code>
   */
  com.erksystem.protobuf.api.EmoRecogRP_mOrBuilder getEmoRecogRpOrBuilder();

  /**
   * <code>.PhysioEmoRecogRQ_m physioEmoRecogRq = 13;</code>
   * @return Whether the physioEmoRecogRq field is set.
   */
  boolean hasPhysioEmoRecogRq();
  /**
   * <code>.PhysioEmoRecogRQ_m physioEmoRecogRq = 13;</code>
   * @return The physioEmoRecogRq.
   */
  com.erksystem.protobuf.api.PhysioEmoRecogRQ_m getPhysioEmoRecogRq();
  /**
   * <code>.PhysioEmoRecogRQ_m physioEmoRecogRq = 13;</code>
   */
  com.erksystem.protobuf.api.PhysioEmoRecogRQ_mOrBuilder getPhysioEmoRecogRqOrBuilder();

  /**
   * <code>.PhysioEmoRecogRP_m physioEmoRecogRp = 14;</code>
   * @return Whether the physioEmoRecogRp field is set.
   */
  boolean hasPhysioEmoRecogRp();
  /**
   * <code>.PhysioEmoRecogRP_m physioEmoRecogRp = 14;</code>
   * @return The physioEmoRecogRp.
   */
  com.erksystem.protobuf.api.PhysioEmoRecogRP_m getPhysioEmoRecogRp();
  /**
   * <code>.PhysioEmoRecogRP_m physioEmoRecogRp = 14;</code>
   */
  com.erksystem.protobuf.api.PhysioEmoRecogRP_mOrBuilder getPhysioEmoRecogRpOrBuilder();

  /**
   * <code>.SpeechEmoRecogRQ_m speechEmoRecogRq = 15;</code>
   * @return Whether the speechEmoRecogRq field is set.
   */
  boolean hasSpeechEmoRecogRq();
  /**
   * <code>.SpeechEmoRecogRQ_m speechEmoRecogRq = 15;</code>
   * @return The speechEmoRecogRq.
   */
  com.erksystem.protobuf.api.SpeechEmoRecogRQ_m getSpeechEmoRecogRq();
  /**
   * <code>.SpeechEmoRecogRQ_m speechEmoRecogRq = 15;</code>
   */
  com.erksystem.protobuf.api.SpeechEmoRecogRQ_mOrBuilder getSpeechEmoRecogRqOrBuilder();

  /**
   * <code>.SpeechEmoRecogRP_m speechEmoRecogRp = 16;</code>
   * @return Whether the speechEmoRecogRp field is set.
   */
  boolean hasSpeechEmoRecogRp();
  /**
   * <code>.SpeechEmoRecogRP_m speechEmoRecogRp = 16;</code>
   * @return The speechEmoRecogRp.
   */
  com.erksystem.protobuf.api.SpeechEmoRecogRP_m getSpeechEmoRecogRp();
  /**
   * <code>.SpeechEmoRecogRP_m speechEmoRecogRp = 16;</code>
   */
  com.erksystem.protobuf.api.SpeechEmoRecogRP_mOrBuilder getSpeechEmoRecogRpOrBuilder();

  /**
   * <code>.FaceEmoRecogRQ_m faceEmoRecogRq = 17;</code>
   * @return Whether the faceEmoRecogRq field is set.
   */
  boolean hasFaceEmoRecogRq();
  /**
   * <code>.FaceEmoRecogRQ_m faceEmoRecogRq = 17;</code>
   * @return The faceEmoRecogRq.
   */
  com.erksystem.protobuf.api.FaceEmoRecogRQ_m getFaceEmoRecogRq();
  /**
   * <code>.FaceEmoRecogRQ_m faceEmoRecogRq = 17;</code>
   */
  com.erksystem.protobuf.api.FaceEmoRecogRQ_mOrBuilder getFaceEmoRecogRqOrBuilder();

  /**
   * <code>.FaceEmoRecogRP_m faceEmoRecogRp = 18;</code>
   * @return Whether the faceEmoRecogRp field is set.
   */
  boolean hasFaceEmoRecogRp();
  /**
   * <code>.FaceEmoRecogRP_m faceEmoRecogRp = 18;</code>
   * @return The faceEmoRecogRp.
   */
  com.erksystem.protobuf.api.FaceEmoRecogRP_m getFaceEmoRecogRp();
  /**
   * <code>.FaceEmoRecogRP_m faceEmoRecogRp = 18;</code>
   */
  com.erksystem.protobuf.api.FaceEmoRecogRP_mOrBuilder getFaceEmoRecogRpOrBuilder();

  /**
   * <code>.EmoRecogNoti_m emoRecogNoti = 19;</code>
   * @return Whether the emoRecogNoti field is set.
   */
  boolean hasEmoRecogNoti();
  /**
   * <code>.EmoRecogNoti_m emoRecogNoti = 19;</code>
   * @return The emoRecogNoti.
   */
  com.erksystem.protobuf.api.EmoRecogNoti_m getEmoRecogNoti();
  /**
   * <code>.EmoRecogNoti_m emoRecogNoti = 19;</code>
   */
  com.erksystem.protobuf.api.EmoRecogNoti_mOrBuilder getEmoRecogNotiOrBuilder();

  com.erksystem.protobuf.api.ErkApiMsg.MsgCase getMsgCase();
}
