// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkApiMsg.proto

// Protobuf Java Version: 3.25.0
package com.erksystem.protobuf.api;

public final class ErkApiMsgOuterClass {
  private ErkApiMsgOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkMsgHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkMsgHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkMsgDataHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkMsgDataHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkEngineInfo_s_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkEngineInfo_s_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkServiceConnRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkServiceConnRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkServiceConnRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkServiceConnRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkServiceDisConnRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkServiceDisConnRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkServiceDisConnRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkServiceDisConnRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoRecogCreateRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoRecogCreateRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoRecogCreateRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoRecogCreateRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoRecogDeleteRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoRecogDeleteRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoRecogDeleteRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoRecogDeleteRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoRecogRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoRecogRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoRecogRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoRecogRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PhysioEmoRecogRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PhysioEmoRecogRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PhysioEmoRecogRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PhysioEmoRecogRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpeechEmoRecogRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpeechEmoRecogRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpeechEmoRecogRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpeechEmoRecogRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FaceEmoRecogRQ_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FaceEmoRecogRQ_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FaceEmoRecogRP_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FaceEmoRecogRP_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmoRecogNoti_m_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmoRecogNoti_m_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErkApiMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErkApiMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ErkApiMsg.proto\"M\n\014ErkMsgHeader\022\036\n\007Msg" +
      "Type\030\001 \001(\0162\r.ErkMsgType_e\022\r\n\005OrgId\030\002 \001(\005" +
      "\022\016\n\006UserId\030\003 \001(\005\"T\n\020ErkMsgDataHeader\022!\n\n" +
      "EngineType\030\001 \001(\0162\r.EngineType_e\022\r\n\005OrgId" +
      "\030\002 \001(\005\022\016\n\006UserId\030\003 \001(\t\"\242\001\n\017ErkEngineInfo" +
      "_s\022!\n\nEngineType\030\001 \001(\0162\r.EngineType_e\022+\n" +
      "\017EngineCondition\030\002 \001(\0162\022.EngineCondition" +
      "_e\022\016\n\006IpAddr\030\003 \001(\t\022\030\n\020ReceiveQueueName\030\004" +
      " \001(\t\022\025\n\rSendQueueName\030\005 \001(\t\"H\n\022ErkServic" +
      "eConnRQ_m\022!\n\nErkMsgHead\030\001 \001(\0132\r.ErkMsgHe" +
      "ader\022\017\n\007MsgTime\030\002 \001(\003\"\220\001\n\022ErkServiceConn" +
      "RP_m\022!\n\nErkMsgHead\030\001 \001(\0132\r.ErkMsgHeader\022" +
      "\017\n\007MsgTime\030\002 \001(\003\022!\n\nReturnCode\030\003 \001(\0162\r.R" +
      "eturnCode_e\022#\n\013ServiceType\030\004 \001(\0162\016.Servi" +
      "ceType_e\"p\n\025ErkServiceDisConnRQ_m\022!\n\nErk" +
      "MsgHead\030\001 \001(\0132\r.ErkMsgHeader\022\017\n\007MsgTime\030" +
      "\002 \001(\003\022#\n\013ServiceType\030\003 \001(\0162\016.ServiceType" +
      "_e\"n\n\025ErkServiceDisConnRP_m\022!\n\nErkMsgHea" +
      "d\030\001 \001(\0132\r.ErkMsgHeader\022\017\n\007MsgTime\030\002 \001(\003\022" +
      "!\n\nReturnCode\030\003 \001(\0162\r.ReturnCode_e\"m\n\022Em" +
      "oRecogCreateRQ_m\022!\n\nErkMsgHead\030\001 \001(\0132\r.E" +
      "rkMsgHeader\022\017\n\007MsgTime\030\002 \001(\003\022#\n\013ServiceT" +
      "ype\030\003 \001(\0162\016.ServiceType_e\"\313\002\n\022EmoRecogCr" +
      "eateRP_m\022!\n\nErkMsgHead\030\001 \001(\0132\r.ErkMsgHea" +
      "der\022\017\n\007MsgTime\030\002 \001(\003\022!\n\nReturnCode\030\003 \001(\016" +
      "2\r.ReturnCode_e\022*\n\020PhysioEngineInfo\030\004 \001(" +
      "\0132\020.ErkEngineInfo_s\022*\n\020SpeechEngineInfo\030" +
      "\005 \001(\0132\020.ErkEngineInfo_s\022(\n\016FaceEngineInf" +
      "o\030\006 \001(\0132\020.ErkEngineInfo_s\022-\n\023Reserved1En" +
      "gineInfo\030\007 \001(\0132\020.ErkEngineInfo_s\022-\n\023Rese" +
      "rved2EngineInfo\030\010 \001(\0132\020.ErkEngineInfo_s\"" +
      "\236\001\n\022EmoRecogDeleteRQ_m\022!\n\nErkMsgHead\030\001 \001" +
      "(\0132\r.ErkMsgHeader\022\017\n\007MsgTime\030\002 \001(\003\022#\n\013Se" +
      "rviceType\030\003 \001(\0162\016.ServiceType_e\022\030\n\020Recei" +
      "veQueueName\030\004 \001(\t\022\025\n\rSendQueueName\030\005 \001(\t" +
      "\"\313\002\n\022EmoRecogDeleteRP_m\022!\n\nErkMsgHead\030\001 " +
      "\001(\0132\r.ErkMsgHeader\022\017\n\007MsgTime\030\002 \001(\003\022!\n\nR" +
      "eturnCode\030\003 \001(\0162\r.ReturnCode_e\022*\n\020Physio" +
      "EngineInfo\030\004 \001(\0132\020.ErkEngineInfo_s\022*\n\020Sp" +
      "eechEngineInfo\030\005 \001(\0132\020.ErkEngineInfo_s\022(" +
      "\n\016FaceEngineInfo\030\006 \001(\0132\020.ErkEngineInfo_s" +
      "\022-\n\023Reserved1EngineInfo\030\007 \001(\0132\020.ErkEngin" +
      "eInfo_s\022-\n\023Reserved2EngineInfo\030\010 \001(\0132\020.E" +
      "rkEngineInfo_s\"2\n\rHeartBeatRQ_m\022!\n\nErkMs" +
      "gHead\030\001 \001(\0132\r.ErkMsgHeader\"B\n\rHeartBeatR" +
      "P_m\022!\n\nErkMsgHead\030\001 \001(\0132\r.ErkMsgHeader\022\016" +
      "\n\006Status\030\002 \001(\005\"}\n\014EmoRecogRQ_m\022)\n\016ErkMsg" +
      "DataHead\030\001 \001(\0132\021.ErkMsgDataHeader\022\025\n\rDat" +
      "aTimeStamp\030\002 \001(\003\022\025\n\rMsgDataLength\030\003 \001(\005\022" +
      "\024\n\014MsgDataFrame\030\004 \001(\014\"\245\001\n\014EmoRecogRP_m\022)" +
      "\n\016ErkMsgDataHead\030\001 \001(\0132\021.ErkMsgDataHeade" +
      "r\022!\n\nReturnCode\030\002 \001(\0162\r.ReturnCode_e\022\024\n\014" +
      "EmoRecogTime\030\003 \001(\003\022\037\n\007Emotion\030\004 \001(\0162\016.Em" +
      "otionType_e\022\020\n\010Accuracy\030\005 \001(\002\"\203\001\n\022Physio" +
      "EmoRecogRQ_m\022)\n\016ErkMsgDataHead\030\001 \001(\0132\021.E" +
      "rkMsgDataHeader\022\025\n\rDataTimeStamp\030\002 \001(\003\022\025" +
      "\n\rMsgDataLength\030\003 \001(\005\022\024\n\014MsgDataFrame\030\004 " +
      "\001(\014\"\253\001\n\022PhysioEmoRecogRP_m\022)\n\016ErkMsgData" +
      "Head\030\001 \001(\0132\021.ErkMsgDataHeader\022!\n\nReturnC" +
      "ode\030\002 \001(\0162\r.ReturnCode_e\022\024\n\014EmoRecogTime" +
      "\030\003 \001(\003\022\037\n\007Emotion\030\004 \001(\0162\016.EmotionType_e\022" +
      "\020\n\010Accuracy\030\005 \001(\002\"\203\001\n\022SpeechEmoRecogRQ_m" +
      "\022)\n\016ErkMsgDataHead\030\001 \001(\0132\021.ErkMsgDataHea" +
      "der\022\025\n\rDataTimeStamp\030\002 \001(\003\022\025\n\rMsgDataLen" +
      "gth\030\003 \001(\005\022\024\n\014MsgDataFrame\030\004 \001(\014\"\253\001\n\022Spee" +
      "chEmoRecogRP_m\022)\n\016ErkMsgDataHead\030\001 \001(\0132\021" +
      ".ErkMsgDataHeader\022!\n\nReturnCode\030\002 \001(\0162\r." +
      "ReturnCode_e\022\024\n\014EmoRecogTime\030\003 \001(\003\022\037\n\007Em" +
      "otion\030\004 \001(\0162\016.EmotionType_e\022\020\n\010Accuracy\030" +
      "\005 \001(\002\"\201\001\n\020FaceEmoRecogRQ_m\022)\n\016ErkMsgData" +
      "Head\030\001 \001(\0132\021.ErkMsgDataHeader\022\025\n\rDataTim" +
      "eStamp\030\002 \001(\003\022\025\n\rMsgDataLength\030\003 \001(\005\022\024\n\014M" +
      "sgDataFrame\030\004 \001(\014\"\251\001\n\020FaceEmoRecogRP_m\022)" +
      "\n\016ErkMsgDataHead\030\001 \001(\0132\021.ErkMsgDataHeade" +
      "r\022!\n\nReturnCode\030\002 \001(\0162\r.ReturnCode_e\022\024\n\014" +
      "EmoRecogTime\030\003 \001(\003\022\037\n\007Emotion\030\004 \001(\0162\016.Em" +
      "otionType_e\022\020\n\010Accuracy\030\005 \001(\002\"\204\001\n\016EmoRec" +
      "ogNoti_m\022)\n\016ErkMsgDataHead\030\001 \001(\0132\021.ErkMs" +
      "gDataHeader\022\024\n\014EmoRecogTime\030\002 \001(\003\022\037\n\007Emo" +
      "tion\030\003 \001(\0162\016.EmotionType_e\022\020\n\010Accuracy\030\004" +
      " \001(\002\"\205\007\n\tErkApiMsg\022/\n\020erkServiceConnRq\030\001" +
      " \001(\0132\023.ErkServiceConnRQ_mH\000\022/\n\020erkServic" +
      "eConnRp\030\002 \001(\0132\023.ErkServiceConnRP_mH\000\0225\n\023" +
      "erkServiceDisConnRq\030\003 \001(\0132\026.ErkServiceDi" +
      "sConnRQ_mH\000\0225\n\023erkServiceDisConnRp\030\004 \001(\013" +
      "2\026.ErkServiceDisConnRP_mH\000\022/\n\020emoRecogCr" +
      "eateRq\030\005 \001(\0132\023.EmoRecogCreateRQ_mH\000\022/\n\020e" +
      "moRecogCreateRp\030\006 \001(\0132\023.EmoRecogCreateRP" +
      "_mH\000\022/\n\020emoRecogDeleteRq\030\007 \001(\0132\023.EmoReco" +
      "gDeleteRQ_mH\000\022/\n\020emoRecogDeleteRp\030\010 \001(\0132" +
      "\023.EmoRecogDeleteRP_mH\000\022%\n\013HeartBeatRQ\030\t " +
      "\001(\0132\016.HeartBeatRQ_mH\000\022%\n\013HeartBeatRP\030\n \001" +
      "(\0132\016.HeartBeatRP_mH\000\022#\n\nemoRecogRq\030\013 \001(\013" +
      "2\r.EmoRecogRQ_mH\000\022#\n\nemoRecogRp\030\014 \001(\0132\r." +
      "EmoRecogRP_mH\000\022/\n\020physioEmoRecogRq\030\r \001(\013" +
      "2\023.PhysioEmoRecogRQ_mH\000\022/\n\020physioEmoReco" +
      "gRp\030\016 \001(\0132\023.PhysioEmoRecogRP_mH\000\022/\n\020spee" +
      "chEmoRecogRq\030\017 \001(\0132\023.SpeechEmoRecogRQ_mH" +
      "\000\022/\n\020speechEmoRecogRp\030\020 \001(\0132\023.SpeechEmoR" +
      "ecogRP_mH\000\022+\n\016faceEmoRecogRq\030\021 \001(\0132\021.Fac" +
      "eEmoRecogRQ_mH\000\022+\n\016faceEmoRecogRp\030\022 \001(\0132" +
      "\021.FaceEmoRecogRP_mH\000\022\'\n\014emoRecogNoti\030\023 \001" +
      "(\0132\017.EmoRecogNoti_mH\000B\005\n\003msg*\365\004\n\014ErkMsgT" +
      "ype_e\022\013\n\007UNKNOWN\020\000\022\024\n\020erkServiceConnRq\020\001" +
      "\022\024\n\020erkServiceConnRp\020\002\022\027\n\023erkServiceDisC" +
      "onnRq\020\003\022\027\n\023erkServiceDisConnRp\020\004\022\034\n\030addS" +
      "erviceProviderInfoRq\020\005\022\034\n\030addServiceProv" +
      "iderInfoRp\020\006\022\034\n\030delServiceProviderInfoRq" +
      "\020\007\022\034\n\030delServiceProviderInfoRp\020\010\022\034\n\030updS" +
      "erviceProviderInfoRq\020\t\022\034\n\030updServiceProv" +
      "iderInfoRp\020\n\022\021\n\raddUserInfoRq\020\013\022\021\n\raddUs" +
      "erInfoRp\020\014\022\021\n\rdelUserInfoRq\020\r\022\021\n\rdelUser" +
      "InfoRp\020\016\022\021\n\rupdUserInfoRq\020\017\022\021\n\rupdUserIn" +
      "foRp\020\020\022\024\n\020emoRecogCreateRq\020\021\022\024\n\020emoRecog" +
      "CreateRp\020\022\022\024\n\020emoRecogDeleteRq\020\023\022\024\n\020emoR" +
      "ecogDeleteRp\020\024\022\024\n\020physioEmoRecogRq\020\025\022\024\n\020" +
      "speechEmoRecogRq\020\026\022\022\n\016faceEmoRecogRq\020\027\022\016" +
      "\n\nemoRecogRq\020\030\022\016\n\nemoRecogRp\020\031\022\r\n\treserv" +
      "ed1\020\032\022\r\n\treserved2\020\033*\246\002\n\014ReturnCode_e\022\013\n" +
      "\007unknown\020\000\022\006\n\002ok\020\001\022\013\n\007nok_Org\020\002\022\014\n\010nok_U" +
      "ser\020\003\022\017\n\013nok_MsgType\020\004\022\022\n\016nok_EngineType" +
      "\020\005\022\027\n\023nok_EngineCondition\020\006\022\035\n\031nok_Physi" +
      "oEngineCondition\020\007\022\035\n\031nok_SpeechEngineCo" +
      "ndition\020\010\022\036\n\032nok_FaceEmoEngineCondition\020" +
      "\t\022\023\n\017nok_DevPlatform\020\n\022\023\n\017nok_EmotionTyp" +
      "e\020\013\022\017\n\013nok_reason1\020\014\022\017\n\013nok_reason2\020\r*\267\001" +
      "\n\014EngineType_e\022\022\n\016Engine_Unknown\020\000\022\025\n\021En" +
      "gine_Physiology\020\001\022\021\n\rEngine_Speech\020\002\022\017\n\013" +
      "Engine_Face\020\003\022\026\n\022Engine_EmoRecogAll\020\004\022\024\n" +
      "\020Engine_Knowledge\020\005\022\024\n\020Engine_Reserved1\020" +
      "\006\022\024\n\020Engine_Reserved2\020\007*_\n\021EngineConditi" +
      "on_e\022\033\n\027Engine_UnknownCondition\020\000\022\024\n\020Eng" +
      "ine_Available\020\001\022\027\n\023Engine_NotAvailable\020\002" +
      "*\260\002\n\rServiceType_e\022\023\n\017Service_Unknown\020\000\022" +
      "\026\n\022Service_Physiology\020\001\022\022\n\016Service_Speec" +
      "h\020\002\022\021\n\rService_Video\020\003\022\034\n\030Service_Physio" +
      "logySPEECH\020\004\022\033\n\027Service_PhysiologyVideo\020" +
      "\005\022\027\n\023Service_SpeechVideo\020\006\022!\n\035Service_Ph" +
      "ysiologySpeechVideo\020\007\022\025\n\021Service_Knowled" +
      "ge\020\010\022\017\n\013Service_All\020\t\022\025\n\021Service_Reserve" +
      "d1\020\n\022\025\n\021Service_Reserved2\020\013*\357\002\n\rEmotionT" +
      "ype_e\022\023\n\017Emotion_Unknown\020\000\022\023\n\017Emotion_Ne" +
      "utral\020\001\022\024\n\020Emotion_Positive\020\002\022\024\n\020Emotion" +
      "_Negative\020\003\022\022\n\016Emotion_Stress\020\004\022\017\n\013Emoti" +
      "on_Joy\020\005\022\021\n\rEmotion_Happy\020\006\022\023\n\017Emotion_S" +
      "adness\020\007\022\021\n\rEmotion_Anger\020\010\022\023\n\017Emotion_A" +
      "rousal\020\t\022\026\n\022Emotion_Relaxation\020\n\022\021\n\rEmot" +
      "ion_Peace\020\013\022\023\n\017Emotion_Anxiety\020\014\022\020\n\014Emot" +
      "ion_Fear\020\r\022\023\n\017Emotion_Disgust\020\016\022\025\n\021Emoti" +
      "on_Reserved1\020\017\022\025\n\021Emotion_Reserved2\020\020*\262\002" +
      "\n\022OrgProfileResult_e\022\027\n\023Org_Profile_Unkn" +
      "own\020\000\022\022\n\016Org_Profile_Ok\020\001\022\033\n\027Org_Profile" +
      "_Nok_OrgName\020\002\022\032\n\026Org_Profile_Nok_OrgPwd" +
      "\020\003\022#\n\037Org_Profile_Nok_ServiceDuration\020\004\022" +
      "\036\n\032Org_Profile_Nok_UserNumber\020\005\022\037\n\033Org_P" +
      "rofile_Nok_ServiceType\020\006\022\026\n\022Org_Profile_" +
      "Nok_DB\020\007\022\033\n\027Org_Profile_Nok_Reason1\020\010\022\033\n" +
      "\027Org_Profile_Nok_Reason2\020\t*\233\003\n\023UserProfi" +
      "leResult_e\022$\n User_ProfileUSER_PROFILE_U" +
      "NKNOWN\020\000\022\023\n\017User_Profile_Ok\020\001\022\034\n\030User_Pr" +
      "ofile_Nok_OrgName\020\002\022\035\n\031User_Profile_Nok_" +
      "UserName\020\003\022\034\n\030User_Profile_Nok_UserPwd\020\004" +
      "\022$\n User_Profile_Nok_ServiceDuration\020\005\022\030" +
      "\n\024User_Profile_Nok_Age\020\006\022\030\n\024User_Profile" +
      "_Nok_Sex\020\007\022\035\n\031User_Profile_Nok_UserType\020" +
      "\010\022 \n\034User_Profile_Nok_ServiceType\020\t\022\027\n\023U" +
      "ser_Profile_Nok_DB\020\n\022\034\n\030User_Profile_Nok" +
      "_Reason1\020\013\022\034\n\030User_Profile_Nok_Reason2\020\014" +
      "B\036\n\032com.erksystem.protobuf.apiP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ErkMsgHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ErkMsgHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkMsgHeader_descriptor,
        new java.lang.String[] { "MsgType", "OrgId", "UserId", });
    internal_static_ErkMsgDataHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ErkMsgDataHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkMsgDataHeader_descriptor,
        new java.lang.String[] { "EngineType", "OrgId", "UserId", });
    internal_static_ErkEngineInfo_s_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ErkEngineInfo_s_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkEngineInfo_s_descriptor,
        new java.lang.String[] { "EngineType", "EngineCondition", "IpAddr", "ReceiveQueueName", "SendQueueName", });
    internal_static_ErkServiceConnRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ErkServiceConnRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkServiceConnRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", });
    internal_static_ErkServiceConnRP_m_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ErkServiceConnRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkServiceConnRP_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ReturnCode", "ServiceType", });
    internal_static_ErkServiceDisConnRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ErkServiceDisConnRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkServiceDisConnRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ServiceType", });
    internal_static_ErkServiceDisConnRP_m_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ErkServiceDisConnRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkServiceDisConnRP_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ReturnCode", });
    internal_static_EmoRecogCreateRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_EmoRecogCreateRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoRecogCreateRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ServiceType", });
    internal_static_EmoRecogCreateRP_m_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_EmoRecogCreateRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoRecogCreateRP_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ReturnCode", "PhysioEngineInfo", "SpeechEngineInfo", "FaceEngineInfo", "Reserved1EngineInfo", "Reserved2EngineInfo", });
    internal_static_EmoRecogDeleteRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_EmoRecogDeleteRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoRecogDeleteRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ServiceType", "ReceiveQueueName", "SendQueueName", });
    internal_static_EmoRecogDeleteRP_m_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_EmoRecogDeleteRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoRecogDeleteRP_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "MsgTime", "ReturnCode", "PhysioEngineInfo", "SpeechEngineInfo", "FaceEngineInfo", "Reserved1EngineInfo", "Reserved2EngineInfo", });
    internal_static_HeartBeatRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_HeartBeatRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", });
    internal_static_HeartBeatRP_m_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_HeartBeatRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatRP_m_descriptor,
        new java.lang.String[] { "ErkMsgHead", "Status", });
    internal_static_EmoRecogRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_EmoRecogRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoRecogRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "DataTimeStamp", "MsgDataLength", "MsgDataFrame", });
    internal_static_EmoRecogRP_m_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_EmoRecogRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoRecogRP_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "ReturnCode", "EmoRecogTime", "Emotion", "Accuracy", });
    internal_static_PhysioEmoRecogRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_PhysioEmoRecogRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PhysioEmoRecogRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "DataTimeStamp", "MsgDataLength", "MsgDataFrame", });
    internal_static_PhysioEmoRecogRP_m_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_PhysioEmoRecogRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PhysioEmoRecogRP_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "ReturnCode", "EmoRecogTime", "Emotion", "Accuracy", });
    internal_static_SpeechEmoRecogRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_SpeechEmoRecogRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpeechEmoRecogRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "DataTimeStamp", "MsgDataLength", "MsgDataFrame", });
    internal_static_SpeechEmoRecogRP_m_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_SpeechEmoRecogRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpeechEmoRecogRP_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "ReturnCode", "EmoRecogTime", "Emotion", "Accuracy", });
    internal_static_FaceEmoRecogRQ_m_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_FaceEmoRecogRQ_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FaceEmoRecogRQ_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "DataTimeStamp", "MsgDataLength", "MsgDataFrame", });
    internal_static_FaceEmoRecogRP_m_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_FaceEmoRecogRP_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FaceEmoRecogRP_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "ReturnCode", "EmoRecogTime", "Emotion", "Accuracy", });
    internal_static_EmoRecogNoti_m_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_EmoRecogNoti_m_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmoRecogNoti_m_descriptor,
        new java.lang.String[] { "ErkMsgDataHead", "EmoRecogTime", "Emotion", "Accuracy", });
    internal_static_ErkApiMsg_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_ErkApiMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErkApiMsg_descriptor,
        new java.lang.String[] { "ErkServiceConnRq", "ErkServiceConnRp", "ErkServiceDisConnRq", "ErkServiceDisConnRp", "EmoRecogCreateRq", "EmoRecogCreateRp", "EmoRecogDeleteRq", "EmoRecogDeleteRp", "HeartBeatRQ", "HeartBeatRP", "EmoRecogRq", "EmoRecogRp", "PhysioEmoRecogRq", "PhysioEmoRecogRp", "SpeechEmoRecogRq", "SpeechEmoRecogRp", "FaceEmoRecogRq", "FaceEmoRecogRp", "EmoRecogNoti", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
