// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkApiMsg.proto

// Protobuf Java Version: 3.25.0
package com.erksystem.protobuf.api;

public interface ErkApiMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ErkApiMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.AddServiceProviderInfoRQ_m AddServiceProviderInfoRQ = 1;</code>
   * @return Whether the addServiceProviderInfoRQ field is set.
   */
  boolean hasAddServiceProviderInfoRQ();
  /**
   * <code>.AddServiceProviderInfoRQ_m AddServiceProviderInfoRQ = 1;</code>
   * @return The addServiceProviderInfoRQ.
   */
  com.erksystem.protobuf.api.AddServiceProviderInfoRQ_m getAddServiceProviderInfoRQ();
  /**
   * <code>.AddServiceProviderInfoRQ_m AddServiceProviderInfoRQ = 1;</code>
   */
  com.erksystem.protobuf.api.AddServiceProviderInfoRQ_mOrBuilder getAddServiceProviderInfoRQOrBuilder();

  /**
   * <code>.AddServiceProviderInfoRP_m AddServiceProviderInfoRP = 2;</code>
   * @return Whether the addServiceProviderInfoRP field is set.
   */
  boolean hasAddServiceProviderInfoRP();
  /**
   * <code>.AddServiceProviderInfoRP_m AddServiceProviderInfoRP = 2;</code>
   * @return The addServiceProviderInfoRP.
   */
  com.erksystem.protobuf.api.AddServiceProviderInfoRP_m getAddServiceProviderInfoRP();
  /**
   * <code>.AddServiceProviderInfoRP_m AddServiceProviderInfoRP = 2;</code>
   */
  com.erksystem.protobuf.api.AddServiceProviderInfoRP_mOrBuilder getAddServiceProviderInfoRPOrBuilder();

  /**
   * <code>.UpdateServiceProviderInfoRQ_m UpdateServiceProviderInfoRQ = 3;</code>
   * @return Whether the updateServiceProviderInfoRQ field is set.
   */
  boolean hasUpdateServiceProviderInfoRQ();
  /**
   * <code>.UpdateServiceProviderInfoRQ_m UpdateServiceProviderInfoRQ = 3;</code>
   * @return The updateServiceProviderInfoRQ.
   */
  com.erksystem.protobuf.api.UpdateServiceProviderInfoRQ_m getUpdateServiceProviderInfoRQ();
  /**
   * <code>.UpdateServiceProviderInfoRQ_m UpdateServiceProviderInfoRQ = 3;</code>
   */
  com.erksystem.protobuf.api.UpdateServiceProviderInfoRQ_mOrBuilder getUpdateServiceProviderInfoRQOrBuilder();

  /**
   * <code>.UpdateServiceProviderInfoRP_m UpdateServiceProviderInfoRP = 4;</code>
   * @return Whether the updateServiceProviderInfoRP field is set.
   */
  boolean hasUpdateServiceProviderInfoRP();
  /**
   * <code>.UpdateServiceProviderInfoRP_m UpdateServiceProviderInfoRP = 4;</code>
   * @return The updateServiceProviderInfoRP.
   */
  com.erksystem.protobuf.api.UpdateServiceProviderInfoRP_m getUpdateServiceProviderInfoRP();
  /**
   * <code>.UpdateServiceProviderInfoRP_m UpdateServiceProviderInfoRP = 4;</code>
   */
  com.erksystem.protobuf.api.UpdateServiceProviderInfoRP_mOrBuilder getUpdateServiceProviderInfoRPOrBuilder();

  /**
   * <code>.DelServiceProviderInfoRQ_m DelServiceProviderInfoRQ = 5;</code>
   * @return Whether the delServiceProviderInfoRQ field is set.
   */
  boolean hasDelServiceProviderInfoRQ();
  /**
   * <code>.DelServiceProviderInfoRQ_m DelServiceProviderInfoRQ = 5;</code>
   * @return The delServiceProviderInfoRQ.
   */
  com.erksystem.protobuf.api.DelServiceProviderInfoRQ_m getDelServiceProviderInfoRQ();
  /**
   * <code>.DelServiceProviderInfoRQ_m DelServiceProviderInfoRQ = 5;</code>
   */
  com.erksystem.protobuf.api.DelServiceProviderInfoRQ_mOrBuilder getDelServiceProviderInfoRQOrBuilder();

  /**
   * <code>.DelServiceProviderInfoRP_m DelServiceProviderInfoRP = 6;</code>
   * @return Whether the delServiceProviderInfoRP field is set.
   */
  boolean hasDelServiceProviderInfoRP();
  /**
   * <code>.DelServiceProviderInfoRP_m DelServiceProviderInfoRP = 6;</code>
   * @return The delServiceProviderInfoRP.
   */
  com.erksystem.protobuf.api.DelServiceProviderInfoRP_m getDelServiceProviderInfoRP();
  /**
   * <code>.DelServiceProviderInfoRP_m DelServiceProviderInfoRP = 6;</code>
   */
  com.erksystem.protobuf.api.DelServiceProviderInfoRP_mOrBuilder getDelServiceProviderInfoRPOrBuilder();

  /**
   * <code>.AddUserInfoRQ_m AddUserInfoRQ = 7;</code>
   * @return Whether the addUserInfoRQ field is set.
   */
  boolean hasAddUserInfoRQ();
  /**
   * <code>.AddUserInfoRQ_m AddUserInfoRQ = 7;</code>
   * @return The addUserInfoRQ.
   */
  com.erksystem.protobuf.api.AddUserInfoRQ_m getAddUserInfoRQ();
  /**
   * <code>.AddUserInfoRQ_m AddUserInfoRQ = 7;</code>
   */
  com.erksystem.protobuf.api.AddUserInfoRQ_mOrBuilder getAddUserInfoRQOrBuilder();

  /**
   * <code>.AddUserInfoRP_m AddUserInfoRP = 8;</code>
   * @return Whether the addUserInfoRP field is set.
   */
  boolean hasAddUserInfoRP();
  /**
   * <code>.AddUserInfoRP_m AddUserInfoRP = 8;</code>
   * @return The addUserInfoRP.
   */
  com.erksystem.protobuf.api.AddUserInfoRP_m getAddUserInfoRP();
  /**
   * <code>.AddUserInfoRP_m AddUserInfoRP = 8;</code>
   */
  com.erksystem.protobuf.api.AddUserInfoRP_mOrBuilder getAddUserInfoRPOrBuilder();

  /**
   * <code>.UpdateUserInfoRQ_m UpdateUserInfoRQ = 9;</code>
   * @return Whether the updateUserInfoRQ field is set.
   */
  boolean hasUpdateUserInfoRQ();
  /**
   * <code>.UpdateUserInfoRQ_m UpdateUserInfoRQ = 9;</code>
   * @return The updateUserInfoRQ.
   */
  com.erksystem.protobuf.api.UpdateUserInfoRQ_m getUpdateUserInfoRQ();
  /**
   * <code>.UpdateUserInfoRQ_m UpdateUserInfoRQ = 9;</code>
   */
  com.erksystem.protobuf.api.UpdateUserInfoRQ_mOrBuilder getUpdateUserInfoRQOrBuilder();

  /**
   * <code>.UpdateUserInfoRP_m UpdateUserInfoRP = 10;</code>
   * @return Whether the updateUserInfoRP field is set.
   */
  boolean hasUpdateUserInfoRP();
  /**
   * <code>.UpdateUserInfoRP_m UpdateUserInfoRP = 10;</code>
   * @return The updateUserInfoRP.
   */
  com.erksystem.protobuf.api.UpdateUserInfoRP_m getUpdateUserInfoRP();
  /**
   * <code>.UpdateUserInfoRP_m UpdateUserInfoRP = 10;</code>
   */
  com.erksystem.protobuf.api.UpdateUserInfoRP_mOrBuilder getUpdateUserInfoRPOrBuilder();

  /**
   * <code>.DelUserInfoRQ_m DelUserInfoRQ = 11;</code>
   * @return Whether the delUserInfoRQ field is set.
   */
  boolean hasDelUserInfoRQ();
  /**
   * <code>.DelUserInfoRQ_m DelUserInfoRQ = 11;</code>
   * @return The delUserInfoRQ.
   */
  com.erksystem.protobuf.api.DelUserInfoRQ_m getDelUserInfoRQ();
  /**
   * <code>.DelUserInfoRQ_m DelUserInfoRQ = 11;</code>
   */
  com.erksystem.protobuf.api.DelUserInfoRQ_mOrBuilder getDelUserInfoRQOrBuilder();

  /**
   * <code>.DelUserInfoRP_m DelUserInfoRP = 12;</code>
   * @return Whether the delUserInfoRP field is set.
   */
  boolean hasDelUserInfoRP();
  /**
   * <code>.DelUserInfoRP_m DelUserInfoRP = 12;</code>
   * @return The delUserInfoRP.
   */
  com.erksystem.protobuf.api.DelUserInfoRP_m getDelUserInfoRP();
  /**
   * <code>.DelUserInfoRP_m DelUserInfoRP = 12;</code>
   */
  com.erksystem.protobuf.api.DelUserInfoRP_mOrBuilder getDelUserInfoRPOrBuilder();

  /**
   * <code>.ErkServiceConnRQ_m ErkServiceConnRQ = 13;</code>
   * @return Whether the erkServiceConnRQ field is set.
   */
  boolean hasErkServiceConnRQ();
  /**
   * <code>.ErkServiceConnRQ_m ErkServiceConnRQ = 13;</code>
   * @return The erkServiceConnRQ.
   */
  com.erksystem.protobuf.api.ErkServiceConnRQ_m getErkServiceConnRQ();
  /**
   * <code>.ErkServiceConnRQ_m ErkServiceConnRQ = 13;</code>
   */
  com.erksystem.protobuf.api.ErkServiceConnRQ_mOrBuilder getErkServiceConnRQOrBuilder();

  /**
   * <code>.ErkServiceConnRP_m ErkServiceConnRP = 14;</code>
   * @return Whether the erkServiceConnRP field is set.
   */
  boolean hasErkServiceConnRP();
  /**
   * <code>.ErkServiceConnRP_m ErkServiceConnRP = 14;</code>
   * @return The erkServiceConnRP.
   */
  com.erksystem.protobuf.api.ErkServiceConnRP_m getErkServiceConnRP();
  /**
   * <code>.ErkServiceConnRP_m ErkServiceConnRP = 14;</code>
   */
  com.erksystem.protobuf.api.ErkServiceConnRP_mOrBuilder getErkServiceConnRPOrBuilder();

  /**
   * <code>.ErkServiceDisConnRQ_m ErkServiceDisConnRQ = 15;</code>
   * @return Whether the erkServiceDisConnRQ field is set.
   */
  boolean hasErkServiceDisConnRQ();
  /**
   * <code>.ErkServiceDisConnRQ_m ErkServiceDisConnRQ = 15;</code>
   * @return The erkServiceDisConnRQ.
   */
  com.erksystem.protobuf.api.ErkServiceDisConnRQ_m getErkServiceDisConnRQ();
  /**
   * <code>.ErkServiceDisConnRQ_m ErkServiceDisConnRQ = 15;</code>
   */
  com.erksystem.protobuf.api.ErkServiceDisConnRQ_mOrBuilder getErkServiceDisConnRQOrBuilder();

  /**
   * <code>.ErkServiceDisConnRP_m ErkServiceDisConnRP = 16;</code>
   * @return Whether the erkServiceDisConnRP field is set.
   */
  boolean hasErkServiceDisConnRP();
  /**
   * <code>.ErkServiceDisConnRP_m ErkServiceDisConnRP = 16;</code>
   * @return The erkServiceDisConnRP.
   */
  com.erksystem.protobuf.api.ErkServiceDisConnRP_m getErkServiceDisConnRP();
  /**
   * <code>.ErkServiceDisConnRP_m ErkServiceDisConnRP = 16;</code>
   */
  com.erksystem.protobuf.api.ErkServiceDisConnRP_mOrBuilder getErkServiceDisConnRPOrBuilder();

  /**
   * <code>.EmoServiceStartRQ_m EmoServiceStartRQ = 17;</code>
   * @return Whether the emoServiceStartRQ field is set.
   */
  boolean hasEmoServiceStartRQ();
  /**
   * <code>.EmoServiceStartRQ_m EmoServiceStartRQ = 17;</code>
   * @return The emoServiceStartRQ.
   */
  com.erksystem.protobuf.api.EmoServiceStartRQ_m getEmoServiceStartRQ();
  /**
   * <code>.EmoServiceStartRQ_m EmoServiceStartRQ = 17;</code>
   */
  com.erksystem.protobuf.api.EmoServiceStartRQ_mOrBuilder getEmoServiceStartRQOrBuilder();

  /**
   * <code>.EmoServiceStartRP_m EmoServiceStartRP = 18;</code>
   * @return Whether the emoServiceStartRP field is set.
   */
  boolean hasEmoServiceStartRP();
  /**
   * <code>.EmoServiceStartRP_m EmoServiceStartRP = 18;</code>
   * @return The emoServiceStartRP.
   */
  com.erksystem.protobuf.api.EmoServiceStartRP_m getEmoServiceStartRP();
  /**
   * <code>.EmoServiceStartRP_m EmoServiceStartRP = 18;</code>
   */
  com.erksystem.protobuf.api.EmoServiceStartRP_mOrBuilder getEmoServiceStartRPOrBuilder();

  /**
   * <code>.EmoServiceStopRQ_m EmoServiceStopRQ = 19;</code>
   * @return Whether the emoServiceStopRQ field is set.
   */
  boolean hasEmoServiceStopRQ();
  /**
   * <code>.EmoServiceStopRQ_m EmoServiceStopRQ = 19;</code>
   * @return The emoServiceStopRQ.
   */
  com.erksystem.protobuf.api.EmoServiceStopRQ_m getEmoServiceStopRQ();
  /**
   * <code>.EmoServiceStopRQ_m EmoServiceStopRQ = 19;</code>
   */
  com.erksystem.protobuf.api.EmoServiceStopRQ_mOrBuilder getEmoServiceStopRQOrBuilder();

  /**
   * <code>.EmoServiceStopRP_m EmoServiceStopRP = 20;</code>
   * @return Whether the emoServiceStopRP field is set.
   */
  boolean hasEmoServiceStopRP();
  /**
   * <code>.EmoServiceStopRP_m EmoServiceStopRP = 20;</code>
   * @return The emoServiceStopRP.
   */
  com.erksystem.protobuf.api.EmoServiceStopRP_m getEmoServiceStopRP();
  /**
   * <code>.EmoServiceStopRP_m EmoServiceStopRP = 20;</code>
   */
  com.erksystem.protobuf.api.EmoServiceStopRP_mOrBuilder getEmoServiceStopRPOrBuilder();

  /**
   * <code>.ErkEngineCreateRQ_m ErkEngineCreateRQ = 21;</code>
   * @return Whether the erkEngineCreateRQ field is set.
   */
  boolean hasErkEngineCreateRQ();
  /**
   * <code>.ErkEngineCreateRQ_m ErkEngineCreateRQ = 21;</code>
   * @return The erkEngineCreateRQ.
   */
  com.erksystem.protobuf.api.ErkEngineCreateRQ_m getErkEngineCreateRQ();
  /**
   * <code>.ErkEngineCreateRQ_m ErkEngineCreateRQ = 21;</code>
   */
  com.erksystem.protobuf.api.ErkEngineCreateRQ_mOrBuilder getErkEngineCreateRQOrBuilder();

  /**
   * <code>.ErkEngineCreateRP_m ErkEngineCreateRP = 22;</code>
   * @return Whether the erkEngineCreateRP field is set.
   */
  boolean hasErkEngineCreateRP();
  /**
   * <code>.ErkEngineCreateRP_m ErkEngineCreateRP = 22;</code>
   * @return The erkEngineCreateRP.
   */
  com.erksystem.protobuf.api.ErkEngineCreateRP_m getErkEngineCreateRP();
  /**
   * <code>.ErkEngineCreateRP_m ErkEngineCreateRP = 22;</code>
   */
  com.erksystem.protobuf.api.ErkEngineCreateRP_mOrBuilder getErkEngineCreateRPOrBuilder();

  /**
   * <code>.ErkEngineDeleteRQ_m ErkEngineDeleteRQ = 23;</code>
   * @return Whether the erkEngineDeleteRQ field is set.
   */
  boolean hasErkEngineDeleteRQ();
  /**
   * <code>.ErkEngineDeleteRQ_m ErkEngineDeleteRQ = 23;</code>
   * @return The erkEngineDeleteRQ.
   */
  com.erksystem.protobuf.api.ErkEngineDeleteRQ_m getErkEngineDeleteRQ();
  /**
   * <code>.ErkEngineDeleteRQ_m ErkEngineDeleteRQ = 23;</code>
   */
  com.erksystem.protobuf.api.ErkEngineDeleteRQ_mOrBuilder getErkEngineDeleteRQOrBuilder();

  /**
   * <code>.ErkEngineDeleteRP_m ErkEngineDeleteRP = 24;</code>
   * @return Whether the erkEngineDeleteRP field is set.
   */
  boolean hasErkEngineDeleteRP();
  /**
   * <code>.ErkEngineDeleteRP_m ErkEngineDeleteRP = 24;</code>
   * @return The erkEngineDeleteRP.
   */
  com.erksystem.protobuf.api.ErkEngineDeleteRP_m getErkEngineDeleteRP();
  /**
   * <code>.ErkEngineDeleteRP_m ErkEngineDeleteRP = 24;</code>
   */
  com.erksystem.protobuf.api.ErkEngineDeleteRP_mOrBuilder getErkEngineDeleteRPOrBuilder();

  /**
   * <code>.HeartBeatRQ_m HeartBeatRQ = 25;</code>
   * @return Whether the heartBeatRQ field is set.
   */
  boolean hasHeartBeatRQ();
  /**
   * <code>.HeartBeatRQ_m HeartBeatRQ = 25;</code>
   * @return The heartBeatRQ.
   */
  com.erksystem.protobuf.api.HeartBeatRQ_m getHeartBeatRQ();
  /**
   * <code>.HeartBeatRQ_m HeartBeatRQ = 25;</code>
   */
  com.erksystem.protobuf.api.HeartBeatRQ_mOrBuilder getHeartBeatRQOrBuilder();

  /**
   * <code>.HeartBeatRP_m HeartBeatRP = 26;</code>
   * @return Whether the heartBeatRP field is set.
   */
  boolean hasHeartBeatRP();
  /**
   * <code>.HeartBeatRP_m HeartBeatRP = 26;</code>
   * @return The heartBeatRP.
   */
  com.erksystem.protobuf.api.HeartBeatRP_m getHeartBeatRP();
  /**
   * <code>.HeartBeatRP_m HeartBeatRP = 26;</code>
   */
  com.erksystem.protobuf.api.HeartBeatRP_mOrBuilder getHeartBeatRPOrBuilder();

  /**
   * <code>.EmoRecogRQ_m EmoRecogRQ = 27;</code>
   * @return Whether the emoRecogRQ field is set.
   */
  boolean hasEmoRecogRQ();
  /**
   * <code>.EmoRecogRQ_m EmoRecogRQ = 27;</code>
   * @return The emoRecogRQ.
   */
  com.erksystem.protobuf.api.EmoRecogRQ_m getEmoRecogRQ();
  /**
   * <code>.EmoRecogRQ_m EmoRecogRQ = 27;</code>
   */
  com.erksystem.protobuf.api.EmoRecogRQ_mOrBuilder getEmoRecogRQOrBuilder();

  /**
   * <code>.EmoRecogRP_m EmoRecogRP = 28;</code>
   * @return Whether the emoRecogRP field is set.
   */
  boolean hasEmoRecogRP();
  /**
   * <code>.EmoRecogRP_m EmoRecogRP = 28;</code>
   * @return The emoRecogRP.
   */
  com.erksystem.protobuf.api.EmoRecogRP_m getEmoRecogRP();
  /**
   * <code>.EmoRecogRP_m EmoRecogRP = 28;</code>
   */
  com.erksystem.protobuf.api.EmoRecogRP_mOrBuilder getEmoRecogRPOrBuilder();

  /**
   * <code>.PhysioEmoRecogRQ_m PhysioEmoRecogRQ = 29;</code>
   * @return Whether the physioEmoRecogRQ field is set.
   */
  boolean hasPhysioEmoRecogRQ();
  /**
   * <code>.PhysioEmoRecogRQ_m PhysioEmoRecogRQ = 29;</code>
   * @return The physioEmoRecogRQ.
   */
  com.erksystem.protobuf.api.PhysioEmoRecogRQ_m getPhysioEmoRecogRQ();
  /**
   * <code>.PhysioEmoRecogRQ_m PhysioEmoRecogRQ = 29;</code>
   */
  com.erksystem.protobuf.api.PhysioEmoRecogRQ_mOrBuilder getPhysioEmoRecogRQOrBuilder();

  /**
   * <code>.PhysioEmoRecogRP_m PhysioEmoRecogRP = 30;</code>
   * @return Whether the physioEmoRecogRP field is set.
   */
  boolean hasPhysioEmoRecogRP();
  /**
   * <code>.PhysioEmoRecogRP_m PhysioEmoRecogRP = 30;</code>
   * @return The physioEmoRecogRP.
   */
  com.erksystem.protobuf.api.PhysioEmoRecogRP_m getPhysioEmoRecogRP();
  /**
   * <code>.PhysioEmoRecogRP_m PhysioEmoRecogRP = 30;</code>
   */
  com.erksystem.protobuf.api.PhysioEmoRecogRP_mOrBuilder getPhysioEmoRecogRPOrBuilder();

  /**
   * <code>.SpeechEmoRecogRQ_m SpeechEmoRecogRQ = 31;</code>
   * @return Whether the speechEmoRecogRQ field is set.
   */
  boolean hasSpeechEmoRecogRQ();
  /**
   * <code>.SpeechEmoRecogRQ_m SpeechEmoRecogRQ = 31;</code>
   * @return The speechEmoRecogRQ.
   */
  com.erksystem.protobuf.api.SpeechEmoRecogRQ_m getSpeechEmoRecogRQ();
  /**
   * <code>.SpeechEmoRecogRQ_m SpeechEmoRecogRQ = 31;</code>
   */
  com.erksystem.protobuf.api.SpeechEmoRecogRQ_mOrBuilder getSpeechEmoRecogRQOrBuilder();

  /**
   * <code>.SpeechEmoRecogRP_m SpeechEmoRecogRP = 32;</code>
   * @return Whether the speechEmoRecogRP field is set.
   */
  boolean hasSpeechEmoRecogRP();
  /**
   * <code>.SpeechEmoRecogRP_m SpeechEmoRecogRP = 32;</code>
   * @return The speechEmoRecogRP.
   */
  com.erksystem.protobuf.api.SpeechEmoRecogRP_m getSpeechEmoRecogRP();
  /**
   * <code>.SpeechEmoRecogRP_m SpeechEmoRecogRP = 32;</code>
   */
  com.erksystem.protobuf.api.SpeechEmoRecogRP_mOrBuilder getSpeechEmoRecogRPOrBuilder();

  /**
   * <code>.FaceEmoRecogRQ_m FaceEmoRecogRQ = 33;</code>
   * @return Whether the faceEmoRecogRQ field is set.
   */
  boolean hasFaceEmoRecogRQ();
  /**
   * <code>.FaceEmoRecogRQ_m FaceEmoRecogRQ = 33;</code>
   * @return The faceEmoRecogRQ.
   */
  com.erksystem.protobuf.api.FaceEmoRecogRQ_m getFaceEmoRecogRQ();
  /**
   * <code>.FaceEmoRecogRQ_m FaceEmoRecogRQ = 33;</code>
   */
  com.erksystem.protobuf.api.FaceEmoRecogRQ_mOrBuilder getFaceEmoRecogRQOrBuilder();

  /**
   * <code>.FaceEmoRecogRP_m FaceEmoRecogRP = 34;</code>
   * @return Whether the faceEmoRecogRP field is set.
   */
  boolean hasFaceEmoRecogRP();
  /**
   * <code>.FaceEmoRecogRP_m FaceEmoRecogRP = 34;</code>
   * @return The faceEmoRecogRP.
   */
  com.erksystem.protobuf.api.FaceEmoRecogRP_m getFaceEmoRecogRP();
  /**
   * <code>.FaceEmoRecogRP_m FaceEmoRecogRP = 34;</code>
   */
  com.erksystem.protobuf.api.FaceEmoRecogRP_mOrBuilder getFaceEmoRecogRPOrBuilder();

  /**
   * <code>.EmoRecogNoti_m EmoRecogNoti = 35;</code>
   * @return Whether the emoRecogNoti field is set.
   */
  boolean hasEmoRecogNoti();
  /**
   * <code>.EmoRecogNoti_m EmoRecogNoti = 35;</code>
   * @return The emoRecogNoti.
   */
  com.erksystem.protobuf.api.EmoRecogNoti_m getEmoRecogNoti();
  /**
   * <code>.EmoRecogNoti_m EmoRecogNoti = 35;</code>
   */
  com.erksystem.protobuf.api.EmoRecogNoti_mOrBuilder getEmoRecogNotiOrBuilder();

  com.erksystem.protobuf.api.ErkApiMsg.MsgCase getMsgCase();
}
