// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkApiMsg.proto

// Protobuf Java Version: 3.25.0
package com.erksystem.protobuf.api;

/**
 * Protobuf type {@code ErkEngineCreateRQ_m}
 */
public final class ErkEngineCreateRQ_m extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ErkEngineCreateRQ_m)
    ErkEngineCreateRQ_mOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ErkEngineCreateRQ_m.newBuilder() to construct.
  private ErkEngineCreateRQ_m(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ErkEngineCreateRQ_m() {
    serviceType_ = 0;
    physioEngineReceiveQueueName_ = "";
    physioEngineSendQueueName_ = "";
    speechEngineReceiveQueueName_ = "";
    speechEngineSendQueueName_ = "";
    faceEngineReceiveQueueName_ = "";
    faceEngineSendQueueName_ = "";
    knowledgeEngineReceiveQueueName_ = "";
    knowledgeEngineSendQueueName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ErkEngineCreateRQ_m();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_ErkEngineCreateRQ_m_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_ErkEngineCreateRQ_m_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.erksystem.protobuf.api.ErkEngineCreateRQ_m.class, com.erksystem.protobuf.api.ErkEngineCreateRQ_m.Builder.class);
  }

  private int bitField0_;
  public static final int ERKINTERMSGHEAD_FIELD_NUMBER = 1;
  private com.erksystem.protobuf.api.ErkInterMsgHead_s erkInterMsgHead_;
  /**
   * <code>.ErkInterMsgHead_s ErkInterMsgHead = 1;</code>
   * @return Whether the erkInterMsgHead field is set.
   */
  @java.lang.Override
  public boolean hasErkInterMsgHead() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.ErkInterMsgHead_s ErkInterMsgHead = 1;</code>
   * @return The erkInterMsgHead.
   */
  @java.lang.Override
  public com.erksystem.protobuf.api.ErkInterMsgHead_s getErkInterMsgHead() {
    return erkInterMsgHead_ == null ? com.erksystem.protobuf.api.ErkInterMsgHead_s.getDefaultInstance() : erkInterMsgHead_;
  }
  /**
   * <code>.ErkInterMsgHead_s ErkInterMsgHead = 1;</code>
   */
  @java.lang.Override
  public com.erksystem.protobuf.api.ErkInterMsgHead_sOrBuilder getErkInterMsgHeadOrBuilder() {
    return erkInterMsgHead_ == null ? com.erksystem.protobuf.api.ErkInterMsgHead_s.getDefaultInstance() : erkInterMsgHead_;
  }

  public static final int MSGTIME_FIELD_NUMBER = 2;
  private long msgTime_ = 0L;
  /**
   * <code>int64 MsgTime = 2;</code>
   * @return The msgTime.
   */
  @java.lang.Override
  public long getMsgTime() {
    return msgTime_;
  }

  public static final int SERVICETYPE_FIELD_NUMBER = 3;
  private int serviceType_ = 0;
  /**
   * <code>.ServiceType_e ServiceType = 3;</code>
   * @return The enum numeric value on the wire for serviceType.
   */
  @java.lang.Override public int getServiceTypeValue() {
    return serviceType_;
  }
  /**
   * <code>.ServiceType_e ServiceType = 3;</code>
   * @return The serviceType.
   */
  @java.lang.Override public com.erksystem.protobuf.api.ServiceType_e getServiceType() {
    com.erksystem.protobuf.api.ServiceType_e result = com.erksystem.protobuf.api.ServiceType_e.forNumber(serviceType_);
    return result == null ? com.erksystem.protobuf.api.ServiceType_e.UNRECOGNIZED : result;
  }

  public static final int PHYSIOENGINE_RECEIVEQUEUENAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object physioEngineReceiveQueueName_ = "";
  /**
   * <code>string PhysioEngine_ReceiveQueueName = 4;</code>
   * @return The physioEngineReceiveQueueName.
   */
  @java.lang.Override
  public java.lang.String getPhysioEngineReceiveQueueName() {
    java.lang.Object ref = physioEngineReceiveQueueName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      physioEngineReceiveQueueName_ = s;
      return s;
    }
  }
  /**
   * <code>string PhysioEngine_ReceiveQueueName = 4;</code>
   * @return The bytes for physioEngineReceiveQueueName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhysioEngineReceiveQueueNameBytes() {
    java.lang.Object ref = physioEngineReceiveQueueName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      physioEngineReceiveQueueName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHYSIOENGINE_SENDQUEUENAME_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object physioEngineSendQueueName_ = "";
  /**
   * <code>string PhysioEngine_SendQueueName = 5;</code>
   * @return The physioEngineSendQueueName.
   */
  @java.lang.Override
  public java.lang.String getPhysioEngineSendQueueName() {
    java.lang.Object ref = physioEngineSendQueueName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      physioEngineSendQueueName_ = s;
      return s;
    }
  }
  /**
   * <code>string PhysioEngine_SendQueueName = 5;</code>
   * @return The bytes for physioEngineSendQueueName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhysioEngineSendQueueNameBytes() {
    java.lang.Object ref = physioEngineSendQueueName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      physioEngineSendQueueName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPEECHENGINE_RECEIVEQUEUENAME_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object speechEngineReceiveQueueName_ = "";
  /**
   * <code>string SpeechEngine_ReceiveQueueName = 6;</code>
   * @return The speechEngineReceiveQueueName.
   */
  @java.lang.Override
  public java.lang.String getSpeechEngineReceiveQueueName() {
    java.lang.Object ref = speechEngineReceiveQueueName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      speechEngineReceiveQueueName_ = s;
      return s;
    }
  }
  /**
   * <code>string SpeechEngine_ReceiveQueueName = 6;</code>
   * @return The bytes for speechEngineReceiveQueueName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSpeechEngineReceiveQueueNameBytes() {
    java.lang.Object ref = speechEngineReceiveQueueName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      speechEngineReceiveQueueName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPEECHENGINE_SENDQUEUENAME_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object speechEngineSendQueueName_ = "";
  /**
   * <code>string SpeechEngine_SendQueueName = 7;</code>
   * @return The speechEngineSendQueueName.
   */
  @java.lang.Override
  public java.lang.String getSpeechEngineSendQueueName() {
    java.lang.Object ref = speechEngineSendQueueName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      speechEngineSendQueueName_ = s;
      return s;
    }
  }
  /**
   * <code>string SpeechEngine_SendQueueName = 7;</code>
   * @return The bytes for speechEngineSendQueueName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSpeechEngineSendQueueNameBytes() {
    java.lang.Object ref = speechEngineSendQueueName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      speechEngineSendQueueName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FACEENGINE_RECEIVEQUEUENAME_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object faceEngineReceiveQueueName_ = "";
  /**
   * <code>string FaceEngine_ReceiveQueueName = 8;</code>
   * @return The faceEngineReceiveQueueName.
   */
  @java.lang.Override
  public java.lang.String getFaceEngineReceiveQueueName() {
    java.lang.Object ref = faceEngineReceiveQueueName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      faceEngineReceiveQueueName_ = s;
      return s;
    }
  }
  /**
   * <code>string FaceEngine_ReceiveQueueName = 8;</code>
   * @return The bytes for faceEngineReceiveQueueName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFaceEngineReceiveQueueNameBytes() {
    java.lang.Object ref = faceEngineReceiveQueueName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      faceEngineReceiveQueueName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FACEENGINE_SENDQUEUENAME_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object faceEngineSendQueueName_ = "";
  /**
   * <code>string FaceEngine_SendQueueName = 9;</code>
   * @return The faceEngineSendQueueName.
   */
  @java.lang.Override
  public java.lang.String getFaceEngineSendQueueName() {
    java.lang.Object ref = faceEngineSendQueueName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      faceEngineSendQueueName_ = s;
      return s;
    }
  }
  /**
   * <code>string FaceEngine_SendQueueName = 9;</code>
   * @return The bytes for faceEngineSendQueueName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFaceEngineSendQueueNameBytes() {
    java.lang.Object ref = faceEngineSendQueueName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      faceEngineSendQueueName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KNOWLEDGEENGINE_RECEIVEQUEUENAME_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object knowledgeEngineReceiveQueueName_ = "";
  /**
   * <code>string KnowledgeEngine_ReceiveQueueName = 10;</code>
   * @return The knowledgeEngineReceiveQueueName.
   */
  @java.lang.Override
  public java.lang.String getKnowledgeEngineReceiveQueueName() {
    java.lang.Object ref = knowledgeEngineReceiveQueueName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      knowledgeEngineReceiveQueueName_ = s;
      return s;
    }
  }
  /**
   * <code>string KnowledgeEngine_ReceiveQueueName = 10;</code>
   * @return The bytes for knowledgeEngineReceiveQueueName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKnowledgeEngineReceiveQueueNameBytes() {
    java.lang.Object ref = knowledgeEngineReceiveQueueName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      knowledgeEngineReceiveQueueName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KNOWLEDGEENGINE_SENDQUEUENAME_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object knowledgeEngineSendQueueName_ = "";
  /**
   * <code>string KnowledgeEngine_SendQueueName = 11;</code>
   * @return The knowledgeEngineSendQueueName.
   */
  @java.lang.Override
  public java.lang.String getKnowledgeEngineSendQueueName() {
    java.lang.Object ref = knowledgeEngineSendQueueName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      knowledgeEngineSendQueueName_ = s;
      return s;
    }
  }
  /**
   * <code>string KnowledgeEngine_SendQueueName = 11;</code>
   * @return The bytes for knowledgeEngineSendQueueName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKnowledgeEngineSendQueueNameBytes() {
    java.lang.Object ref = knowledgeEngineSendQueueName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      knowledgeEngineSendQueueName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getErkInterMsgHead());
    }
    if (msgTime_ != 0L) {
      output.writeInt64(2, msgTime_);
    }
    if (serviceType_ != com.erksystem.protobuf.api.ServiceType_e.ServiceType_unknown.getNumber()) {
      output.writeEnum(3, serviceType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(physioEngineReceiveQueueName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, physioEngineReceiveQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(physioEngineSendQueueName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, physioEngineSendQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(speechEngineReceiveQueueName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, speechEngineReceiveQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(speechEngineSendQueueName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, speechEngineSendQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(faceEngineReceiveQueueName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, faceEngineReceiveQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(faceEngineSendQueueName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, faceEngineSendQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(knowledgeEngineReceiveQueueName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, knowledgeEngineReceiveQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(knowledgeEngineSendQueueName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, knowledgeEngineSendQueueName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getErkInterMsgHead());
    }
    if (msgTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, msgTime_);
    }
    if (serviceType_ != com.erksystem.protobuf.api.ServiceType_e.ServiceType_unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, serviceType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(physioEngineReceiveQueueName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, physioEngineReceiveQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(physioEngineSendQueueName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, physioEngineSendQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(speechEngineReceiveQueueName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, speechEngineReceiveQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(speechEngineSendQueueName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, speechEngineSendQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(faceEngineReceiveQueueName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, faceEngineReceiveQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(faceEngineSendQueueName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, faceEngineSendQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(knowledgeEngineReceiveQueueName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, knowledgeEngineReceiveQueueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(knowledgeEngineSendQueueName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, knowledgeEngineSendQueueName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.erksystem.protobuf.api.ErkEngineCreateRQ_m)) {
      return super.equals(obj);
    }
    com.erksystem.protobuf.api.ErkEngineCreateRQ_m other = (com.erksystem.protobuf.api.ErkEngineCreateRQ_m) obj;

    if (hasErkInterMsgHead() != other.hasErkInterMsgHead()) return false;
    if (hasErkInterMsgHead()) {
      if (!getErkInterMsgHead()
          .equals(other.getErkInterMsgHead())) return false;
    }
    if (getMsgTime()
        != other.getMsgTime()) return false;
    if (serviceType_ != other.serviceType_) return false;
    if (!getPhysioEngineReceiveQueueName()
        .equals(other.getPhysioEngineReceiveQueueName())) return false;
    if (!getPhysioEngineSendQueueName()
        .equals(other.getPhysioEngineSendQueueName())) return false;
    if (!getSpeechEngineReceiveQueueName()
        .equals(other.getSpeechEngineReceiveQueueName())) return false;
    if (!getSpeechEngineSendQueueName()
        .equals(other.getSpeechEngineSendQueueName())) return false;
    if (!getFaceEngineReceiveQueueName()
        .equals(other.getFaceEngineReceiveQueueName())) return false;
    if (!getFaceEngineSendQueueName()
        .equals(other.getFaceEngineSendQueueName())) return false;
    if (!getKnowledgeEngineReceiveQueueName()
        .equals(other.getKnowledgeEngineReceiveQueueName())) return false;
    if (!getKnowledgeEngineSendQueueName()
        .equals(other.getKnowledgeEngineSendQueueName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasErkInterMsgHead()) {
      hash = (37 * hash) + ERKINTERMSGHEAD_FIELD_NUMBER;
      hash = (53 * hash) + getErkInterMsgHead().hashCode();
    }
    hash = (37 * hash) + MSGTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMsgTime());
    hash = (37 * hash) + SERVICETYPE_FIELD_NUMBER;
    hash = (53 * hash) + serviceType_;
    hash = (37 * hash) + PHYSIOENGINE_RECEIVEQUEUENAME_FIELD_NUMBER;
    hash = (53 * hash) + getPhysioEngineReceiveQueueName().hashCode();
    hash = (37 * hash) + PHYSIOENGINE_SENDQUEUENAME_FIELD_NUMBER;
    hash = (53 * hash) + getPhysioEngineSendQueueName().hashCode();
    hash = (37 * hash) + SPEECHENGINE_RECEIVEQUEUENAME_FIELD_NUMBER;
    hash = (53 * hash) + getSpeechEngineReceiveQueueName().hashCode();
    hash = (37 * hash) + SPEECHENGINE_SENDQUEUENAME_FIELD_NUMBER;
    hash = (53 * hash) + getSpeechEngineSendQueueName().hashCode();
    hash = (37 * hash) + FACEENGINE_RECEIVEQUEUENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFaceEngineReceiveQueueName().hashCode();
    hash = (37 * hash) + FACEENGINE_SENDQUEUENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFaceEngineSendQueueName().hashCode();
    hash = (37 * hash) + KNOWLEDGEENGINE_RECEIVEQUEUENAME_FIELD_NUMBER;
    hash = (53 * hash) + getKnowledgeEngineReceiveQueueName().hashCode();
    hash = (37 * hash) + KNOWLEDGEENGINE_SENDQUEUENAME_FIELD_NUMBER;
    hash = (53 * hash) + getKnowledgeEngineSendQueueName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.erksystem.protobuf.api.ErkEngineCreateRQ_m parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.erksystem.protobuf.api.ErkEngineCreateRQ_m parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.erksystem.protobuf.api.ErkEngineCreateRQ_m parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.erksystem.protobuf.api.ErkEngineCreateRQ_m parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.erksystem.protobuf.api.ErkEngineCreateRQ_m parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.erksystem.protobuf.api.ErkEngineCreateRQ_m parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.erksystem.protobuf.api.ErkEngineCreateRQ_m parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.erksystem.protobuf.api.ErkEngineCreateRQ_m parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.erksystem.protobuf.api.ErkEngineCreateRQ_m parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.erksystem.protobuf.api.ErkEngineCreateRQ_m parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.erksystem.protobuf.api.ErkEngineCreateRQ_m parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.erksystem.protobuf.api.ErkEngineCreateRQ_m parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.erksystem.protobuf.api.ErkEngineCreateRQ_m prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ErkEngineCreateRQ_m}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ErkEngineCreateRQ_m)
      com.erksystem.protobuf.api.ErkEngineCreateRQ_mOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_ErkEngineCreateRQ_m_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_ErkEngineCreateRQ_m_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.erksystem.protobuf.api.ErkEngineCreateRQ_m.class, com.erksystem.protobuf.api.ErkEngineCreateRQ_m.Builder.class);
    }

    // Construct using com.erksystem.protobuf.api.ErkEngineCreateRQ_m.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getErkInterMsgHeadFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      erkInterMsgHead_ = null;
      if (erkInterMsgHeadBuilder_ != null) {
        erkInterMsgHeadBuilder_.dispose();
        erkInterMsgHeadBuilder_ = null;
      }
      msgTime_ = 0L;
      serviceType_ = 0;
      physioEngineReceiveQueueName_ = "";
      physioEngineSendQueueName_ = "";
      speechEngineReceiveQueueName_ = "";
      speechEngineSendQueueName_ = "";
      faceEngineReceiveQueueName_ = "";
      faceEngineSendQueueName_ = "";
      knowledgeEngineReceiveQueueName_ = "";
      knowledgeEngineSendQueueName_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_ErkEngineCreateRQ_m_descriptor;
    }

    @java.lang.Override
    public com.erksystem.protobuf.api.ErkEngineCreateRQ_m getDefaultInstanceForType() {
      return com.erksystem.protobuf.api.ErkEngineCreateRQ_m.getDefaultInstance();
    }

    @java.lang.Override
    public com.erksystem.protobuf.api.ErkEngineCreateRQ_m build() {
      com.erksystem.protobuf.api.ErkEngineCreateRQ_m result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.erksystem.protobuf.api.ErkEngineCreateRQ_m buildPartial() {
      com.erksystem.protobuf.api.ErkEngineCreateRQ_m result = new com.erksystem.protobuf.api.ErkEngineCreateRQ_m(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.erksystem.protobuf.api.ErkEngineCreateRQ_m result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.erkInterMsgHead_ = erkInterMsgHeadBuilder_ == null
            ? erkInterMsgHead_
            : erkInterMsgHeadBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.msgTime_ = msgTime_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.serviceType_ = serviceType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.physioEngineReceiveQueueName_ = physioEngineReceiveQueueName_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.physioEngineSendQueueName_ = physioEngineSendQueueName_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.speechEngineReceiveQueueName_ = speechEngineReceiveQueueName_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.speechEngineSendQueueName_ = speechEngineSendQueueName_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.faceEngineReceiveQueueName_ = faceEngineReceiveQueueName_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.faceEngineSendQueueName_ = faceEngineSendQueueName_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.knowledgeEngineReceiveQueueName_ = knowledgeEngineReceiveQueueName_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.knowledgeEngineSendQueueName_ = knowledgeEngineSendQueueName_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.erksystem.protobuf.api.ErkEngineCreateRQ_m) {
        return mergeFrom((com.erksystem.protobuf.api.ErkEngineCreateRQ_m)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.erksystem.protobuf.api.ErkEngineCreateRQ_m other) {
      if (other == com.erksystem.protobuf.api.ErkEngineCreateRQ_m.getDefaultInstance()) return this;
      if (other.hasErkInterMsgHead()) {
        mergeErkInterMsgHead(other.getErkInterMsgHead());
      }
      if (other.getMsgTime() != 0L) {
        setMsgTime(other.getMsgTime());
      }
      if (other.serviceType_ != 0) {
        setServiceTypeValue(other.getServiceTypeValue());
      }
      if (!other.getPhysioEngineReceiveQueueName().isEmpty()) {
        physioEngineReceiveQueueName_ = other.physioEngineReceiveQueueName_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getPhysioEngineSendQueueName().isEmpty()) {
        physioEngineSendQueueName_ = other.physioEngineSendQueueName_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getSpeechEngineReceiveQueueName().isEmpty()) {
        speechEngineReceiveQueueName_ = other.speechEngineReceiveQueueName_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getSpeechEngineSendQueueName().isEmpty()) {
        speechEngineSendQueueName_ = other.speechEngineSendQueueName_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getFaceEngineReceiveQueueName().isEmpty()) {
        faceEngineReceiveQueueName_ = other.faceEngineReceiveQueueName_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getFaceEngineSendQueueName().isEmpty()) {
        faceEngineSendQueueName_ = other.faceEngineSendQueueName_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getKnowledgeEngineReceiveQueueName().isEmpty()) {
        knowledgeEngineReceiveQueueName_ = other.knowledgeEngineReceiveQueueName_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getKnowledgeEngineSendQueueName().isEmpty()) {
        knowledgeEngineSendQueueName_ = other.knowledgeEngineSendQueueName_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getErkInterMsgHeadFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              msgTime_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              serviceType_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              physioEngineReceiveQueueName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              physioEngineSendQueueName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              speechEngineReceiveQueueName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              speechEngineSendQueueName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              faceEngineReceiveQueueName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              faceEngineSendQueueName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              knowledgeEngineReceiveQueueName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              knowledgeEngineSendQueueName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.erksystem.protobuf.api.ErkInterMsgHead_s erkInterMsgHead_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.erksystem.protobuf.api.ErkInterMsgHead_s, com.erksystem.protobuf.api.ErkInterMsgHead_s.Builder, com.erksystem.protobuf.api.ErkInterMsgHead_sOrBuilder> erkInterMsgHeadBuilder_;
    /**
     * <code>.ErkInterMsgHead_s ErkInterMsgHead = 1;</code>
     * @return Whether the erkInterMsgHead field is set.
     */
    public boolean hasErkInterMsgHead() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.ErkInterMsgHead_s ErkInterMsgHead = 1;</code>
     * @return The erkInterMsgHead.
     */
    public com.erksystem.protobuf.api.ErkInterMsgHead_s getErkInterMsgHead() {
      if (erkInterMsgHeadBuilder_ == null) {
        return erkInterMsgHead_ == null ? com.erksystem.protobuf.api.ErkInterMsgHead_s.getDefaultInstance() : erkInterMsgHead_;
      } else {
        return erkInterMsgHeadBuilder_.getMessage();
      }
    }
    /**
     * <code>.ErkInterMsgHead_s ErkInterMsgHead = 1;</code>
     */
    public Builder setErkInterMsgHead(com.erksystem.protobuf.api.ErkInterMsgHead_s value) {
      if (erkInterMsgHeadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        erkInterMsgHead_ = value;
      } else {
        erkInterMsgHeadBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ErkInterMsgHead_s ErkInterMsgHead = 1;</code>
     */
    public Builder setErkInterMsgHead(
        com.erksystem.protobuf.api.ErkInterMsgHead_s.Builder builderForValue) {
      if (erkInterMsgHeadBuilder_ == null) {
        erkInterMsgHead_ = builderForValue.build();
      } else {
        erkInterMsgHeadBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ErkInterMsgHead_s ErkInterMsgHead = 1;</code>
     */
    public Builder mergeErkInterMsgHead(com.erksystem.protobuf.api.ErkInterMsgHead_s value) {
      if (erkInterMsgHeadBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          erkInterMsgHead_ != null &&
          erkInterMsgHead_ != com.erksystem.protobuf.api.ErkInterMsgHead_s.getDefaultInstance()) {
          getErkInterMsgHeadBuilder().mergeFrom(value);
        } else {
          erkInterMsgHead_ = value;
        }
      } else {
        erkInterMsgHeadBuilder_.mergeFrom(value);
      }
      if (erkInterMsgHead_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.ErkInterMsgHead_s ErkInterMsgHead = 1;</code>
     */
    public Builder clearErkInterMsgHead() {
      bitField0_ = (bitField0_ & ~0x00000001);
      erkInterMsgHead_ = null;
      if (erkInterMsgHeadBuilder_ != null) {
        erkInterMsgHeadBuilder_.dispose();
        erkInterMsgHeadBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ErkInterMsgHead_s ErkInterMsgHead = 1;</code>
     */
    public com.erksystem.protobuf.api.ErkInterMsgHead_s.Builder getErkInterMsgHeadBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getErkInterMsgHeadFieldBuilder().getBuilder();
    }
    /**
     * <code>.ErkInterMsgHead_s ErkInterMsgHead = 1;</code>
     */
    public com.erksystem.protobuf.api.ErkInterMsgHead_sOrBuilder getErkInterMsgHeadOrBuilder() {
      if (erkInterMsgHeadBuilder_ != null) {
        return erkInterMsgHeadBuilder_.getMessageOrBuilder();
      } else {
        return erkInterMsgHead_ == null ?
            com.erksystem.protobuf.api.ErkInterMsgHead_s.getDefaultInstance() : erkInterMsgHead_;
      }
    }
    /**
     * <code>.ErkInterMsgHead_s ErkInterMsgHead = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.erksystem.protobuf.api.ErkInterMsgHead_s, com.erksystem.protobuf.api.ErkInterMsgHead_s.Builder, com.erksystem.protobuf.api.ErkInterMsgHead_sOrBuilder> 
        getErkInterMsgHeadFieldBuilder() {
      if (erkInterMsgHeadBuilder_ == null) {
        erkInterMsgHeadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.erksystem.protobuf.api.ErkInterMsgHead_s, com.erksystem.protobuf.api.ErkInterMsgHead_s.Builder, com.erksystem.protobuf.api.ErkInterMsgHead_sOrBuilder>(
                getErkInterMsgHead(),
                getParentForChildren(),
                isClean());
        erkInterMsgHead_ = null;
      }
      return erkInterMsgHeadBuilder_;
    }

    private long msgTime_ ;
    /**
     * <code>int64 MsgTime = 2;</code>
     * @return The msgTime.
     */
    @java.lang.Override
    public long getMsgTime() {
      return msgTime_;
    }
    /**
     * <code>int64 MsgTime = 2;</code>
     * @param value The msgTime to set.
     * @return This builder for chaining.
     */
    public Builder setMsgTime(long value) {

      msgTime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 MsgTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      msgTime_ = 0L;
      onChanged();
      return this;
    }

    private int serviceType_ = 0;
    /**
     * <code>.ServiceType_e ServiceType = 3;</code>
     * @return The enum numeric value on the wire for serviceType.
     */
    @java.lang.Override public int getServiceTypeValue() {
      return serviceType_;
    }
    /**
     * <code>.ServiceType_e ServiceType = 3;</code>
     * @param value The enum numeric value on the wire for serviceType to set.
     * @return This builder for chaining.
     */
    public Builder setServiceTypeValue(int value) {
      serviceType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.ServiceType_e ServiceType = 3;</code>
     * @return The serviceType.
     */
    @java.lang.Override
    public com.erksystem.protobuf.api.ServiceType_e getServiceType() {
      com.erksystem.protobuf.api.ServiceType_e result = com.erksystem.protobuf.api.ServiceType_e.forNumber(serviceType_);
      return result == null ? com.erksystem.protobuf.api.ServiceType_e.UNRECOGNIZED : result;
    }
    /**
     * <code>.ServiceType_e ServiceType = 3;</code>
     * @param value The serviceType to set.
     * @return This builder for chaining.
     */
    public Builder setServiceType(com.erksystem.protobuf.api.ServiceType_e value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      serviceType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ServiceType_e ServiceType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      serviceType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object physioEngineReceiveQueueName_ = "";
    /**
     * <code>string PhysioEngine_ReceiveQueueName = 4;</code>
     * @return The physioEngineReceiveQueueName.
     */
    public java.lang.String getPhysioEngineReceiveQueueName() {
      java.lang.Object ref = physioEngineReceiveQueueName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        physioEngineReceiveQueueName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string PhysioEngine_ReceiveQueueName = 4;</code>
     * @return The bytes for physioEngineReceiveQueueName.
     */
    public com.google.protobuf.ByteString
        getPhysioEngineReceiveQueueNameBytes() {
      java.lang.Object ref = physioEngineReceiveQueueName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        physioEngineReceiveQueueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string PhysioEngine_ReceiveQueueName = 4;</code>
     * @param value The physioEngineReceiveQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setPhysioEngineReceiveQueueName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      physioEngineReceiveQueueName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string PhysioEngine_ReceiveQueueName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhysioEngineReceiveQueueName() {
      physioEngineReceiveQueueName_ = getDefaultInstance().getPhysioEngineReceiveQueueName();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string PhysioEngine_ReceiveQueueName = 4;</code>
     * @param value The bytes for physioEngineReceiveQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setPhysioEngineReceiveQueueNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      physioEngineReceiveQueueName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object physioEngineSendQueueName_ = "";
    /**
     * <code>string PhysioEngine_SendQueueName = 5;</code>
     * @return The physioEngineSendQueueName.
     */
    public java.lang.String getPhysioEngineSendQueueName() {
      java.lang.Object ref = physioEngineSendQueueName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        physioEngineSendQueueName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string PhysioEngine_SendQueueName = 5;</code>
     * @return The bytes for physioEngineSendQueueName.
     */
    public com.google.protobuf.ByteString
        getPhysioEngineSendQueueNameBytes() {
      java.lang.Object ref = physioEngineSendQueueName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        physioEngineSendQueueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string PhysioEngine_SendQueueName = 5;</code>
     * @param value The physioEngineSendQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setPhysioEngineSendQueueName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      physioEngineSendQueueName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string PhysioEngine_SendQueueName = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhysioEngineSendQueueName() {
      physioEngineSendQueueName_ = getDefaultInstance().getPhysioEngineSendQueueName();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string PhysioEngine_SendQueueName = 5;</code>
     * @param value The bytes for physioEngineSendQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setPhysioEngineSendQueueNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      physioEngineSendQueueName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object speechEngineReceiveQueueName_ = "";
    /**
     * <code>string SpeechEngine_ReceiveQueueName = 6;</code>
     * @return The speechEngineReceiveQueueName.
     */
    public java.lang.String getSpeechEngineReceiveQueueName() {
      java.lang.Object ref = speechEngineReceiveQueueName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        speechEngineReceiveQueueName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string SpeechEngine_ReceiveQueueName = 6;</code>
     * @return The bytes for speechEngineReceiveQueueName.
     */
    public com.google.protobuf.ByteString
        getSpeechEngineReceiveQueueNameBytes() {
      java.lang.Object ref = speechEngineReceiveQueueName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        speechEngineReceiveQueueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string SpeechEngine_ReceiveQueueName = 6;</code>
     * @param value The speechEngineReceiveQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setSpeechEngineReceiveQueueName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      speechEngineReceiveQueueName_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string SpeechEngine_ReceiveQueueName = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpeechEngineReceiveQueueName() {
      speechEngineReceiveQueueName_ = getDefaultInstance().getSpeechEngineReceiveQueueName();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string SpeechEngine_ReceiveQueueName = 6;</code>
     * @param value The bytes for speechEngineReceiveQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setSpeechEngineReceiveQueueNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      speechEngineReceiveQueueName_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object speechEngineSendQueueName_ = "";
    /**
     * <code>string SpeechEngine_SendQueueName = 7;</code>
     * @return The speechEngineSendQueueName.
     */
    public java.lang.String getSpeechEngineSendQueueName() {
      java.lang.Object ref = speechEngineSendQueueName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        speechEngineSendQueueName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string SpeechEngine_SendQueueName = 7;</code>
     * @return The bytes for speechEngineSendQueueName.
     */
    public com.google.protobuf.ByteString
        getSpeechEngineSendQueueNameBytes() {
      java.lang.Object ref = speechEngineSendQueueName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        speechEngineSendQueueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string SpeechEngine_SendQueueName = 7;</code>
     * @param value The speechEngineSendQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setSpeechEngineSendQueueName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      speechEngineSendQueueName_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string SpeechEngine_SendQueueName = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpeechEngineSendQueueName() {
      speechEngineSendQueueName_ = getDefaultInstance().getSpeechEngineSendQueueName();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string SpeechEngine_SendQueueName = 7;</code>
     * @param value The bytes for speechEngineSendQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setSpeechEngineSendQueueNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      speechEngineSendQueueName_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object faceEngineReceiveQueueName_ = "";
    /**
     * <code>string FaceEngine_ReceiveQueueName = 8;</code>
     * @return The faceEngineReceiveQueueName.
     */
    public java.lang.String getFaceEngineReceiveQueueName() {
      java.lang.Object ref = faceEngineReceiveQueueName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        faceEngineReceiveQueueName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string FaceEngine_ReceiveQueueName = 8;</code>
     * @return The bytes for faceEngineReceiveQueueName.
     */
    public com.google.protobuf.ByteString
        getFaceEngineReceiveQueueNameBytes() {
      java.lang.Object ref = faceEngineReceiveQueueName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        faceEngineReceiveQueueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string FaceEngine_ReceiveQueueName = 8;</code>
     * @param value The faceEngineReceiveQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setFaceEngineReceiveQueueName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      faceEngineReceiveQueueName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string FaceEngine_ReceiveQueueName = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFaceEngineReceiveQueueName() {
      faceEngineReceiveQueueName_ = getDefaultInstance().getFaceEngineReceiveQueueName();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string FaceEngine_ReceiveQueueName = 8;</code>
     * @param value The bytes for faceEngineReceiveQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setFaceEngineReceiveQueueNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      faceEngineReceiveQueueName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object faceEngineSendQueueName_ = "";
    /**
     * <code>string FaceEngine_SendQueueName = 9;</code>
     * @return The faceEngineSendQueueName.
     */
    public java.lang.String getFaceEngineSendQueueName() {
      java.lang.Object ref = faceEngineSendQueueName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        faceEngineSendQueueName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string FaceEngine_SendQueueName = 9;</code>
     * @return The bytes for faceEngineSendQueueName.
     */
    public com.google.protobuf.ByteString
        getFaceEngineSendQueueNameBytes() {
      java.lang.Object ref = faceEngineSendQueueName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        faceEngineSendQueueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string FaceEngine_SendQueueName = 9;</code>
     * @param value The faceEngineSendQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setFaceEngineSendQueueName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      faceEngineSendQueueName_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string FaceEngine_SendQueueName = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearFaceEngineSendQueueName() {
      faceEngineSendQueueName_ = getDefaultInstance().getFaceEngineSendQueueName();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string FaceEngine_SendQueueName = 9;</code>
     * @param value The bytes for faceEngineSendQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setFaceEngineSendQueueNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      faceEngineSendQueueName_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object knowledgeEngineReceiveQueueName_ = "";
    /**
     * <code>string KnowledgeEngine_ReceiveQueueName = 10;</code>
     * @return The knowledgeEngineReceiveQueueName.
     */
    public java.lang.String getKnowledgeEngineReceiveQueueName() {
      java.lang.Object ref = knowledgeEngineReceiveQueueName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        knowledgeEngineReceiveQueueName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string KnowledgeEngine_ReceiveQueueName = 10;</code>
     * @return The bytes for knowledgeEngineReceiveQueueName.
     */
    public com.google.protobuf.ByteString
        getKnowledgeEngineReceiveQueueNameBytes() {
      java.lang.Object ref = knowledgeEngineReceiveQueueName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        knowledgeEngineReceiveQueueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string KnowledgeEngine_ReceiveQueueName = 10;</code>
     * @param value The knowledgeEngineReceiveQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setKnowledgeEngineReceiveQueueName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      knowledgeEngineReceiveQueueName_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string KnowledgeEngine_ReceiveQueueName = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearKnowledgeEngineReceiveQueueName() {
      knowledgeEngineReceiveQueueName_ = getDefaultInstance().getKnowledgeEngineReceiveQueueName();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string KnowledgeEngine_ReceiveQueueName = 10;</code>
     * @param value The bytes for knowledgeEngineReceiveQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setKnowledgeEngineReceiveQueueNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      knowledgeEngineReceiveQueueName_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object knowledgeEngineSendQueueName_ = "";
    /**
     * <code>string KnowledgeEngine_SendQueueName = 11;</code>
     * @return The knowledgeEngineSendQueueName.
     */
    public java.lang.String getKnowledgeEngineSendQueueName() {
      java.lang.Object ref = knowledgeEngineSendQueueName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        knowledgeEngineSendQueueName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string KnowledgeEngine_SendQueueName = 11;</code>
     * @return The bytes for knowledgeEngineSendQueueName.
     */
    public com.google.protobuf.ByteString
        getKnowledgeEngineSendQueueNameBytes() {
      java.lang.Object ref = knowledgeEngineSendQueueName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        knowledgeEngineSendQueueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string KnowledgeEngine_SendQueueName = 11;</code>
     * @param value The knowledgeEngineSendQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setKnowledgeEngineSendQueueName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      knowledgeEngineSendQueueName_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string KnowledgeEngine_SendQueueName = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearKnowledgeEngineSendQueueName() {
      knowledgeEngineSendQueueName_ = getDefaultInstance().getKnowledgeEngineSendQueueName();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string KnowledgeEngine_SendQueueName = 11;</code>
     * @param value The bytes for knowledgeEngineSendQueueName to set.
     * @return This builder for chaining.
     */
    public Builder setKnowledgeEngineSendQueueNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      knowledgeEngineSendQueueName_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ErkEngineCreateRQ_m)
  }

  // @@protoc_insertion_point(class_scope:ErkEngineCreateRQ_m)
  private static final com.erksystem.protobuf.api.ErkEngineCreateRQ_m DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.erksystem.protobuf.api.ErkEngineCreateRQ_m();
  }

  public static com.erksystem.protobuf.api.ErkEngineCreateRQ_m getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ErkEngineCreateRQ_m>
      PARSER = new com.google.protobuf.AbstractParser<ErkEngineCreateRQ_m>() {
    @java.lang.Override
    public ErkEngineCreateRQ_m parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ErkEngineCreateRQ_m> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ErkEngineCreateRQ_m> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.erksystem.protobuf.api.ErkEngineCreateRQ_m getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

