// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkApiMsg.proto

// Protobuf Java Version: 3.25.0
package com.erksystem.protobuf.api;

/**
 * Protobuf enum {@code ErkInterMsgType_e}
 */
public enum ErkInterMsgType_e
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ErkInterMsgType_unknown = 0;</code>
   */
  ErkInterMsgType_unknown(0),
  /**
   * <code>ErkEngineCreateRQ = 1;</code>
   */
  ErkEngineCreateRQ(1),
  /**
   * <code>ErkEngineCreateRP = 2;</code>
   */
  ErkEngineCreateRP(2),
  /**
   * <code>ErkEngineDeleteRQ = 3;</code>
   */
  ErkEngineDeleteRQ(3),
  /**
   * <code>ErkEngineDeleteRP = 4;</code>
   */
  ErkEngineDeleteRP(4),
  /**
   * <code>ErkInterMsgType_reserved1 = 5;</code>
   */
  ErkInterMsgType_reserved1(5),
  /**
   * <code>ErkInterMsgType_reserved2 = 6;</code>
   */
  ErkInterMsgType_reserved2(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ErkInterMsgType_unknown = 0;</code>
   */
  public static final int ErkInterMsgType_unknown_VALUE = 0;
  /**
   * <code>ErkEngineCreateRQ = 1;</code>
   */
  public static final int ErkEngineCreateRQ_VALUE = 1;
  /**
   * <code>ErkEngineCreateRP = 2;</code>
   */
  public static final int ErkEngineCreateRP_VALUE = 2;
  /**
   * <code>ErkEngineDeleteRQ = 3;</code>
   */
  public static final int ErkEngineDeleteRQ_VALUE = 3;
  /**
   * <code>ErkEngineDeleteRP = 4;</code>
   */
  public static final int ErkEngineDeleteRP_VALUE = 4;
  /**
   * <code>ErkInterMsgType_reserved1 = 5;</code>
   */
  public static final int ErkInterMsgType_reserved1_VALUE = 5;
  /**
   * <code>ErkInterMsgType_reserved2 = 6;</code>
   */
  public static final int ErkInterMsgType_reserved2_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ErkInterMsgType_e valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ErkInterMsgType_e forNumber(int value) {
    switch (value) {
      case 0: return ErkInterMsgType_unknown;
      case 1: return ErkEngineCreateRQ;
      case 2: return ErkEngineCreateRP;
      case 3: return ErkEngineDeleteRQ;
      case 4: return ErkEngineDeleteRP;
      case 5: return ErkInterMsgType_reserved1;
      case 6: return ErkInterMsgType_reserved2;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ErkInterMsgType_e>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ErkInterMsgType_e> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ErkInterMsgType_e>() {
          public ErkInterMsgType_e findValueByNumber(int number) {
            return ErkInterMsgType_e.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.erksystem.protobuf.api.ErkApiMsgOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final ErkInterMsgType_e[] VALUES = values();

  public static ErkInterMsgType_e valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ErkInterMsgType_e(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ErkInterMsgType_e)
}

