// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkApiMsg.proto

// Protobuf Java Version: 3.25.0
package com.erksystem.protobuf.api;

public interface ErkMsgDataHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ErkMsgDataHeader)
    com.google.protobuf.MessageOrBuilder {
}
