// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkApiMsg.proto

// Protobuf Java Version: 3.25.0
package com.erksystem.protobuf.api;

public interface ErkServiceDisConnRQ_mOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ErkServiceDisConnRQ_m)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ErkMsgHead_s ErkMsgHead = 1;</code>
   * @return Whether the erkMsgHead field is set.
   */
  boolean hasErkMsgHead();
  /**
   * <code>.ErkMsgHead_s ErkMsgHead = 1;</code>
   * @return The erkMsgHead.
   */
  com.erksystem.protobuf.api.ErkMsgHead_s getErkMsgHead();
  /**
   * <code>.ErkMsgHead_s ErkMsgHead = 1;</code>
   */
  com.erksystem.protobuf.api.ErkMsgHead_sOrBuilder getErkMsgHeadOrBuilder();

  /**
   * <code>int64 MsgTime = 2;</code>
   * @return The msgTime.
   */
  long getMsgTime();

  /**
   * <code>.ServiceType_e ServiceType = 3;</code>
   * @return The enum numeric value on the wire for serviceType.
   */
  int getServiceTypeValue();
  /**
   * <code>.ServiceType_e ServiceType = 3;</code>
   * @return The serviceType.
   */
  com.erksystem.protobuf.api.ServiceType_e getServiceType();
}
