// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkApiMsg.proto

// Protobuf Java Version: 3.25.0
package com.erksystem.protobuf.api;

/**
 * Protobuf type {@code HeartBeatRP_m}
 */
public final class HeartBeatRP_m extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HeartBeatRP_m)
    HeartBeatRP_mOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeartBeatRP_m.newBuilder() to construct.
  private HeartBeatRP_m(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeartBeatRP_m() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HeartBeatRP_m();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_HeartBeatRP_m_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_HeartBeatRP_m_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.erksystem.protobuf.api.HeartBeatRP_m.class, com.erksystem.protobuf.api.HeartBeatRP_m.Builder.class);
  }

  private int bitField0_;
  public static final int ERKMSGHEAD_FIELD_NUMBER = 1;
  private com.erksystem.protobuf.api.ErkMsgHeader erkMsgHead_;
  /**
   * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
   * @return Whether the erkMsgHead field is set.
   */
  @java.lang.Override
  public boolean hasErkMsgHead() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
   * @return The erkMsgHead.
   */
  @java.lang.Override
  public com.erksystem.protobuf.api.ErkMsgHeader getErkMsgHead() {
    return erkMsgHead_ == null ? com.erksystem.protobuf.api.ErkMsgHeader.getDefaultInstance() : erkMsgHead_;
  }
  /**
   * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
   */
  @java.lang.Override
  public com.erksystem.protobuf.api.ErkMsgHeaderOrBuilder getErkMsgHeadOrBuilder() {
    return erkMsgHead_ == null ? com.erksystem.protobuf.api.ErkMsgHeader.getDefaultInstance() : erkMsgHead_;
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_ = 0;
  /**
   * <code>int32 Status = 2;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getErkMsgHead());
    }
    if (status_ != 0) {
      output.writeInt32(2, status_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getErkMsgHead());
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, status_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.erksystem.protobuf.api.HeartBeatRP_m)) {
      return super.equals(obj);
    }
    com.erksystem.protobuf.api.HeartBeatRP_m other = (com.erksystem.protobuf.api.HeartBeatRP_m) obj;

    if (hasErkMsgHead() != other.hasErkMsgHead()) return false;
    if (hasErkMsgHead()) {
      if (!getErkMsgHead()
          .equals(other.getErkMsgHead())) return false;
    }
    if (getStatus()
        != other.getStatus()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasErkMsgHead()) {
      hash = (37 * hash) + ERKMSGHEAD_FIELD_NUMBER;
      hash = (53 * hash) + getErkMsgHead().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.erksystem.protobuf.api.HeartBeatRP_m parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.erksystem.protobuf.api.HeartBeatRP_m parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.erksystem.protobuf.api.HeartBeatRP_m parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.erksystem.protobuf.api.HeartBeatRP_m parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.erksystem.protobuf.api.HeartBeatRP_m parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.erksystem.protobuf.api.HeartBeatRP_m parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.erksystem.protobuf.api.HeartBeatRP_m parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.erksystem.protobuf.api.HeartBeatRP_m parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.erksystem.protobuf.api.HeartBeatRP_m parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.erksystem.protobuf.api.HeartBeatRP_m parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.erksystem.protobuf.api.HeartBeatRP_m parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.erksystem.protobuf.api.HeartBeatRP_m parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.erksystem.protobuf.api.HeartBeatRP_m prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code HeartBeatRP_m}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HeartBeatRP_m)
      com.erksystem.protobuf.api.HeartBeatRP_mOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_HeartBeatRP_m_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_HeartBeatRP_m_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.erksystem.protobuf.api.HeartBeatRP_m.class, com.erksystem.protobuf.api.HeartBeatRP_m.Builder.class);
    }

    // Construct using com.erksystem.protobuf.api.HeartBeatRP_m.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getErkMsgHeadFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      erkMsgHead_ = null;
      if (erkMsgHeadBuilder_ != null) {
        erkMsgHeadBuilder_.dispose();
        erkMsgHeadBuilder_ = null;
      }
      status_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_HeartBeatRP_m_descriptor;
    }

    @java.lang.Override
    public com.erksystem.protobuf.api.HeartBeatRP_m getDefaultInstanceForType() {
      return com.erksystem.protobuf.api.HeartBeatRP_m.getDefaultInstance();
    }

    @java.lang.Override
    public com.erksystem.protobuf.api.HeartBeatRP_m build() {
      com.erksystem.protobuf.api.HeartBeatRP_m result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.erksystem.protobuf.api.HeartBeatRP_m buildPartial() {
      com.erksystem.protobuf.api.HeartBeatRP_m result = new com.erksystem.protobuf.api.HeartBeatRP_m(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.erksystem.protobuf.api.HeartBeatRP_m result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.erkMsgHead_ = erkMsgHeadBuilder_ == null
            ? erkMsgHead_
            : erkMsgHeadBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.status_ = status_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.erksystem.protobuf.api.HeartBeatRP_m) {
        return mergeFrom((com.erksystem.protobuf.api.HeartBeatRP_m)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.erksystem.protobuf.api.HeartBeatRP_m other) {
      if (other == com.erksystem.protobuf.api.HeartBeatRP_m.getDefaultInstance()) return this;
      if (other.hasErkMsgHead()) {
        mergeErkMsgHead(other.getErkMsgHead());
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getErkMsgHeadFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              status_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.erksystem.protobuf.api.ErkMsgHeader erkMsgHead_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.erksystem.protobuf.api.ErkMsgHeader, com.erksystem.protobuf.api.ErkMsgHeader.Builder, com.erksystem.protobuf.api.ErkMsgHeaderOrBuilder> erkMsgHeadBuilder_;
    /**
     * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
     * @return Whether the erkMsgHead field is set.
     */
    public boolean hasErkMsgHead() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
     * @return The erkMsgHead.
     */
    public com.erksystem.protobuf.api.ErkMsgHeader getErkMsgHead() {
      if (erkMsgHeadBuilder_ == null) {
        return erkMsgHead_ == null ? com.erksystem.protobuf.api.ErkMsgHeader.getDefaultInstance() : erkMsgHead_;
      } else {
        return erkMsgHeadBuilder_.getMessage();
      }
    }
    /**
     * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
     */
    public Builder setErkMsgHead(com.erksystem.protobuf.api.ErkMsgHeader value) {
      if (erkMsgHeadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        erkMsgHead_ = value;
      } else {
        erkMsgHeadBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
     */
    public Builder setErkMsgHead(
        com.erksystem.protobuf.api.ErkMsgHeader.Builder builderForValue) {
      if (erkMsgHeadBuilder_ == null) {
        erkMsgHead_ = builderForValue.build();
      } else {
        erkMsgHeadBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
     */
    public Builder mergeErkMsgHead(com.erksystem.protobuf.api.ErkMsgHeader value) {
      if (erkMsgHeadBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          erkMsgHead_ != null &&
          erkMsgHead_ != com.erksystem.protobuf.api.ErkMsgHeader.getDefaultInstance()) {
          getErkMsgHeadBuilder().mergeFrom(value);
        } else {
          erkMsgHead_ = value;
        }
      } else {
        erkMsgHeadBuilder_.mergeFrom(value);
      }
      if (erkMsgHead_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
     */
    public Builder clearErkMsgHead() {
      bitField0_ = (bitField0_ & ~0x00000001);
      erkMsgHead_ = null;
      if (erkMsgHeadBuilder_ != null) {
        erkMsgHeadBuilder_.dispose();
        erkMsgHeadBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
     */
    public com.erksystem.protobuf.api.ErkMsgHeader.Builder getErkMsgHeadBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getErkMsgHeadFieldBuilder().getBuilder();
    }
    /**
     * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
     */
    public com.erksystem.protobuf.api.ErkMsgHeaderOrBuilder getErkMsgHeadOrBuilder() {
      if (erkMsgHeadBuilder_ != null) {
        return erkMsgHeadBuilder_.getMessageOrBuilder();
      } else {
        return erkMsgHead_ == null ?
            com.erksystem.protobuf.api.ErkMsgHeader.getDefaultInstance() : erkMsgHead_;
      }
    }
    /**
     * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.erksystem.protobuf.api.ErkMsgHeader, com.erksystem.protobuf.api.ErkMsgHeader.Builder, com.erksystem.protobuf.api.ErkMsgHeaderOrBuilder> 
        getErkMsgHeadFieldBuilder() {
      if (erkMsgHeadBuilder_ == null) {
        erkMsgHeadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.erksystem.protobuf.api.ErkMsgHeader, com.erksystem.protobuf.api.ErkMsgHeader.Builder, com.erksystem.protobuf.api.ErkMsgHeaderOrBuilder>(
                getErkMsgHead(),
                getParentForChildren(),
                isClean());
        erkMsgHead_ = null;
      }
      return erkMsgHeadBuilder_;
    }

    private int status_ ;
    /**
     * <code>int32 Status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 Status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {

      status_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      status_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:HeartBeatRP_m)
  }

  // @@protoc_insertion_point(class_scope:HeartBeatRP_m)
  private static final com.erksystem.protobuf.api.HeartBeatRP_m DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.erksystem.protobuf.api.HeartBeatRP_m();
  }

  public static com.erksystem.protobuf.api.HeartBeatRP_m getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeartBeatRP_m>
      PARSER = new com.google.protobuf.AbstractParser<HeartBeatRP_m>() {
    @java.lang.Override
    public HeartBeatRP_m parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HeartBeatRP_m> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeartBeatRP_m> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.erksystem.protobuf.api.HeartBeatRP_m getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

