// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkApiMsg.proto

// Protobuf Java Version: 3.25.0
package com.erksystem.protobuf.api;

public interface HeartBeatRP_mOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartBeatRP_m)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
   * @return Whether the erkMsgHead field is set.
   */
  boolean hasErkMsgHead();
  /**
   * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
   * @return The erkMsgHead.
   */
  com.erksystem.protobuf.api.ErkMsgHeader getErkMsgHead();
  /**
   * <code>.ErkMsgHeader ErkMsgHead = 1;</code>
   */
  com.erksystem.protobuf.api.ErkMsgHeaderOrBuilder getErkMsgHeadOrBuilder();

  /**
   * <code>int32 Status = 2;</code>
   * @return The status.
   */
  int getStatus();
}
