// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkApiMsg.proto

// Protobuf Java Version: 3.25.0
package com.erksystem.protobuf.api;

public interface UpdateUserInfoRQ_mOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateUserInfoRQ_m)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ErkMsgType_e MsgType = 1;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  int getMsgTypeValue();
  /**
   * <code>.ErkMsgType_e MsgType = 1;</code>
   * @return The msgType.
   */
  com.erksystem.protobuf.api.ErkMsgType_e getMsgType();

  /**
   * <code>string OrgName = 2;</code>
   * @return The orgName.
   */
  java.lang.String getOrgName();
  /**
   * <code>string OrgName = 2;</code>
   * @return The bytes for orgName.
   */
  com.google.protobuf.ByteString
      getOrgNameBytes();

  /**
   * <code>string UserName = 3;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string UserName = 3;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string Old_UserPwd = 4;</code>
   * @return The oldUserPwd.
   */
  java.lang.String getOldUserPwd();
  /**
   * <code>string Old_UserPwd = 4;</code>
   * @return The bytes for oldUserPwd.
   */
  com.google.protobuf.ByteString
      getOldUserPwdBytes();

  /**
   * <code>string Old_ServiceDuration = 5;</code>
   * @return The oldServiceDuration.
   */
  java.lang.String getOldServiceDuration();
  /**
   * <code>string Old_ServiceDuration = 5;</code>
   * @return The bytes for oldServiceDuration.
   */
  com.google.protobuf.ByteString
      getOldServiceDurationBytes();

  /**
   * <code>int32 Old_Age = 6;</code>
   * @return The oldAge.
   */
  int getOldAge();

  /**
   * <code>int32 Old_Sex = 7;</code>
   * @return The oldSex.
   */
  int getOldSex();

  /**
   * <code>int32 Old_UserType = 8;</code>
   * @return The oldUserType.
   */
  int getOldUserType();

  /**
   * <code>.ServiceType_e Old_ServiceType = 9;</code>
   * @return The enum numeric value on the wire for oldServiceType.
   */
  int getOldServiceTypeValue();
  /**
   * <code>.ServiceType_e Old_ServiceType = 9;</code>
   * @return The oldServiceType.
   */
  com.erksystem.protobuf.api.ServiceType_e getOldServiceType();

  /**
   * <code>string New_UserPwd = 10;</code>
   * @return The newUserPwd.
   */
  java.lang.String getNewUserPwd();
  /**
   * <code>string New_UserPwd = 10;</code>
   * @return The bytes for newUserPwd.
   */
  com.google.protobuf.ByteString
      getNewUserPwdBytes();

  /**
   * <code>string New_ServiceDuration = 11;</code>
   * @return The newServiceDuration.
   */
  java.lang.String getNewServiceDuration();
  /**
   * <code>string New_ServiceDuration = 11;</code>
   * @return The bytes for newServiceDuration.
   */
  com.google.protobuf.ByteString
      getNewServiceDurationBytes();

  /**
   * <code>int32 New_Age = 12;</code>
   * @return The newAge.
   */
  int getNewAge();

  /**
   * <code>int32 New_Sex = 13;</code>
   * @return The newSex.
   */
  int getNewSex();

  /**
   * <code>int32 New_UserType = 14;</code>
   * @return The newUserType.
   */
  int getNewUserType();

  /**
   * <code>.ServiceType_e New_ServiceType = 15;</code>
   * @return The enum numeric value on the wire for newServiceType.
   */
  int getNewServiceTypeValue();
  /**
   * <code>.ServiceType_e New_ServiceType = 15;</code>
   * @return The newServiceType.
   */
  com.erksystem.protobuf.api.ServiceType_e getNewServiceType();
}
