// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErkApiMsg.proto

// Protobuf Java Version: 3.25.0
package com.erksystem.protobuf.api;

/**
 * Protobuf type {@code UpdateUserInfoRP_m}
 */
public final class UpdateUserInfoRP_m extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UpdateUserInfoRP_m)
    UpdateUserInfoRP_mOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateUserInfoRP_m.newBuilder() to construct.
  private UpdateUserInfoRP_m(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateUserInfoRP_m() {
    msgType_ = 0;
    orgName_ = "";
    userName_ = "";
    resultType_ = 0;
    oldUserPwd_ = "";
    oldServiceDuration_ = "";
    oldServiceType_ = 0;
    newUserPwd_ = "";
    newServiceDuration_ = "";
    newServiceType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateUserInfoRP_m();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_UpdateUserInfoRP_m_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_UpdateUserInfoRP_m_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.erksystem.protobuf.api.UpdateUserInfoRP_m.class, com.erksystem.protobuf.api.UpdateUserInfoRP_m.Builder.class);
  }

  private int bitField0_;
  public static final int MSGTYPE_FIELD_NUMBER = 1;
  private int msgType_ = 0;
  /**
   * <code>.ErkMsgType_e MsgType = 1;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  @java.lang.Override public int getMsgTypeValue() {
    return msgType_;
  }
  /**
   * <code>.ErkMsgType_e MsgType = 1;</code>
   * @return The msgType.
   */
  @java.lang.Override public com.erksystem.protobuf.api.ErkMsgType_e getMsgType() {
    com.erksystem.protobuf.api.ErkMsgType_e result = com.erksystem.protobuf.api.ErkMsgType_e.forNumber(msgType_);
    return result == null ? com.erksystem.protobuf.api.ErkMsgType_e.UNRECOGNIZED : result;
  }

  public static final int QUEUEINFO_FIELD_NUMBER = 2;
  private com.erksystem.protobuf.api.QueueInfo_s queueInfo_;
  /**
   * <code>.QueueInfo_s QueueInfo = 2;</code>
   * @return Whether the queueInfo field is set.
   */
  @java.lang.Override
  public boolean hasQueueInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.QueueInfo_s QueueInfo = 2;</code>
   * @return The queueInfo.
   */
  @java.lang.Override
  public com.erksystem.protobuf.api.QueueInfo_s getQueueInfo() {
    return queueInfo_ == null ? com.erksystem.protobuf.api.QueueInfo_s.getDefaultInstance() : queueInfo_;
  }
  /**
   * <code>.QueueInfo_s QueueInfo = 2;</code>
   */
  @java.lang.Override
  public com.erksystem.protobuf.api.QueueInfo_sOrBuilder getQueueInfoOrBuilder() {
    return queueInfo_ == null ? com.erksystem.protobuf.api.QueueInfo_s.getDefaultInstance() : queueInfo_;
  }

  public static final int ORGNAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object orgName_ = "";
  /**
   * <code>string OrgName = 3;</code>
   * @return The orgName.
   */
  @java.lang.Override
  public java.lang.String getOrgName() {
    java.lang.Object ref = orgName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orgName_ = s;
      return s;
    }
  }
  /**
   * <code>string OrgName = 3;</code>
   * @return The bytes for orgName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrgNameBytes() {
    java.lang.Object ref = orgName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orgName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userName_ = "";
  /**
   * <code>string UserName = 4;</code>
   * @return The userName.
   */
  @java.lang.Override
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string UserName = 4;</code>
   * @return The bytes for userName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULTTYPE_FIELD_NUMBER = 5;
  private int resultType_ = 0;
  /**
   * <code>.UserProfileResult_e ResultType = 5;</code>
   * @return The enum numeric value on the wire for resultType.
   */
  @java.lang.Override public int getResultTypeValue() {
    return resultType_;
  }
  /**
   * <code>.UserProfileResult_e ResultType = 5;</code>
   * @return The resultType.
   */
  @java.lang.Override public com.erksystem.protobuf.api.UserProfileResult_e getResultType() {
    com.erksystem.protobuf.api.UserProfileResult_e result = com.erksystem.protobuf.api.UserProfileResult_e.forNumber(resultType_);
    return result == null ? com.erksystem.protobuf.api.UserProfileResult_e.UNRECOGNIZED : result;
  }

  public static final int OLD_USERPWD_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object oldUserPwd_ = "";
  /**
   * <code>string Old_UserPwd = 6;</code>
   * @return The oldUserPwd.
   */
  @java.lang.Override
  public java.lang.String getOldUserPwd() {
    java.lang.Object ref = oldUserPwd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      oldUserPwd_ = s;
      return s;
    }
  }
  /**
   * <code>string Old_UserPwd = 6;</code>
   * @return The bytes for oldUserPwd.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOldUserPwdBytes() {
    java.lang.Object ref = oldUserPwd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      oldUserPwd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OLD_SERVICEDURATION_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object oldServiceDuration_ = "";
  /**
   * <code>string Old_ServiceDuration = 7;</code>
   * @return The oldServiceDuration.
   */
  @java.lang.Override
  public java.lang.String getOldServiceDuration() {
    java.lang.Object ref = oldServiceDuration_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      oldServiceDuration_ = s;
      return s;
    }
  }
  /**
   * <code>string Old_ServiceDuration = 7;</code>
   * @return The bytes for oldServiceDuration.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOldServiceDurationBytes() {
    java.lang.Object ref = oldServiceDuration_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      oldServiceDuration_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OLD_AGE_FIELD_NUMBER = 8;
  private int oldAge_ = 0;
  /**
   * <code>int32 Old_Age = 8;</code>
   * @return The oldAge.
   */
  @java.lang.Override
  public int getOldAge() {
    return oldAge_;
  }

  public static final int OLD_SEX_FIELD_NUMBER = 9;
  private int oldSex_ = 0;
  /**
   * <code>int32 Old_Sex = 9;</code>
   * @return The oldSex.
   */
  @java.lang.Override
  public int getOldSex() {
    return oldSex_;
  }

  public static final int OLD_USERTYPE_FIELD_NUMBER = 10;
  private int oldUserType_ = 0;
  /**
   * <code>int32 Old_UserType = 10;</code>
   * @return The oldUserType.
   */
  @java.lang.Override
  public int getOldUserType() {
    return oldUserType_;
  }

  public static final int OLD_SERVICETYPE_FIELD_NUMBER = 11;
  private int oldServiceType_ = 0;
  /**
   * <code>.ServiceType_e Old_ServiceType = 11;</code>
   * @return The enum numeric value on the wire for oldServiceType.
   */
  @java.lang.Override public int getOldServiceTypeValue() {
    return oldServiceType_;
  }
  /**
   * <code>.ServiceType_e Old_ServiceType = 11;</code>
   * @return The oldServiceType.
   */
  @java.lang.Override public com.erksystem.protobuf.api.ServiceType_e getOldServiceType() {
    com.erksystem.protobuf.api.ServiceType_e result = com.erksystem.protobuf.api.ServiceType_e.forNumber(oldServiceType_);
    return result == null ? com.erksystem.protobuf.api.ServiceType_e.UNRECOGNIZED : result;
  }

  public static final int NEW_USERPWD_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object newUserPwd_ = "";
  /**
   * <code>string New_UserPwd = 12;</code>
   * @return The newUserPwd.
   */
  @java.lang.Override
  public java.lang.String getNewUserPwd() {
    java.lang.Object ref = newUserPwd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      newUserPwd_ = s;
      return s;
    }
  }
  /**
   * <code>string New_UserPwd = 12;</code>
   * @return The bytes for newUserPwd.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNewUserPwdBytes() {
    java.lang.Object ref = newUserPwd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      newUserPwd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEW_SERVICEDURATION_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object newServiceDuration_ = "";
  /**
   * <code>string New_ServiceDuration = 13;</code>
   * @return The newServiceDuration.
   */
  @java.lang.Override
  public java.lang.String getNewServiceDuration() {
    java.lang.Object ref = newServiceDuration_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      newServiceDuration_ = s;
      return s;
    }
  }
  /**
   * <code>string New_ServiceDuration = 13;</code>
   * @return The bytes for newServiceDuration.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNewServiceDurationBytes() {
    java.lang.Object ref = newServiceDuration_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      newServiceDuration_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEW_AGE_FIELD_NUMBER = 14;
  private int newAge_ = 0;
  /**
   * <code>int32 New_Age = 14;</code>
   * @return The newAge.
   */
  @java.lang.Override
  public int getNewAge() {
    return newAge_;
  }

  public static final int NEW_SEX_FIELD_NUMBER = 15;
  private int newSex_ = 0;
  /**
   * <code>int32 New_Sex = 15;</code>
   * @return The newSex.
   */
  @java.lang.Override
  public int getNewSex() {
    return newSex_;
  }

  public static final int NEW_USERTYPE_FIELD_NUMBER = 16;
  private int newUserType_ = 0;
  /**
   * <code>int32 New_UserType = 16;</code>
   * @return The newUserType.
   */
  @java.lang.Override
  public int getNewUserType() {
    return newUserType_;
  }

  public static final int NEW_SERVICETYPE_FIELD_NUMBER = 17;
  private int newServiceType_ = 0;
  /**
   * <code>.ServiceType_e New_ServiceType = 17;</code>
   * @return The enum numeric value on the wire for newServiceType.
   */
  @java.lang.Override public int getNewServiceTypeValue() {
    return newServiceType_;
  }
  /**
   * <code>.ServiceType_e New_ServiceType = 17;</code>
   * @return The newServiceType.
   */
  @java.lang.Override public com.erksystem.protobuf.api.ServiceType_e getNewServiceType() {
    com.erksystem.protobuf.api.ServiceType_e result = com.erksystem.protobuf.api.ServiceType_e.forNumber(newServiceType_);
    return result == null ? com.erksystem.protobuf.api.ServiceType_e.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msgType_ != com.erksystem.protobuf.api.ErkMsgType_e.ErkMsgType_unknown.getNumber()) {
      output.writeEnum(1, msgType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getQueueInfo());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orgName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, orgName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userName_);
    }
    if (resultType_ != com.erksystem.protobuf.api.UserProfileResult_e.UserProfileResult_unknown.getNumber()) {
      output.writeEnum(5, resultType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oldUserPwd_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, oldUserPwd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oldServiceDuration_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, oldServiceDuration_);
    }
    if (oldAge_ != 0) {
      output.writeInt32(8, oldAge_);
    }
    if (oldSex_ != 0) {
      output.writeInt32(9, oldSex_);
    }
    if (oldUserType_ != 0) {
      output.writeInt32(10, oldUserType_);
    }
    if (oldServiceType_ != com.erksystem.protobuf.api.ServiceType_e.ServiceType_unknown.getNumber()) {
      output.writeEnum(11, oldServiceType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(newUserPwd_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, newUserPwd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(newServiceDuration_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, newServiceDuration_);
    }
    if (newAge_ != 0) {
      output.writeInt32(14, newAge_);
    }
    if (newSex_ != 0) {
      output.writeInt32(15, newSex_);
    }
    if (newUserType_ != 0) {
      output.writeInt32(16, newUserType_);
    }
    if (newServiceType_ != com.erksystem.protobuf.api.ServiceType_e.ServiceType_unknown.getNumber()) {
      output.writeEnum(17, newServiceType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msgType_ != com.erksystem.protobuf.api.ErkMsgType_e.ErkMsgType_unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, msgType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getQueueInfo());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orgName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, orgName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userName_);
    }
    if (resultType_ != com.erksystem.protobuf.api.UserProfileResult_e.UserProfileResult_unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, resultType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oldUserPwd_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, oldUserPwd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oldServiceDuration_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, oldServiceDuration_);
    }
    if (oldAge_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, oldAge_);
    }
    if (oldSex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, oldSex_);
    }
    if (oldUserType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, oldUserType_);
    }
    if (oldServiceType_ != com.erksystem.protobuf.api.ServiceType_e.ServiceType_unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(11, oldServiceType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(newUserPwd_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, newUserPwd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(newServiceDuration_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, newServiceDuration_);
    }
    if (newAge_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, newAge_);
    }
    if (newSex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, newSex_);
    }
    if (newUserType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, newUserType_);
    }
    if (newServiceType_ != com.erksystem.protobuf.api.ServiceType_e.ServiceType_unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(17, newServiceType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.erksystem.protobuf.api.UpdateUserInfoRP_m)) {
      return super.equals(obj);
    }
    com.erksystem.protobuf.api.UpdateUserInfoRP_m other = (com.erksystem.protobuf.api.UpdateUserInfoRP_m) obj;

    if (msgType_ != other.msgType_) return false;
    if (hasQueueInfo() != other.hasQueueInfo()) return false;
    if (hasQueueInfo()) {
      if (!getQueueInfo()
          .equals(other.getQueueInfo())) return false;
    }
    if (!getOrgName()
        .equals(other.getOrgName())) return false;
    if (!getUserName()
        .equals(other.getUserName())) return false;
    if (resultType_ != other.resultType_) return false;
    if (!getOldUserPwd()
        .equals(other.getOldUserPwd())) return false;
    if (!getOldServiceDuration()
        .equals(other.getOldServiceDuration())) return false;
    if (getOldAge()
        != other.getOldAge()) return false;
    if (getOldSex()
        != other.getOldSex()) return false;
    if (getOldUserType()
        != other.getOldUserType()) return false;
    if (oldServiceType_ != other.oldServiceType_) return false;
    if (!getNewUserPwd()
        .equals(other.getNewUserPwd())) return false;
    if (!getNewServiceDuration()
        .equals(other.getNewServiceDuration())) return false;
    if (getNewAge()
        != other.getNewAge()) return false;
    if (getNewSex()
        != other.getNewSex()) return false;
    if (getNewUserType()
        != other.getNewUserType()) return false;
    if (newServiceType_ != other.newServiceType_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
    hash = (53 * hash) + msgType_;
    if (hasQueueInfo()) {
      hash = (37 * hash) + QUEUEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getQueueInfo().hashCode();
    }
    hash = (37 * hash) + ORGNAME_FIELD_NUMBER;
    hash = (53 * hash) + getOrgName().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + RESULTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + resultType_;
    hash = (37 * hash) + OLD_USERPWD_FIELD_NUMBER;
    hash = (53 * hash) + getOldUserPwd().hashCode();
    hash = (37 * hash) + OLD_SERVICEDURATION_FIELD_NUMBER;
    hash = (53 * hash) + getOldServiceDuration().hashCode();
    hash = (37 * hash) + OLD_AGE_FIELD_NUMBER;
    hash = (53 * hash) + getOldAge();
    hash = (37 * hash) + OLD_SEX_FIELD_NUMBER;
    hash = (53 * hash) + getOldSex();
    hash = (37 * hash) + OLD_USERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getOldUserType();
    hash = (37 * hash) + OLD_SERVICETYPE_FIELD_NUMBER;
    hash = (53 * hash) + oldServiceType_;
    hash = (37 * hash) + NEW_USERPWD_FIELD_NUMBER;
    hash = (53 * hash) + getNewUserPwd().hashCode();
    hash = (37 * hash) + NEW_SERVICEDURATION_FIELD_NUMBER;
    hash = (53 * hash) + getNewServiceDuration().hashCode();
    hash = (37 * hash) + NEW_AGE_FIELD_NUMBER;
    hash = (53 * hash) + getNewAge();
    hash = (37 * hash) + NEW_SEX_FIELD_NUMBER;
    hash = (53 * hash) + getNewSex();
    hash = (37 * hash) + NEW_USERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getNewUserType();
    hash = (37 * hash) + NEW_SERVICETYPE_FIELD_NUMBER;
    hash = (53 * hash) + newServiceType_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.erksystem.protobuf.api.UpdateUserInfoRP_m parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.erksystem.protobuf.api.UpdateUserInfoRP_m parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.erksystem.protobuf.api.UpdateUserInfoRP_m parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.erksystem.protobuf.api.UpdateUserInfoRP_m parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.erksystem.protobuf.api.UpdateUserInfoRP_m parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.erksystem.protobuf.api.UpdateUserInfoRP_m parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.erksystem.protobuf.api.UpdateUserInfoRP_m parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.erksystem.protobuf.api.UpdateUserInfoRP_m parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.erksystem.protobuf.api.UpdateUserInfoRP_m parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.erksystem.protobuf.api.UpdateUserInfoRP_m parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.erksystem.protobuf.api.UpdateUserInfoRP_m parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.erksystem.protobuf.api.UpdateUserInfoRP_m parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.erksystem.protobuf.api.UpdateUserInfoRP_m prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UpdateUserInfoRP_m}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UpdateUserInfoRP_m)
      com.erksystem.protobuf.api.UpdateUserInfoRP_mOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_UpdateUserInfoRP_m_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_UpdateUserInfoRP_m_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.erksystem.protobuf.api.UpdateUserInfoRP_m.class, com.erksystem.protobuf.api.UpdateUserInfoRP_m.Builder.class);
    }

    // Construct using com.erksystem.protobuf.api.UpdateUserInfoRP_m.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getQueueInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      msgType_ = 0;
      queueInfo_ = null;
      if (queueInfoBuilder_ != null) {
        queueInfoBuilder_.dispose();
        queueInfoBuilder_ = null;
      }
      orgName_ = "";
      userName_ = "";
      resultType_ = 0;
      oldUserPwd_ = "";
      oldServiceDuration_ = "";
      oldAge_ = 0;
      oldSex_ = 0;
      oldUserType_ = 0;
      oldServiceType_ = 0;
      newUserPwd_ = "";
      newServiceDuration_ = "";
      newAge_ = 0;
      newSex_ = 0;
      newUserType_ = 0;
      newServiceType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.erksystem.protobuf.api.ErkApiMsgOuterClass.internal_static_UpdateUserInfoRP_m_descriptor;
    }

    @java.lang.Override
    public com.erksystem.protobuf.api.UpdateUserInfoRP_m getDefaultInstanceForType() {
      return com.erksystem.protobuf.api.UpdateUserInfoRP_m.getDefaultInstance();
    }

    @java.lang.Override
    public com.erksystem.protobuf.api.UpdateUserInfoRP_m build() {
      com.erksystem.protobuf.api.UpdateUserInfoRP_m result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.erksystem.protobuf.api.UpdateUserInfoRP_m buildPartial() {
      com.erksystem.protobuf.api.UpdateUserInfoRP_m result = new com.erksystem.protobuf.api.UpdateUserInfoRP_m(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.erksystem.protobuf.api.UpdateUserInfoRP_m result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.msgType_ = msgType_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.queueInfo_ = queueInfoBuilder_ == null
            ? queueInfo_
            : queueInfoBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.orgName_ = orgName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.userName_ = userName_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.resultType_ = resultType_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.oldUserPwd_ = oldUserPwd_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.oldServiceDuration_ = oldServiceDuration_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.oldAge_ = oldAge_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.oldSex_ = oldSex_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.oldUserType_ = oldUserType_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.oldServiceType_ = oldServiceType_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.newUserPwd_ = newUserPwd_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.newServiceDuration_ = newServiceDuration_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.newAge_ = newAge_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.newSex_ = newSex_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.newUserType_ = newUserType_;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.newServiceType_ = newServiceType_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.erksystem.protobuf.api.UpdateUserInfoRP_m) {
        return mergeFrom((com.erksystem.protobuf.api.UpdateUserInfoRP_m)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.erksystem.protobuf.api.UpdateUserInfoRP_m other) {
      if (other == com.erksystem.protobuf.api.UpdateUserInfoRP_m.getDefaultInstance()) return this;
      if (other.msgType_ != 0) {
        setMsgTypeValue(other.getMsgTypeValue());
      }
      if (other.hasQueueInfo()) {
        mergeQueueInfo(other.getQueueInfo());
      }
      if (!other.getOrgName().isEmpty()) {
        orgName_ = other.orgName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.resultType_ != 0) {
        setResultTypeValue(other.getResultTypeValue());
      }
      if (!other.getOldUserPwd().isEmpty()) {
        oldUserPwd_ = other.oldUserPwd_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getOldServiceDuration().isEmpty()) {
        oldServiceDuration_ = other.oldServiceDuration_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getOldAge() != 0) {
        setOldAge(other.getOldAge());
      }
      if (other.getOldSex() != 0) {
        setOldSex(other.getOldSex());
      }
      if (other.getOldUserType() != 0) {
        setOldUserType(other.getOldUserType());
      }
      if (other.oldServiceType_ != 0) {
        setOldServiceTypeValue(other.getOldServiceTypeValue());
      }
      if (!other.getNewUserPwd().isEmpty()) {
        newUserPwd_ = other.newUserPwd_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (!other.getNewServiceDuration().isEmpty()) {
        newServiceDuration_ = other.newServiceDuration_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (other.getNewAge() != 0) {
        setNewAge(other.getNewAge());
      }
      if (other.getNewSex() != 0) {
        setNewSex(other.getNewSex());
      }
      if (other.getNewUserType() != 0) {
        setNewUserType(other.getNewUserType());
      }
      if (other.newServiceType_ != 0) {
        setNewServiceTypeValue(other.getNewServiceTypeValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              msgType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getQueueInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              orgName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              userName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              resultType_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              oldUserPwd_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              oldServiceDuration_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              oldAge_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              oldSex_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              oldUserType_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              oldServiceType_ = input.readEnum();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 98: {
              newUserPwd_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              newServiceDuration_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 112: {
              newAge_ = input.readInt32();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 120: {
              newSex_ = input.readInt32();
              bitField0_ |= 0x00004000;
              break;
            } // case 120
            case 128: {
              newUserType_ = input.readInt32();
              bitField0_ |= 0x00008000;
              break;
            } // case 128
            case 136: {
              newServiceType_ = input.readEnum();
              bitField0_ |= 0x00010000;
              break;
            } // case 136
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int msgType_ = 0;
    /**
     * <code>.ErkMsgType_e MsgType = 1;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.ErkMsgType_e MsgType = 1;</code>
     * @param value The enum numeric value on the wire for msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgTypeValue(int value) {
      msgType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ErkMsgType_e MsgType = 1;</code>
     * @return The msgType.
     */
    @java.lang.Override
    public com.erksystem.protobuf.api.ErkMsgType_e getMsgType() {
      com.erksystem.protobuf.api.ErkMsgType_e result = com.erksystem.protobuf.api.ErkMsgType_e.forNumber(msgType_);
      return result == null ? com.erksystem.protobuf.api.ErkMsgType_e.UNRECOGNIZED : result;
    }
    /**
     * <code>.ErkMsgType_e MsgType = 1;</code>
     * @param value The msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgType(com.erksystem.protobuf.api.ErkMsgType_e value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      msgType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ErkMsgType_e MsgType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      msgType_ = 0;
      onChanged();
      return this;
    }

    private com.erksystem.protobuf.api.QueueInfo_s queueInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.erksystem.protobuf.api.QueueInfo_s, com.erksystem.protobuf.api.QueueInfo_s.Builder, com.erksystem.protobuf.api.QueueInfo_sOrBuilder> queueInfoBuilder_;
    /**
     * <code>.QueueInfo_s QueueInfo = 2;</code>
     * @return Whether the queueInfo field is set.
     */
    public boolean hasQueueInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.QueueInfo_s QueueInfo = 2;</code>
     * @return The queueInfo.
     */
    public com.erksystem.protobuf.api.QueueInfo_s getQueueInfo() {
      if (queueInfoBuilder_ == null) {
        return queueInfo_ == null ? com.erksystem.protobuf.api.QueueInfo_s.getDefaultInstance() : queueInfo_;
      } else {
        return queueInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.QueueInfo_s QueueInfo = 2;</code>
     */
    public Builder setQueueInfo(com.erksystem.protobuf.api.QueueInfo_s value) {
      if (queueInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        queueInfo_ = value;
      } else {
        queueInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.QueueInfo_s QueueInfo = 2;</code>
     */
    public Builder setQueueInfo(
        com.erksystem.protobuf.api.QueueInfo_s.Builder builderForValue) {
      if (queueInfoBuilder_ == null) {
        queueInfo_ = builderForValue.build();
      } else {
        queueInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.QueueInfo_s QueueInfo = 2;</code>
     */
    public Builder mergeQueueInfo(com.erksystem.protobuf.api.QueueInfo_s value) {
      if (queueInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          queueInfo_ != null &&
          queueInfo_ != com.erksystem.protobuf.api.QueueInfo_s.getDefaultInstance()) {
          getQueueInfoBuilder().mergeFrom(value);
        } else {
          queueInfo_ = value;
        }
      } else {
        queueInfoBuilder_.mergeFrom(value);
      }
      if (queueInfo_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.QueueInfo_s QueueInfo = 2;</code>
     */
    public Builder clearQueueInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      queueInfo_ = null;
      if (queueInfoBuilder_ != null) {
        queueInfoBuilder_.dispose();
        queueInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.QueueInfo_s QueueInfo = 2;</code>
     */
    public com.erksystem.protobuf.api.QueueInfo_s.Builder getQueueInfoBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getQueueInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.QueueInfo_s QueueInfo = 2;</code>
     */
    public com.erksystem.protobuf.api.QueueInfo_sOrBuilder getQueueInfoOrBuilder() {
      if (queueInfoBuilder_ != null) {
        return queueInfoBuilder_.getMessageOrBuilder();
      } else {
        return queueInfo_ == null ?
            com.erksystem.protobuf.api.QueueInfo_s.getDefaultInstance() : queueInfo_;
      }
    }
    /**
     * <code>.QueueInfo_s QueueInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.erksystem.protobuf.api.QueueInfo_s, com.erksystem.protobuf.api.QueueInfo_s.Builder, com.erksystem.protobuf.api.QueueInfo_sOrBuilder> 
        getQueueInfoFieldBuilder() {
      if (queueInfoBuilder_ == null) {
        queueInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.erksystem.protobuf.api.QueueInfo_s, com.erksystem.protobuf.api.QueueInfo_s.Builder, com.erksystem.protobuf.api.QueueInfo_sOrBuilder>(
                getQueueInfo(),
                getParentForChildren(),
                isClean());
        queueInfo_ = null;
      }
      return queueInfoBuilder_;
    }

    private java.lang.Object orgName_ = "";
    /**
     * <code>string OrgName = 3;</code>
     * @return The orgName.
     */
    public java.lang.String getOrgName() {
      java.lang.Object ref = orgName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orgName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string OrgName = 3;</code>
     * @return The bytes for orgName.
     */
    public com.google.protobuf.ByteString
        getOrgNameBytes() {
      java.lang.Object ref = orgName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orgName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string OrgName = 3;</code>
     * @param value The orgName to set.
     * @return This builder for chaining.
     */
    public Builder setOrgName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      orgName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string OrgName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrgName() {
      orgName_ = getDefaultInstance().getOrgName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string OrgName = 3;</code>
     * @param value The bytes for orgName to set.
     * @return This builder for chaining.
     */
    public Builder setOrgNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      orgName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <code>string UserName = 4;</code>
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string UserName = 4;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string UserName = 4;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string UserName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {
      userName_ = getDefaultInstance().getUserName();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string UserName = 4;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int resultType_ = 0;
    /**
     * <code>.UserProfileResult_e ResultType = 5;</code>
     * @return The enum numeric value on the wire for resultType.
     */
    @java.lang.Override public int getResultTypeValue() {
      return resultType_;
    }
    /**
     * <code>.UserProfileResult_e ResultType = 5;</code>
     * @param value The enum numeric value on the wire for resultType to set.
     * @return This builder for chaining.
     */
    public Builder setResultTypeValue(int value) {
      resultType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.UserProfileResult_e ResultType = 5;</code>
     * @return The resultType.
     */
    @java.lang.Override
    public com.erksystem.protobuf.api.UserProfileResult_e getResultType() {
      com.erksystem.protobuf.api.UserProfileResult_e result = com.erksystem.protobuf.api.UserProfileResult_e.forNumber(resultType_);
      return result == null ? com.erksystem.protobuf.api.UserProfileResult_e.UNRECOGNIZED : result;
    }
    /**
     * <code>.UserProfileResult_e ResultType = 5;</code>
     * @param value The resultType to set.
     * @return This builder for chaining.
     */
    public Builder setResultType(com.erksystem.protobuf.api.UserProfileResult_e value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      resultType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.UserProfileResult_e ResultType = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultType() {
      bitField0_ = (bitField0_ & ~0x00000010);
      resultType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object oldUserPwd_ = "";
    /**
     * <code>string Old_UserPwd = 6;</code>
     * @return The oldUserPwd.
     */
    public java.lang.String getOldUserPwd() {
      java.lang.Object ref = oldUserPwd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oldUserPwd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Old_UserPwd = 6;</code>
     * @return The bytes for oldUserPwd.
     */
    public com.google.protobuf.ByteString
        getOldUserPwdBytes() {
      java.lang.Object ref = oldUserPwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oldUserPwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Old_UserPwd = 6;</code>
     * @param value The oldUserPwd to set.
     * @return This builder for chaining.
     */
    public Builder setOldUserPwd(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      oldUserPwd_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string Old_UserPwd = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOldUserPwd() {
      oldUserPwd_ = getDefaultInstance().getOldUserPwd();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string Old_UserPwd = 6;</code>
     * @param value The bytes for oldUserPwd to set.
     * @return This builder for chaining.
     */
    public Builder setOldUserPwdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      oldUserPwd_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object oldServiceDuration_ = "";
    /**
     * <code>string Old_ServiceDuration = 7;</code>
     * @return The oldServiceDuration.
     */
    public java.lang.String getOldServiceDuration() {
      java.lang.Object ref = oldServiceDuration_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oldServiceDuration_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Old_ServiceDuration = 7;</code>
     * @return The bytes for oldServiceDuration.
     */
    public com.google.protobuf.ByteString
        getOldServiceDurationBytes() {
      java.lang.Object ref = oldServiceDuration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oldServiceDuration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Old_ServiceDuration = 7;</code>
     * @param value The oldServiceDuration to set.
     * @return This builder for chaining.
     */
    public Builder setOldServiceDuration(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      oldServiceDuration_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string Old_ServiceDuration = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOldServiceDuration() {
      oldServiceDuration_ = getDefaultInstance().getOldServiceDuration();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string Old_ServiceDuration = 7;</code>
     * @param value The bytes for oldServiceDuration to set.
     * @return This builder for chaining.
     */
    public Builder setOldServiceDurationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      oldServiceDuration_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private int oldAge_ ;
    /**
     * <code>int32 Old_Age = 8;</code>
     * @return The oldAge.
     */
    @java.lang.Override
    public int getOldAge() {
      return oldAge_;
    }
    /**
     * <code>int32 Old_Age = 8;</code>
     * @param value The oldAge to set.
     * @return This builder for chaining.
     */
    public Builder setOldAge(int value) {

      oldAge_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Old_Age = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearOldAge() {
      bitField0_ = (bitField0_ & ~0x00000080);
      oldAge_ = 0;
      onChanged();
      return this;
    }

    private int oldSex_ ;
    /**
     * <code>int32 Old_Sex = 9;</code>
     * @return The oldSex.
     */
    @java.lang.Override
    public int getOldSex() {
      return oldSex_;
    }
    /**
     * <code>int32 Old_Sex = 9;</code>
     * @param value The oldSex to set.
     * @return This builder for chaining.
     */
    public Builder setOldSex(int value) {

      oldSex_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Old_Sex = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearOldSex() {
      bitField0_ = (bitField0_ & ~0x00000100);
      oldSex_ = 0;
      onChanged();
      return this;
    }

    private int oldUserType_ ;
    /**
     * <code>int32 Old_UserType = 10;</code>
     * @return The oldUserType.
     */
    @java.lang.Override
    public int getOldUserType() {
      return oldUserType_;
    }
    /**
     * <code>int32 Old_UserType = 10;</code>
     * @param value The oldUserType to set.
     * @return This builder for chaining.
     */
    public Builder setOldUserType(int value) {

      oldUserType_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Old_UserType = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearOldUserType() {
      bitField0_ = (bitField0_ & ~0x00000200);
      oldUserType_ = 0;
      onChanged();
      return this;
    }

    private int oldServiceType_ = 0;
    /**
     * <code>.ServiceType_e Old_ServiceType = 11;</code>
     * @return The enum numeric value on the wire for oldServiceType.
     */
    @java.lang.Override public int getOldServiceTypeValue() {
      return oldServiceType_;
    }
    /**
     * <code>.ServiceType_e Old_ServiceType = 11;</code>
     * @param value The enum numeric value on the wire for oldServiceType to set.
     * @return This builder for chaining.
     */
    public Builder setOldServiceTypeValue(int value) {
      oldServiceType_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.ServiceType_e Old_ServiceType = 11;</code>
     * @return The oldServiceType.
     */
    @java.lang.Override
    public com.erksystem.protobuf.api.ServiceType_e getOldServiceType() {
      com.erksystem.protobuf.api.ServiceType_e result = com.erksystem.protobuf.api.ServiceType_e.forNumber(oldServiceType_);
      return result == null ? com.erksystem.protobuf.api.ServiceType_e.UNRECOGNIZED : result;
    }
    /**
     * <code>.ServiceType_e Old_ServiceType = 11;</code>
     * @param value The oldServiceType to set.
     * @return This builder for chaining.
     */
    public Builder setOldServiceType(com.erksystem.protobuf.api.ServiceType_e value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000400;
      oldServiceType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ServiceType_e Old_ServiceType = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearOldServiceType() {
      bitField0_ = (bitField0_ & ~0x00000400);
      oldServiceType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object newUserPwd_ = "";
    /**
     * <code>string New_UserPwd = 12;</code>
     * @return The newUserPwd.
     */
    public java.lang.String getNewUserPwd() {
      java.lang.Object ref = newUserPwd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newUserPwd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string New_UserPwd = 12;</code>
     * @return The bytes for newUserPwd.
     */
    public com.google.protobuf.ByteString
        getNewUserPwdBytes() {
      java.lang.Object ref = newUserPwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newUserPwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string New_UserPwd = 12;</code>
     * @param value The newUserPwd to set.
     * @return This builder for chaining.
     */
    public Builder setNewUserPwd(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      newUserPwd_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>string New_UserPwd = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewUserPwd() {
      newUserPwd_ = getDefaultInstance().getNewUserPwd();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>string New_UserPwd = 12;</code>
     * @param value The bytes for newUserPwd to set.
     * @return This builder for chaining.
     */
    public Builder setNewUserPwdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      newUserPwd_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private java.lang.Object newServiceDuration_ = "";
    /**
     * <code>string New_ServiceDuration = 13;</code>
     * @return The newServiceDuration.
     */
    public java.lang.String getNewServiceDuration() {
      java.lang.Object ref = newServiceDuration_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newServiceDuration_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string New_ServiceDuration = 13;</code>
     * @return The bytes for newServiceDuration.
     */
    public com.google.protobuf.ByteString
        getNewServiceDurationBytes() {
      java.lang.Object ref = newServiceDuration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newServiceDuration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string New_ServiceDuration = 13;</code>
     * @param value The newServiceDuration to set.
     * @return This builder for chaining.
     */
    public Builder setNewServiceDuration(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      newServiceDuration_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string New_ServiceDuration = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewServiceDuration() {
      newServiceDuration_ = getDefaultInstance().getNewServiceDuration();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string New_ServiceDuration = 13;</code>
     * @param value The bytes for newServiceDuration to set.
     * @return This builder for chaining.
     */
    public Builder setNewServiceDurationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      newServiceDuration_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private int newAge_ ;
    /**
     * <code>int32 New_Age = 14;</code>
     * @return The newAge.
     */
    @java.lang.Override
    public int getNewAge() {
      return newAge_;
    }
    /**
     * <code>int32 New_Age = 14;</code>
     * @param value The newAge to set.
     * @return This builder for chaining.
     */
    public Builder setNewAge(int value) {

      newAge_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 New_Age = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewAge() {
      bitField0_ = (bitField0_ & ~0x00002000);
      newAge_ = 0;
      onChanged();
      return this;
    }

    private int newSex_ ;
    /**
     * <code>int32 New_Sex = 15;</code>
     * @return The newSex.
     */
    @java.lang.Override
    public int getNewSex() {
      return newSex_;
    }
    /**
     * <code>int32 New_Sex = 15;</code>
     * @param value The newSex to set.
     * @return This builder for chaining.
     */
    public Builder setNewSex(int value) {

      newSex_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 New_Sex = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewSex() {
      bitField0_ = (bitField0_ & ~0x00004000);
      newSex_ = 0;
      onChanged();
      return this;
    }

    private int newUserType_ ;
    /**
     * <code>int32 New_UserType = 16;</code>
     * @return The newUserType.
     */
    @java.lang.Override
    public int getNewUserType() {
      return newUserType_;
    }
    /**
     * <code>int32 New_UserType = 16;</code>
     * @param value The newUserType to set.
     * @return This builder for chaining.
     */
    public Builder setNewUserType(int value) {

      newUserType_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 New_UserType = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewUserType() {
      bitField0_ = (bitField0_ & ~0x00008000);
      newUserType_ = 0;
      onChanged();
      return this;
    }

    private int newServiceType_ = 0;
    /**
     * <code>.ServiceType_e New_ServiceType = 17;</code>
     * @return The enum numeric value on the wire for newServiceType.
     */
    @java.lang.Override public int getNewServiceTypeValue() {
      return newServiceType_;
    }
    /**
     * <code>.ServiceType_e New_ServiceType = 17;</code>
     * @param value The enum numeric value on the wire for newServiceType to set.
     * @return This builder for chaining.
     */
    public Builder setNewServiceTypeValue(int value) {
      newServiceType_ = value;
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>.ServiceType_e New_ServiceType = 17;</code>
     * @return The newServiceType.
     */
    @java.lang.Override
    public com.erksystem.protobuf.api.ServiceType_e getNewServiceType() {
      com.erksystem.protobuf.api.ServiceType_e result = com.erksystem.protobuf.api.ServiceType_e.forNumber(newServiceType_);
      return result == null ? com.erksystem.protobuf.api.ServiceType_e.UNRECOGNIZED : result;
    }
    /**
     * <code>.ServiceType_e New_ServiceType = 17;</code>
     * @param value The newServiceType to set.
     * @return This builder for chaining.
     */
    public Builder setNewServiceType(com.erksystem.protobuf.api.ServiceType_e value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00010000;
      newServiceType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ServiceType_e New_ServiceType = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewServiceType() {
      bitField0_ = (bitField0_ & ~0x00010000);
      newServiceType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UpdateUserInfoRP_m)
  }

  // @@protoc_insertion_point(class_scope:UpdateUserInfoRP_m)
  private static final com.erksystem.protobuf.api.UpdateUserInfoRP_m DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.erksystem.protobuf.api.UpdateUserInfoRP_m();
  }

  public static com.erksystem.protobuf.api.UpdateUserInfoRP_m getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateUserInfoRP_m>
      PARSER = new com.google.protobuf.AbstractParser<UpdateUserInfoRP_m>() {
    @java.lang.Override
    public UpdateUserInfoRP_m parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateUserInfoRP_m> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateUserInfoRP_m> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.erksystem.protobuf.api.UpdateUserInfoRP_m getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

